import { SinanFormTemplate, SinanField, SINAN_COMMON_FIELDS, SINAN_FORM_GROUPS } from "../template-types";

const COLERA_FIELDS: SinanField[] = [
  {
    key: "col_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "col_diarreia",
    label: "Diarreia",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 35,
    sinanCode: "DIARREIA",
    width: "quarter",
  },
  {
    key: "col_tipo_diarreia",
    label: "Tipo de Diarreia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Aquosa (água de arroz)" },
      { value: "2", label: "Mucosa" },
      { value: "3", label: "Sanguinolenta" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "TP_DIAR",
    dependsOn: { field: "col_diarreia", value: "1" },
    width: "half",
  },
  {
    key: "col_vomito",
    label: "Vômito",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "VOMITO",
    width: "quarter",
  },
  {
    key: "col_desidratacao",
    label: "Desidratação",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sem desidratação" },
      { value: "2", label: "Leve" },
      { value: "3", label: "Moderada" },
      { value: "4", label: "Grave" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "DESIDRAT",
    width: "half",
  },
  {
    key: "col_caimbras",
    label: "Cãibras",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "CAIMBRAS",
    width: "quarter",
  },
  {
    key: "col_viagem",
    label: "Viagem para Área Endêmica (5 dias)",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "VIAGEM",
    width: "half",
  },
  {
    key: "col_coprocultura",
    label: "Coprocultura",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Vibrio cholerae O1" },
      { value: "2", label: "Vibrio cholerae O139" },
      { value: "3", label: "Vibrio cholerae NAG" },
      { value: "4", label: "Negativa" },
      { value: "5", label: "Não realizada" },
    ],
    order: 50,
    sinanCode: "COPROCULT",
    width: "half",
  },
];

const BOTULISMO_FIELDS: SinanField[] = [
  {
    key: "bot_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "bot_tipo",
    label: "Tipo de Botulismo",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Alimentar" },
      { value: "2", label: "Por ferimentos" },
      { value: "3", label: "Intestinal (lactente)" },
      { value: "4", label: "Inalação" },
      { value: "9", label: "Indeterminado" },
    ],
    order: 35,
    sinanCode: "TP_BOTUL",
    width: "half",
  },
  {
    key: "bot_visao_turva",
    label: "Visão Turva/Diplopia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "VISAO",
    width: "quarter",
  },
  {
    key: "bot_ptose",
    label: "Ptose Palpebral",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "PTOSE",
    width: "quarter",
  },
  {
    key: "bot_disfagia",
    label: "Disfagia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "DISFAGIA",
    width: "quarter",
  },
  {
    key: "bot_disartria",
    label: "Disartria",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "DISARTRIA",
    width: "quarter",
  },
  {
    key: "bot_fraqueza_muscular",
    label: "Fraqueza Muscular Descendente",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "FRAQUEZA",
    width: "quarter",
  },
  {
    key: "bot_constipacao",
    label: "Constipação",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 41,
    sinanCode: "CONSTIP",
    width: "quarter",
  },
  {
    key: "bot_alimento_suspeito",
    label: "Alimento Suspeito Identificado",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "ALIM_SUSP",
    width: "half",
  },
  {
    key: "bot_tipo_alimento",
    label: "Tipo de Alimento",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Conserva caseira" },
      { value: "2", label: "Conserva industrializada" },
      { value: "3", label: "Mel" },
      { value: "4", label: "Embutido/defumado" },
      { value: "5", label: "Outro" },
    ],
    order: 35,
    sinanCode: "TP_ALIM",
    dependsOn: { field: "bot_alimento_suspeito", value: "1" },
    width: "half",
  },
  {
    key: "bot_toxina_soro",
    label: "Pesquisa de Toxina no Soro",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positivo" },
      { value: "2", label: "Negativo" },
      { value: "3", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "TOX_SORO",
    width: "quarter",
  },
  {
    key: "bot_toxina_alimento",
    label: "Pesquisa de Toxina no Alimento",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positivo" },
      { value: "2", label: "Negativo" },
      { value: "3", label: "Não realizado" },
    ],
    order: 51,
    sinanCode: "TOX_ALIM",
    width: "quarter",
  },
  {
    key: "bot_soro_antibotulínico",
    label: "Uso de Soro Antibotulínico",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 60,
    sinanCode: "SORO_BOT",
    width: "quarter",
  },
];

const FEBRE_TIFOIDE_FIELDS: SinanField[] = [
  {
    key: "tif_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "tif_febre",
    label: "Febre",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 35,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "tif_cefaleia",
    label: "Cefaleia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "CEFALEIA",
    width: "quarter",
  },
  {
    key: "tif_dor_abdominal",
    label: "Dor Abdominal",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "DOR_ABD",
    width: "quarter",
  },
  {
    key: "tif_diarreia",
    label: "Diarreia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "DIARREIA",
    width: "quarter",
  },
  {
    key: "tif_constipacao",
    label: "Constipação",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "CONSTIP",
    width: "quarter",
  },
  {
    key: "tif_roseolas",
    label: "Roséolas Tíficas",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "ROSEOLAS",
    width: "quarter",
  },
  {
    key: "tif_hepatoesplenomegalia",
    label: "Hepatoesplenomegalia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 41,
    sinanCode: "HEPATOESPL",
    width: "quarter",
  },
  {
    key: "tif_hemocultura",
    label: "Hemocultura",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Salmonella typhi" },
      { value: "2", label: "Salmonella paratyphi" },
      { value: "3", label: "Negativa" },
      { value: "4", label: "Não realizada" },
    ],
    order: 50,
    sinanCode: "HEMOCULT",
    width: "half",
  },
  {
    key: "tif_coprocultura",
    label: "Coprocultura",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Salmonella typhi" },
      { value: "2", label: "Salmonella paratyphi" },
      { value: "3", label: "Negativa" },
      { value: "4", label: "Não realizada" },
    ],
    order: 51,
    sinanCode: "COPROCULT",
    width: "half",
  },
];

const DTA_SURTO_FIELDS: SinanField[] = [
  {
    key: "dta_classificacao",
    label: "Classificação do Surto",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Inconclusivo" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "dta_num_expostos",
    label: "Número de Expostos",
    type: "number",
    required: false,
    group: "dados_gerais",
    order: 20,
    sinanCode: "NUM_EXP",
    width: "quarter",
  },
  {
    key: "dta_num_doentes",
    label: "Número de Doentes",
    type: "number",
    required: false,
    group: "dados_gerais",
    order: 21,
    sinanCode: "NUM_DOENT",
    width: "quarter",
  },
  {
    key: "dta_num_obitos",
    label: "Número de Óbitos",
    type: "number",
    required: false,
    group: "dados_gerais",
    order: 22,
    sinanCode: "NUM_OBIT",
    width: "quarter",
  },
  {
    key: "dta_local_ocorrencia",
    label: "Local de Ocorrência do Surto",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Domicílio" },
      { value: "2", label: "Restaurante/bar" },
      { value: "3", label: "Escola/creche" },
      { value: "4", label: "Hospital/instituição de saúde" },
      { value: "5", label: "Evento social/festa" },
      { value: "6", label: "Refeitório industrial" },
      { value: "7", label: "Outro" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "LOC_OCORR",
    width: "half",
  },
  {
    key: "dta_alimento_suspeito",
    label: "Alimento Suspeito",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim, identificado" },
      { value: "2", label: "Não identificado" },
    ],
    order: 35,
    sinanCode: "ALIM_SUSP",
    width: "half",
  },
  {
    key: "dta_sintomas_diarreia",
    label: "Diarreia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 35,
    sinanCode: "DIARREIA",
    width: "quarter",
  },
  {
    key: "dta_sintomas_vomito",
    label: "Vômito",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 36,
    sinanCode: "VOMITO",
    width: "quarter",
  },
  {
    key: "dta_sintomas_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 37,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "dta_sintomas_dor_abdominal",
    label: "Dor Abdominal",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 38,
    sinanCode: "DOR_ABD",
    width: "quarter",
  },
  {
    key: "dta_agente_etiologico",
    label: "Agente Etiológico Identificado",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Salmonella spp." },
      { value: "2", label: "E. coli patogênica" },
      { value: "3", label: "Staphylococcus aureus" },
      { value: "4", label: "Bacillus cereus" },
      { value: "5", label: "Clostridium perfringens" },
      { value: "6", label: "Norovírus" },
      { value: "7", label: "Rotavírus" },
      { value: "8", label: "Outro" },
      { value: "9", label: "Não identificado" },
    ],
    order: 50,
    sinanCode: "AG_ETIOL",
    width: "half",
  },
];

export const COLERA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_colera",
  nome: "Cólera",
  agravoCode: "A00",
  cid10: "A00",
  categoria: "alimentares",
  versaoFicha: "COLERA_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...COLERA_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "col_diarreia",
  ],
};

export const BOTULISMO_TEMPLATE: SinanFormTemplate = {
  id: "sinan_botulismo",
  nome: "Botulismo",
  agravoCode: "A05.1",
  cid10: "A05.1",
  categoria: "alimentares",
  versaoFicha: "BOTUL_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...BOTULISMO_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const FEBRE_TIFOIDE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_febre_tifoide",
  nome: "Febre Tifoide",
  agravoCode: "A01.0",
  cid10: "A01.0",
  categoria: "alimentares",
  versaoFicha: "TIFOID_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...FEBRE_TIFOIDE_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "tif_febre",
  ],
};

export const DTA_SURTO_TEMPLATE: SinanFormTemplate = {
  id: "sinan_dta_surto",
  nome: "Surto de DTA (Doença Transmitida por Alimentos)",
  agravoCode: "SURTO",
  cid10: "A05.9",
  categoria: "alimentares",
  versaoFicha: "DTA_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...DTA_SURTO_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
  ],
};
