import { SinanFormTemplate, SinanField, SINAN_COMMON_FIELDS, SINAN_FORM_GROUPS } from "../template-types";

const CHIKUNGUNYA_SPECIFIC_FIELDS: SinanField[] = [
  {
    key: "chik_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "10", label: "Chikungunya" },
      { value: "11", label: "Chikungunya fase aguda" },
      { value: "12", label: "Chikungunya fase crônica" },
      { value: "5", label: "Descartado" },
      { value: "8", label: "Inconclusivo" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "chik_hospitalizacao",
    label: "Houve Hospitalização",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "HOSPITAL",
    width: "quarter",
  },
  {
    key: "chik_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "chik_artralgia",
    label: "Artralgia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "ARTRALGIA",
    width: "quarter",
  },
  {
    key: "chik_artrite",
    label: "Artrite",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "ARTRITE",
    width: "quarter",
  },
  {
    key: "chik_cefaleia",
    label: "Cefaleia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "CEFALEIA",
    width: "quarter",
  },
  {
    key: "chik_exantema",
    label: "Exantema",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "EXANTEMA",
    width: "quarter",
  },
  {
    key: "chik_mialgia",
    label: "Mialgia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "MIALGIA",
    width: "quarter",
  },
  {
    key: "chik_conjuntivite",
    label: "Hiperemia Conjuntival",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 41,
    sinanCode: "CONJUNTVT",
    width: "quarter",
  },
  {
    key: "chik_igm",
    label: "Sorologia IgM",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "RES_IgM",
    width: "quarter",
  },
  {
    key: "chik_rtpcr",
    label: "RT-PCR",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Detectável" },
      { value: "2", label: "Não detectável" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 51,
    sinanCode: "RTPCR",
    width: "quarter",
  },
];

const ZIKA_SPECIFIC_FIELDS: SinanField[] = [
  {
    key: "zika_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
      { value: "8", label: "Inconclusivo" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "zika_exantema",
    label: "Exantema",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "EXANTEMA",
    width: "quarter",
  },
  {
    key: "zika_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "zika_conjuntivite",
    label: "Hiperemia Conjuntival",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "CONJUNTVT",
    width: "quarter",
  },
  {
    key: "zika_artralgia",
    label: "Artralgia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "ARTRALGIA",
    width: "quarter",
  },
  {
    key: "zika_edema_periarticular",
    label: "Edema Periarticular",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "EDEMA_PER",
    width: "quarter",
  },
  {
    key: "zika_cefaleia",
    label: "Cefaleia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "CEFALEIA",
    width: "quarter",
  },
  {
    key: "zika_prurido",
    label: "Prurido",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 41,
    sinanCode: "PRURIDO",
    width: "quarter",
  },
  {
    key: "zika_rtpcr",
    label: "RT-PCR para Zika",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Detectável" },
      { value: "2", label: "Não detectável" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "RTPCR_ZK",
    width: "quarter",
  },
];

const FEBRE_AMARELA_SPECIFIC_FIELDS: SinanField[] = [
  {
    key: "fa_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado" },
      { value: "2", label: "Descartado" },
      { value: "8", label: "Inconclusivo" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "fa_vacinacao",
    label: "Vacinação Prévia para Febre Amarela",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "VACINA_FA",
    width: "quarter",
  },
  {
    key: "fa_dt_vacina",
    label: "Data da Última Vacina",
    type: "date",
    required: false,
    group: "antecedentes",
    order: 35,
    sinanCode: "DT_VAC_FA",
    dependsOn: { field: "fa_vacinacao", value: "1" },
    width: "third",
  },
  {
    key: "fa_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "fa_ictericia",
    label: "Icterícia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "ICTERICIA",
    width: "quarter",
  },
  {
    key: "fa_cefaleia",
    label: "Cefaleia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "CEFALEIA",
    width: "quarter",
  },
  {
    key: "fa_mialgia",
    label: "Mialgia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "MIALGIA",
    width: "quarter",
  },
  {
    key: "fa_nausea",
    label: "Náuseas/Vômitos",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "NAUSEA",
    width: "quarter",
  },
  {
    key: "fa_hemorragia",
    label: "Manifestações Hemorrágicas",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 41,
    sinanCode: "HEMORRG",
    width: "quarter",
  },
  {
    key: "fa_oliguria",
    label: "Oligúria/Anúria",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 42,
    sinanCode: "OLIGURIA",
    width: "quarter",
  },
  {
    key: "fa_igm",
    label: "Sorologia IgM",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "RES_IgM",
    width: "quarter",
  },
  {
    key: "fa_isolamento",
    label: "Isolamento Viral",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positivo" },
      { value: "2", label: "Negativo" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 51,
    sinanCode: "ISOLAMENT",
    width: "quarter",
  },
  {
    key: "fa_rtpcr",
    label: "RT-PCR",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positivo" },
      { value: "2", label: "Negativo" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 52,
    sinanCode: "RTPCR",
    width: "quarter",
  },
  {
    key: "fa_histopatologia",
    label: "Histopatologia",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Compatível" },
      { value: "2", label: "Não compatível" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 53,
    sinanCode: "HISTOPATL",
    width: "quarter",
  },
];

export const CHIKUNGUNYA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_chikungunya",
  nome: "Chikungunya",
  agravoCode: "A92.0",
  cid10: "A92.0",
  categoria: "arboviroses",
  versaoFicha: "DENGCHIK_v5.1",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...CHIKUNGUNYA_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const ZIKA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_zika",
  nome: "Zika Vírus",
  agravoCode: "A92.8",
  cid10: "A92.8",
  categoria: "arboviroses",
  versaoFicha: "ZIKA_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...ZIKA_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const FEBRE_AMARELA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_febre_amarela",
  nome: "Febre Amarela",
  agravoCode: "A95",
  cid10: "A95",
  categoria: "arboviroses",
  versaoFicha: "FEAM_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...FEBRE_AMARELA_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

const ARBOVIROSE_GENERICA_FIELDS: SinanField[] = [
  {
    key: "arbo_febre",
    label: "Febre",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 35,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "arbo_cefaleia",
    label: "Cefaleia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "CEFALEIA",
    width: "quarter",
  },
  {
    key: "arbo_mialgia",
    label: "Mialgia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "MIALGIA",
    width: "quarter",
  },
  {
    key: "arbo_artralgia",
    label: "Artralgia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "ARTRALGIA",
    width: "quarter",
  },
  {
    key: "arbo_exantema",
    label: "Exantema",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "EXANTEMA",
    width: "quarter",
  },
  {
    key: "arbo_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "arbo_rt_pcr",
    label: "RT-PCR",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positivo" },
      { value: "2", label: "Negativo" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "RT_PCR",
    width: "quarter",
  },
  {
    key: "arbo_sorologia",
    label: "Sorologia (IgM/IgG)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 51,
    sinanCode: "SOROL",
    width: "quarter",
  },
];

const MICROCEFALIA_FIELDS: SinanField[] = [
  {
    key: "mic_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado - Infecção congênita Zika" },
      { value: "2", label: "Confirmado - Outra etiologia" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "mic_perimetro_cefalico",
    label: "Perímetro Cefálico (cm)",
    type: "number",
    required: true,
    group: "clinicos",
    order: 35,
    sinanCode: "PC",
    width: "quarter",
  },
  {
    key: "mic_ig_nascimento",
    label: "Idade Gestacional ao Nascer (semanas)",
    type: "number",
    required: false,
    group: "clinicos",
    order: 36,
    sinanCode: "IG_NASC",
    width: "quarter",
  },
  {
    key: "mic_alteracoes_snc",
    label: "Alterações SNC na Imagem",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "ALT_SNC",
    width: "quarter",
  },
  {
    key: "mic_mae_exantema",
    label: "Mãe com Exantema na Gestação",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 30,
    sinanCode: "MAE_EXANT",
    width: "half",
  },
  {
    key: "mic_rt_pcr_rn",
    label: "RT-PCR Zika no RN",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positivo" },
      { value: "2", label: "Negativo" },
      { value: "3", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "PCR_RN",
    width: "quarter",
  },
];

export const ENCEFALITE_ARBOVIRUS_TEMPLATE: SinanFormTemplate = {
  id: "sinan_encefalite_arbovirus",
  nome: "Encefalite por Arbovírus",
  agravoCode: "A83",
  cid10: "A83",
  categoria: "arboviroses",
  versaoFicha: "ENCEFAL_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...ARBOVIROSE_GENERICA_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const FEBRE_NILO_TEMPLATE: SinanFormTemplate = {
  id: "sinan_febre_nilo",
  nome: "Febre do Nilo Ocidental",
  agravoCode: "A92.3",
  cid10: "A92.3",
  categoria: "arboviroses",
  versaoFicha: "NILO_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...ARBOVIROSE_GENERICA_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const FEBRE_OROPOUCHE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_oropouche",
  nome: "Febre Oropouche",
  agravoCode: "A93.0",
  cid10: "A93.0",
  categoria: "arboviroses",
  versaoFicha: "OROP_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...ARBOVIROSE_GENERICA_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const FEBRE_MAYARO_TEMPLATE: SinanFormTemplate = {
  id: "sinan_mayaro",
  nome: "Febre Mayaro",
  agravoCode: "A93.8",
  cid10: "A93.8",
  categoria: "arboviroses",
  versaoFicha: "MAYARO_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...ARBOVIROSE_GENERICA_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const MICROCEFALIA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_microcefalia",
  nome: "Microcefalia e/ou Alterações do SNC",
  agravoCode: "Q02",
  cid10: "Q02",
  categoria: "arboviroses",
  versaoFicha: "MICRO_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...MICROCEFALIA_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

const DENGUE_HEMORRAGICA_FIELDS: SinanField[] = [
  {
    key: "dh_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Dengue com sinais de alarme" },
      { value: "2", label: "Dengue grave" },
      { value: "3", label: "FHD Grau I" },
      { value: "4", label: "FHD Grau II" },
      { value: "5", label: "FHD Grau III" },
      { value: "6", label: "FHD Grau IV" },
      { value: "7", label: "Síndrome do choque dengue" },
      { value: "8", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "dh_prova_laco",
    label: "Prova do Laço",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Positiva" },
      { value: "2", label: "Negativa" },
      { value: "3", label: "Não realizada" },
    ],
    order: 35,
    sinanCode: "PROVA_LACO",
    width: "quarter",
  },
  {
    key: "dh_sangramento",
    label: "Sangramento",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "SANGRAM",
    width: "quarter",
  },
  {
    key: "dh_hipotensao",
    label: "Hipotensão",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "HIPOTEN",
    width: "quarter",
  },
  {
    key: "dh_hepatomegalia",
    label: "Hepatomegalia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "HEPATOMEG",
    width: "quarter",
  },
  {
    key: "dh_plaquetas",
    label: "Plaquetopenia (<100.000)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "3", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "PLAQUETAS",
    width: "quarter",
  },
  {
    key: "dh_hematocrito",
    label: "Hemoconcentração (>20%)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "3", label: "Não realizado" },
    ],
    order: 51,
    sinanCode: "HEMOCONCEN",
    width: "quarter",
  },
  {
    key: "dh_ns1",
    label: "Antígeno NS1",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Não realizado" },
    ],
    order: 52,
    sinanCode: "NS1",
    width: "quarter",
  },
];

export const DENGUE_HEMORRAGICA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_dengue_hemorragica",
  nome: "Dengue Hemorrágica / FHD",
  agravoCode: "A91",
  cid10: "A91",
  categoria: "arboviroses",
  versaoFicha: "DENGHEMOR_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...DENGUE_HEMORRAGICA_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};
