import { SinanFormTemplate, SinanField, SINAN_COMMON_FIELDS, SINAN_FORM_GROUPS } from "../template-types";

const DENGUE_SPECIFIC_FIELDS: SinanField[] = [
  {
    key: "dengue_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "10", label: "Dengue" },
      { value: "11", label: "Dengue com sinais de alarme" },
      { value: "12", label: "Dengue grave" },
      { value: "5", label: "Descartado" },
      { value: "8", label: "Inconclusivo" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "dengue_sorotipo",
    label: "Sorotipo",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "DENV-1" },
      { value: "2", label: "DENV-2" },
      { value: "3", label: "DENV-3" },
      { value: "4", label: "DENV-4" },
      { value: "9", label: "Ignorado" },
    ],
    order: 50,
    sinanCode: "SOROTIPO",
    width: "quarter",
  },
  {
    key: "dengue_hospitalizacao",
    label: "Houve Hospitalização",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "HOSPITAL",
    width: "quarter",
  },
  {
    key: "dengue_dt_internacao",
    label: "Data da Internação",
    type: "date",
    required: false,
    group: "clinicos",
    order: 41,
    sinanCode: "DT_INTERNA",
    dependsOn: { field: "dengue_hospitalizacao", value: "1" },
    width: "third",
  },
  {
    key: "dengue_uf_internacao",
    label: "UF Internação",
    type: "select",
    required: false,
    group: "clinicos",
    order: 42,
    sinanCode: "SG_UF_INTE",
    dependsOn: { field: "dengue_hospitalizacao", value: "1" },
    width: "quarter",
  },
  {
    key: "dengue_municipio_internacao",
    label: "Município Internação",
    type: "text",
    required: false,
    group: "clinicos",
    order: 43,
    sinanCode: "ID_MN_INTE",
    dependsOn: { field: "dengue_hospitalizacao", value: "1" },
    width: "half",
  },
  {
    key: "dengue_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "dengue_mialgia",
    label: "Mialgia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "MIALGIA",
    width: "quarter",
  },
  {
    key: "dengue_cefaleia",
    label: "Cefaleia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "CEFALEIA",
    width: "quarter",
  },
  {
    key: "dengue_exantema",
    label: "Exantema",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "EXANTEMA",
    width: "quarter",
  },
  {
    key: "dengue_vomito",
    label: "Vômito",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "VOMITO",
    width: "quarter",
  },
  {
    key: "dengue_nausea",
    label: "Náusea",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "NAUSEA",
    width: "quarter",
  },
  {
    key: "dengue_dor_costas",
    label: "Dor nas Costas",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 41,
    sinanCode: "DOR_COSTA",
    width: "quarter",
  },
  {
    key: "dengue_conjuntivite",
    label: "Conjuntivite",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 42,
    sinanCode: "CONJUNTVT",
    width: "quarter",
  },
  {
    key: "dengue_artrite",
    label: "Artrite",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 43,
    sinanCode: "ARTRITE",
    width: "quarter",
  },
  {
    key: "dengue_artralgia",
    label: "Artralgia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 44,
    sinanCode: "ARTRALGIA",
    width: "quarter",
  },
  {
    key: "dengue_petequia",
    label: "Petéquias",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 45,
    sinanCode: "PETEQUIA",
    width: "quarter",
  },
  {
    key: "dengue_leucopenia",
    label: "Leucopenia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 46,
    sinanCode: "LEUCOPENI",
    width: "quarter",
  },
  {
    key: "dengue_prova_laco",
    label: "Prova do Laço Positiva",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 47,
    sinanCode: "LACO",
    width: "quarter",
  },
  {
    key: "dengue_dor_retro",
    label: "Dor Retro-orbitária",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 48,
    sinanCode: "DOR_RETRO",
    width: "quarter",
  },
  {
    key: "dengue_diabetes",
    label: "Diabetes",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "DIABETES",
    width: "quarter",
  },
  {
    key: "dengue_hematologicas",
    label: "Doenças Hematológicas",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "HEMATOLOG",
    width: "quarter",
  },
  {
    key: "dengue_hepatopatia",
    label: "Hepatopatia",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "HEPATOPAT",
    width: "quarter",
  },
  {
    key: "dengue_renal",
    label: "Doença Renal",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "RENAL",
    width: "quarter",
  },
  {
    key: "dengue_hipertensao",
    label: "Hipertensão",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "HIPERTENS",
    width: "quarter",
  },
  {
    key: "dengue_acido_peptica",
    label: "Doença Ácido-péptica",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "ACIDO_PEP",
    width: "quarter",
  },
  {
    key: "dengue_auto_imune",
    label: "Doença Auto-imune",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "AUTO_IMUN",
    width: "quarter",
  },
  {
    key: "dengue_sinais_alarme",
    label: "Apresentou Sinais de Alarme",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 50,
    sinanCode: "ALARME",
    width: "half",
  },
  {
    key: "dengue_dor_abdominal",
    label: "Dor Abdominal Intensa",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 51,
    sinanCode: "DOR_ABDOM",
    dependsOn: { field: "dengue_sinais_alarme", value: "1" },
    width: "quarter",
  },
  {
    key: "dengue_vomito_persistente",
    label: "Vômitos Persistentes",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 52,
    sinanCode: "VOMITO_PE",
    dependsOn: { field: "dengue_sinais_alarme", value: "1" },
    width: "quarter",
  },
  {
    key: "dengue_acumulo_liquidos",
    label: "Acúmulo de Líquidos",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 53,
    sinanCode: "ACUM_LIQ",
    dependsOn: { field: "dengue_sinais_alarme", value: "1" },
    width: "quarter",
  },
  {
    key: "dengue_sangramento_mucosa",
    label: "Sangramento de Mucosa",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 54,
    sinanCode: "SANG_MUCO",
    dependsOn: { field: "dengue_sinais_alarme", value: "1" },
    width: "quarter",
  },
  {
    key: "dengue_letargia",
    label: "Letargia/Irritabilidade",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 55,
    sinanCode: "LETARGIA",
    dependsOn: { field: "dengue_sinais_alarme", value: "1" },
    width: "quarter",
  },
  {
    key: "dengue_hepatomegalia",
    label: "Hepatomegalia >2cm",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 56,
    sinanCode: "HEPATOMEG",
    dependsOn: { field: "dengue_sinais_alarme", value: "1" },
    width: "quarter",
  },
  {
    key: "dengue_aumento_hematocrito",
    label: "Aumento do Hematócrito",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 57,
    sinanCode: "HEMATOCRT",
    dependsOn: { field: "dengue_sinais_alarme", value: "1" },
    width: "quarter",
  },
  {
    key: "dengue_igm_soro",
    label: "Sorologia IgM",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 60,
    sinanCode: "RES_IgM",
    width: "quarter",
  },
  {
    key: "dengue_ns1",
    label: "NS1",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 61,
    sinanCode: "NS1",
    width: "quarter",
  },
  {
    key: "dengue_isolamento",
    label: "Isolamento Viral",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positivo" },
      { value: "2", label: "Negativo" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 62,
    sinanCode: "ISOLAMENT",
    width: "quarter",
  },
  {
    key: "dengue_rtpcr",
    label: "RT-PCR",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positivo" },
      { value: "2", label: "Negativo" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 63,
    sinanCode: "RTPCR",
    width: "quarter",
  },
  {
    key: "dengue_histopatologia",
    label: "Histopatologia",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Compatível" },
      { value: "2", label: "Não compatível" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 64,
    sinanCode: "HISTOPATL",
    width: "quarter",
  },
  {
    key: "dengue_imunohistoquimica",
    label: "Imuno-histoquímica",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positiva" },
      { value: "2", label: "Negativa" },
      { value: "3", label: "Inconclusiva" },
      { value: "4", label: "Não realizada" },
    ],
    order: 65,
    sinanCode: "IMUNOHIST",
    width: "quarter",
  },
];

export const DENGUE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_dengue",
  nome: "Dengue",
  agravoCode: "A90",
  cid10: "A90",
  categoria: "arboviroses",
  versaoFicha: "DENGCHIK_v5.1",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...DENGUE_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};
