import { SinanFormTemplate, SinanField, SINAN_COMMON_FIELDS, SINAN_FORM_GROUPS } from "../template-types";

const LEISHMANIOSE_VISCERAL_FIELDS: SinanField[] = [
  {
    key: "lv_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "lv_tipo_entrada",
    label: "Tipo de Entrada",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Caso novo" },
      { value: "2", label: "Recidiva" },
      { value: "3", label: "Transferência" },
    ],
    order: 35,
    sinanCode: "TIPO_ENTRA",
    width: "half",
  },
  {
    key: "lv_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "lv_fraqueza",
    label: "Fraqueza",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "FRAQUEZA",
    width: "quarter",
  },
  {
    key: "lv_emagrecimento",
    label: "Emagrecimento",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "EMAGRECIM",
    width: "quarter",
  },
  {
    key: "lv_tosse",
    label: "Tosse e/ou Diarreia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "TOSSE_DIAR",
    width: "quarter",
  },
  {
    key: "lv_palidez",
    label: "Palidez",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "PALIDEZ",
    width: "quarter",
  },
  {
    key: "lv_esplenomegalia",
    label: "Esplenomegalia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 41,
    sinanCode: "ESPLENOMEG",
    width: "quarter",
  },
  {
    key: "lv_hepatomegalia",
    label: "Hepatomegalia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 42,
    sinanCode: "HEPATOMEG",
    width: "quarter",
  },
  {
    key: "lv_ictericia",
    label: "Icterícia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 43,
    sinanCode: "ICTERICIA",
    width: "quarter",
  },
  {
    key: "lv_hemorragia",
    label: "Manifestações Hemorrágicas",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 44,
    sinanCode: "HEMORRG",
    width: "quarter",
  },
  {
    key: "lv_edema",
    label: "Edema",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 45,
    sinanCode: "EDEMA",
    width: "quarter",
  },
  {
    key: "lv_coinfeccao_hiv",
    label: "Coinfecção HIV",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "HIV",
    width: "quarter",
  },
  {
    key: "lv_parasitologico",
    label: "Diagnóstico Parasitológico",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positivo" },
      { value: "2", label: "Negativo" },
      { value: "3", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "PARASIT",
    width: "quarter",
  },
  {
    key: "lv_imunologico",
    label: "Diagnóstico Imunológico",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Não realizado" },
    ],
    order: 51,
    sinanCode: "IMUNOLOG",
    width: "quarter",
  },
  {
    key: "lv_droga",
    label: "Droga Inicial Administrada",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Antimonial pentavalente" },
      { value: "2", label: "Anfotericina B lipossomal" },
      { value: "3", label: "Anfotericina B desoxicolato" },
      { value: "4", label: "Pentamidina" },
      { value: "5", label: "Outras" },
      { value: "6", label: "Não utilizada" },
    ],
    order: 60,
    sinanCode: "DROGA_INIC",
    width: "half",
  },
];

const LEISHMANIOSE_TEGUMENTAR_FIELDS: SinanField[] = [
  {
    key: "lt_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "lt_forma_clinica",
    label: "Forma Clínica",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Cutânea" },
      { value: "2", label: "Mucosa" },
      { value: "3", label: "Cutâneo-mucosa" },
    ],
    order: 35,
    sinanCode: "FORM_CLIN",
    width: "half",
  },
  {
    key: "lt_tipo_entrada",
    label: "Tipo de Entrada",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Caso novo" },
      { value: "2", label: "Recidiva" },
      { value: "3", label: "Transferência" },
    ],
    order: 36,
    sinanCode: "TIPO_ENTRA",
    width: "half",
  },
  {
    key: "lt_numero_lesoes",
    label: "Número de Lesões",
    type: "number",
    required: false,
    group: "clinicos",
    order: 37,
    sinanCode: "NUM_LESOES",
    validation: { min: 1, max: 99 },
    width: "quarter",
  },
  {
    key: "lt_intradermorreacao",
    label: "Intradermorreação de Montenegro",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positiva" },
      { value: "2", label: "Negativa" },
      { value: "3", label: "Não realizada" },
    ],
    order: 50,
    sinanCode: "IDRM",
    width: "quarter",
  },
  {
    key: "lt_parasitologico",
    label: "Diagnóstico Parasitológico",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positivo" },
      { value: "2", label: "Negativo" },
      { value: "3", label: "Não realizado" },
    ],
    order: 51,
    sinanCode: "PARASIT",
    width: "quarter",
  },
  {
    key: "lt_droga",
    label: "Droga Inicial Administrada",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Antimonial pentavalente" },
      { value: "2", label: "Anfotericina B" },
      { value: "3", label: "Pentamidina" },
      { value: "4", label: "Outras" },
      { value: "5", label: "Não utilizada" },
    ],
    order: 60,
    sinanCode: "DROGA_INIC",
    width: "half",
  },
];

const MALARIA_FIELDS: SinanField[] = [
  {
    key: "mal_classificacao",
    label: "Resultado da Lâmina/Teste Rápido",
    type: "select",
    required: true,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Falciparum" },
      { value: "2", label: "Vivax" },
      { value: "3", label: "Mista (F+V)" },
      { value: "4", label: "Malariae" },
      { value: "5", label: "Ovale" },
      { value: "6", label: "Negativo" },
      { value: "9", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "RES_EXAM",
    width: "half",
  },
  {
    key: "mal_tipo_lamina",
    label: "Tipo de Lâmina",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Detecção ativa" },
      { value: "2", label: "Detecção passiva" },
      { value: "3", label: "LVC (busca ativa)" },
    ],
    order: 51,
    sinanCode: "TP_LAMINA",
    width: "quarter",
  },
  {
    key: "mal_parasitemia",
    label: "Parasitemia (cruzes)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "+/2" },
      { value: "2", label: "+" },
      { value: "3", label: "++" },
      { value: "4", label: "+++" },
      { value: "5", label: "++++" },
    ],
    order: 52,
    sinanCode: "PARASITE",
    width: "quarter",
  },
  {
    key: "mal_hospitalizacao",
    label: "Houve Hospitalização",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "HOSPITAL",
    width: "quarter",
  },
  {
    key: "mal_gravidez",
    label: "Malária na Gravidez",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "3", label: "Não se aplica" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "GRAVIDEZ",
    width: "quarter",
  },
  {
    key: "mal_sintomas",
    label: "Apresentou Sintomas",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 36,
    sinanCode: "SINTOMAS",
    width: "quarter",
  },
  {
    key: "mal_esquema_tratamento",
    label: "Esquema de Tratamento",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "P. vivax" },
      { value: "2", label: "P. falciparum" },
      { value: "3", label: "Mista" },
      { value: "4", label: "P. malariae" },
      { value: "5", label: "Malária grave e complicada" },
      { value: "6", label: "Outro" },
    ],
    order: 60,
    sinanCode: "ESQ_TRAT",
    width: "half",
  },
];

const CHAGAS_AGUDO_FIELDS: SinanField[] = [
  {
    key: "cha_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado" },
      { value: "2", label: "Descartado" },
      { value: "8", label: "Inconclusivo" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "cha_modo_transmissao",
    label: "Provável Modo de Transmissão",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Vetorial" },
      { value: "2", label: "Oral" },
      { value: "3", label: "Vertical" },
      { value: "4", label: "Transfusional" },
      { value: "5", label: "Acidental" },
      { value: "6", label: "Outro" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "MODO_TRANS",
    width: "half",
  },
  {
    key: "cha_alimento_suspeito",
    label: "Alimento Suspeito (se oral)",
    type: "text",
    required: false,
    group: "antecedentes",
    order: 35,
    sinanCode: "ALIM_SUSP",
    dependsOn: { field: "cha_modo_transmissao", value: "2" },
    width: "full",
  },
  {
    key: "cha_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "cha_cefaleia",
    label: "Cefaleia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "CEFALEIA",
    width: "quarter",
  },
  {
    key: "cha_mialgia",
    label: "Mialgia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "MIALGIA",
    width: "quarter",
  },
  {
    key: "cha_edema_face",
    label: "Edema de Face",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "EDEMA_FACE",
    width: "quarter",
  },
  {
    key: "cha_sinais_porta_entrada",
    label: "Sinais de Porta de Entrada (Chagoma/Romaña)",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "PORTA_ENT",
    width: "half",
  },
  {
    key: "cha_exame_parasitologico",
    label: "Exame Parasitológico Direto",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positivo" },
      { value: "2", label: "Negativo" },
      { value: "3", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "EX_PARASIT",
    width: "quarter",
  },
  {
    key: "cha_sorologia",
    label: "Sorologia IgG (dois testes)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 51,
    sinanCode: "SOROLOGIA",
    width: "quarter",
  },
];

export const LEISHMANIOSE_VISCERAL_TEMPLATE: SinanFormTemplate = {
  id: "sinan_leishmaniose_visceral",
  nome: "Leishmaniose Visceral",
  agravoCode: "B55.0",
  cid10: "B55.0",
  categoria: "endemicas",
  versaoFicha: "LV_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...LEISHMANIOSE_VISCERAL_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "lv_tipo_entrada",
  ],
};

export const LEISHMANIOSE_TEGUMENTAR_TEMPLATE: SinanFormTemplate = {
  id: "sinan_leishmaniose_tegumentar",
  nome: "Leishmaniose Tegumentar Americana",
  agravoCode: "B55.1",
  cid10: "B55.1",
  categoria: "endemicas",
  versaoFicha: "LTA_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...LEISHMANIOSE_TEGUMENTAR_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "lt_tipo_entrada",
  ],
};

export const MALARIA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_malaria",
  nome: "Malária",
  agravoCode: "B50",
  cid10: "B50",
  cid10Range: "B50-B54",
  categoria: "endemicas",
  versaoFicha: "MALARIA_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...MALARIA_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "mal_classificacao",
  ],
};

export const CHAGAS_AGUDO_TEMPLATE: SinanFormTemplate = {
  id: "sinan_chagas_agudo",
  nome: "Doença de Chagas Aguda",
  agravoCode: "B57",
  cid10: "B57",
  categoria: "endemicas",
  versaoFicha: "CHAGAS_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...CHAGAS_AGUDO_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};
