import { SinanFormTemplate, SinanField, SINAN_COMMON_FIELDS, SINAN_FORM_GROUPS } from "../template-types";

const HANSENIASE_SPECIFIC_FIELDS: SinanField[] = [
  {
    key: "hans_modo_entrada",
    label: "Modo de Entrada",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Caso novo" },
      { value: "2", label: "Transferência do mesmo município" },
      { value: "3", label: "Transferência de outro município (mesma UF)" },
      { value: "4", label: "Transferência de outro estado" },
      { value: "5", label: "Transferência de outro país" },
      { value: "6", label: "Recidiva" },
      { value: "7", label: "Outro reingresso" },
    ],
    order: 35,
    sinanCode: "MODO_ENTRA",
    width: "half",
  },
  {
    key: "hans_modo_deteccao",
    label: "Modo de Detecção",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Encaminhamento" },
      { value: "2", label: "Demanda espontânea" },
      { value: "3", label: "Exame de coletividade" },
      { value: "4", label: "Exame de contatos" },
      { value: "5", label: "Outros modos" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "MODO_DETEC",
    width: "half",
  },
  {
    key: "hans_classificacao_operacional",
    label: "Classificação Operacional",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Paucibacilar (PB)" },
      { value: "2", label: "Multibacilar (MB)" },
    ],
    order: 37,
    sinanCode: "CLASS_OPER",
    width: "half",
  },
  {
    key: "hans_forma_clinica",
    label: "Forma Clínica",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Indeterminada" },
      { value: "2", label: "Tuberculóide" },
      { value: "3", label: "Dimorfa" },
      { value: "4", label: "Virchowiana" },
      { value: "5", label: "Não classificada" },
    ],
    order: 38,
    sinanCode: "FORM_CLIN",
    width: "half",
  },
  {
    key: "hans_baciloscopia",
    label: "Baciloscopia",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positiva" },
      { value: "2", label: "Negativa" },
      { value: "3", label: "Não realizada" },
    ],
    order: 50,
    sinanCode: "BACILOSCP",
    width: "quarter",
  },
  {
    key: "hans_num_lesoes",
    label: "Número de Lesões Cutâneas",
    type: "number",
    required: false,
    group: "clinicos",
    order: 39,
    sinanCode: "NUM_LESOES",
    validation: { min: 0, max: 99 },
    width: "quarter",
  },
  {
    key: "hans_num_nervos",
    label: "Número de Nervos Afetados",
    type: "number",
    required: false,
    group: "clinicos",
    order: 40,
    sinanCode: "NUM_NERVO",
    validation: { min: 0, max: 99 },
    width: "quarter",
  },
  {
    key: "hans_grau_incapacidade_diag",
    label: "Grau de Incapacidade Física no Diagnóstico",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "0", label: "Grau 0" },
      { value: "1", label: "Grau I" },
      { value: "2", label: "Grau II" },
      { value: "9", label: "Não avaliado" },
    ],
    order: 41,
    sinanCode: "GRAU_IF_I",
    width: "quarter",
  },
  {
    key: "hans_olho_direito",
    label: "Olho Direito",
    type: "select",
    required: false,
    group: "clinicos",
    subgroup: "Avaliação Simplificada das Funções Neurais e Complicações",
    options: [
      { value: "0", label: "Normal" },
      { value: "1", label: "Diminuição da sensibilidade" },
      { value: "2", label: "Lagoftalmo e/ou triquíase e/ou ectrópio e/ou opacidade corneana" },
      { value: "9", label: "Não avaliado" },
    ],
    order: 42,
    sinanCode: "OLHO_DIR",
    width: "quarter",
  },
  {
    key: "hans_olho_esquerdo",
    label: "Olho Esquerdo",
    type: "select",
    required: false,
    group: "clinicos",
    subgroup: "Avaliação Simplificada das Funções Neurais e Complicações",
    options: [
      { value: "0", label: "Normal" },
      { value: "1", label: "Diminuição da sensibilidade" },
      { value: "2", label: "Lagoftalmo e/ou triquíase e/ou ectrópio e/ou opacidade corneana" },
      { value: "9", label: "Não avaliado" },
    ],
    order: 43,
    sinanCode: "OLHO_ESQ",
    width: "quarter",
  },
  {
    key: "hans_mao_direita",
    label: "Mão Direita",
    type: "select",
    required: false,
    group: "clinicos",
    subgroup: "Avaliação Simplificada das Funções Neurais e Complicações",
    options: [
      { value: "0", label: "Normal" },
      { value: "1", label: "Diminuição da sensibilidade e/ou diminuição da força muscular" },
      { value: "2", label: "Mão em garra e/ou reabsorção e/ou ferida" },
      { value: "9", label: "Não avaliado" },
    ],
    order: 44,
    sinanCode: "MAO_DIR",
    width: "quarter",
  },
  {
    key: "hans_mao_esquerda",
    label: "Mão Esquerda",
    type: "select",
    required: false,
    group: "clinicos",
    subgroup: "Avaliação Simplificada das Funções Neurais e Complicações",
    options: [
      { value: "0", label: "Normal" },
      { value: "1", label: "Diminuição da sensibilidade e/ou diminuição da força muscular" },
      { value: "2", label: "Mão em garra e/ou reabsorção e/ou ferida" },
      { value: "9", label: "Não avaliado" },
    ],
    order: 45,
    sinanCode: "MAO_ESQ",
    width: "quarter",
  },
  {
    key: "hans_pe_direito",
    label: "Pé Direito",
    type: "select",
    required: false,
    group: "clinicos",
    subgroup: "Avaliação Simplificada das Funções Neurais e Complicações",
    options: [
      { value: "0", label: "Normal" },
      { value: "1", label: "Diminuição da sensibilidade e/ou diminuição da força muscular" },
      { value: "2", label: "Pé caído e/ou mal perfurante plantar e/ou contratura e/ou reabsorção" },
      { value: "9", label: "Não avaliado" },
    ],
    order: 46,
    sinanCode: "PE_DIR",
    width: "quarter",
  },
  {
    key: "hans_pe_esquerdo",
    label: "Pé Esquerdo",
    type: "select",
    required: false,
    group: "clinicos",
    subgroup: "Avaliação Simplificada das Funções Neurais e Complicações",
    options: [
      { value: "0", label: "Normal" },
      { value: "1", label: "Diminuição da sensibilidade e/ou diminuição da força muscular" },
      { value: "2", label: "Pé caído e/ou mal perfurante plantar e/ou contratura e/ou reabsorção" },
      { value: "9", label: "Não avaliado" },
    ],
    order: 47,
    sinanCode: "PE_ESQ",
    width: "quarter",
  },
  {
    key: "hans_esquema_terapeutico",
    label: "Esquema Terapêutico Inicial",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "PQT/PB 6 doses" },
      { value: "2", label: "PQT/MB 12 doses" },
      { value: "3", label: "Outros esquemas substitutivos" },
    ],
    order: 60,
    sinanCode: "ESQ_INI_N",
    width: "half",
  },
  {
    key: "hans_dt_inicio_tratamento",
    label: "Data de Início do Tratamento",
    type: "date",
    required: false,
    group: "tratamento",
    order: 61,
    sinanCode: "DT_INI_TRT",
    width: "third",
  },
  {
    key: "hans_contatos_registrados",
    label: "Número de Contatos Registrados",
    type: "number",
    required: false,
    group: "antecedentes",
    order: 34,
    sinanCode: "CONT_REGIS",
    validation: { min: 0, max: 99 },
    width: "quarter",
  },
  {
    key: "hans_contatos_examinados",
    label: "Contatos Examinados",
    type: "number",
    required: false,
    group: "antecedentes",
    order: 35,
    sinanCode: "CONT_EXAM",
    validation: { min: 0, max: 99 },
    width: "quarter",
  },
  {
    key: "hans_grau_incapacidade_alta",
    label: "Grau de Incapacidade Física na Alta",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "0", label: "Grau 0" },
      { value: "1", label: "Grau I" },
      { value: "2", label: "Grau II" },
      { value: "9", label: "Não avaliado" },
    ],
    order: 100,
    sinanCode: "GRAU_IF_A",
    width: "quarter",
  },
  {
    key: "hans_tipo_saida",
    label: "Tipo de Saída",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Cura" },
      { value: "2", label: "Transferência para o mesmo município" },
      { value: "3", label: "Transferência para outro município" },
      { value: "4", label: "Transferência para outro estado" },
      { value: "5", label: "Transferência para outro país" },
      { value: "6", label: "Óbito" },
      { value: "7", label: "Abandono" },
      { value: "8", label: "Erro diagnóstico" },
    ],
    order: 101,
    sinanCode: "TIPO_SAIDA",
    width: "half",
  },
  {
    key: "hans_dt_alta",
    label: "Data de Saída",
    type: "date",
    required: false,
    group: "conclusao",
    order: 102,
    sinanCode: "DT_ALTA_N",
    width: "third",
  },
];

export const HANSENIASE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_hanseniase",
  nome: "Hanseníase",
  agravoCode: "A30",
  cid10: "A30",
  categoria: "cronicas",
  versaoFicha: "HANSEN_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...HANSENIASE_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "hans_modo_entrada",
    "hans_classificacao_operacional",
    "hans_forma_clinica",
  ],
};
