import { SinanFormTemplate, SinanField, SINAN_COMMON_FIELDS, SINAN_FORM_GROUPS } from "../template-types";

const HEPATITES_SPECIFIC_FIELDS: SinanField[] = [
  {
    key: "hep_classificacao_etiologica",
    label: "Classificação Etiológica",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Vírus A" },
      { value: "2", label: "Vírus B" },
      { value: "3", label: "Vírus C" },
      { value: "4", label: "Vírus B+D" },
      { value: "5", label: "Vírus E" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "CLAS_ETIOL",
    width: "half",
  },
  {
    key: "hep_forma_clinica",
    label: "Forma Clínica",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Hepatite aguda" },
      { value: "2", label: "Hepatite crônica/Portador assintomático" },
      { value: "3", label: "Hepatite fulminante" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "FORM_CLIN",
    width: "half",
  },
  {
    key: "hep_ictericia",
    label: "Icterícia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "ICTERICIA",
    width: "quarter",
  },
  {
    key: "hep_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "hep_mal_estar",
    label: "Mal-estar",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "MAL_ESTAR",
    width: "quarter",
  },
  {
    key: "hep_nausea",
    label: "Náuseas/Vômitos",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "NAUSEA",
    width: "quarter",
  },
  {
    key: "hep_dor_abdominal",
    label: "Dor Abdominal",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 41,
    sinanCode: "DOR_ABDOM",
    width: "quarter",
  },
  {
    key: "hep_coluria",
    label: "Colúria",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 42,
    sinanCode: "COLURIA",
    width: "quarter",
  },
  {
    key: "hep_acolia",
    label: "Acolia Fecal",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 43,
    sinanCode: "ACOLIA",
    width: "quarter",
  },
  {
    key: "hep_anti_hav_igm",
    label: "Anti-HAV IgM",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Não realizado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 50,
    sinanCode: "HAV_IGM",
    width: "quarter",
  },
  {
    key: "hep_hbsag",
    label: "HBsAg",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Não realizado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 51,
    sinanCode: "HBSAG",
    width: "quarter",
  },
  {
    key: "hep_anti_hbc_igm",
    label: "Anti-HBc IgM",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Não realizado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 52,
    sinanCode: "HBC_IGM",
    width: "quarter",
  },
  {
    key: "hep_anti_hbc_total",
    label: "Anti-HBc Total",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Não realizado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 53,
    sinanCode: "HBC_TOTAL",
    width: "quarter",
  },
  {
    key: "hep_hbeag",
    label: "HBeAg",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Não realizado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 54,
    sinanCode: "HBEAG",
    width: "quarter",
  },
  {
    key: "hep_anti_hbe",
    label: "Anti-HBe",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Não realizado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 55,
    sinanCode: "ANTI_HBE",
    width: "quarter",
  },
  {
    key: "hep_anti_hcv",
    label: "Anti-HCV",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Não realizado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 56,
    sinanCode: "ANTI_HCV",
    width: "quarter",
  },
  {
    key: "hep_hcv_rna",
    label: "HCV-RNA",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Detectável" },
      { value: "2", label: "Não detectável" },
      { value: "3", label: "Não realizado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 57,
    sinanCode: "HCV_RNA",
    width: "quarter",
  },
  {
    key: "hep_anti_hdv",
    label: "Anti-HDV Total",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Não realizado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 58,
    sinanCode: "ANTI_HDV",
    width: "quarter",
  },
  {
    key: "hep_anti_hev",
    label: "Anti-HEV IgM",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Não realizado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 59,
    sinanCode: "HEV_IGM",
    width: "quarter",
  },
  {
    key: "hep_fonte_infeccao",
    label: "Provável Fonte/Mecanismo de Infecção",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sexual" },
      { value: "2", label: "Transfusional" },
      { value: "3", label: "Uso de drogas" },
      { value: "4", label: "Vertical" },
      { value: "5", label: "Acidente de trabalho" },
      { value: "6", label: "Hemodiálise" },
      { value: "7", label: "Domiciliar" },
      { value: "8", label: "Tratamento cirúrgico/dentário" },
      { value: "9", label: "Pessoa/pessoa" },
      { value: "10", label: "Alimento/água" },
      { value: "11", label: "Outros" },
      { value: "99", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "FONTE_INF",
    width: "half",
  },
  {
    key: "hep_vacinacao_hep_b",
    label: "Vacinação Hepatite B",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim, completa (3 doses ou mais)" },
      { value: "2", label: "Sim, incompleta" },
      { value: "3", label: "Não vacinado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "VACINA_HB",
    width: "half",
  },
  {
    key: "hep_vacinacao_hep_a",
    label: "Vacinação Hepatite A",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "VACINA_HA",
    width: "quarter",
  },
  {
    key: "hep_contato_sexual",
    label: "Contato Sexual com Pessoa Infectada",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "CONT_SEX",
    width: "quarter",
  },
  {
    key: "hep_contato_domiciliar",
    label: "Contato Domiciliar com Pessoa Infectada",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "CONT_DOM",
    width: "quarter",
  },
  {
    key: "hep_uso_drogas_injetaveis",
    label: "Uso de Drogas Injetáveis",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "DROGAS_INJ",
    width: "quarter",
  },
  {
    key: "hep_transfusao",
    label: "Transfusão de Sangue/Derivados",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "TRANSFUS",
    width: "quarter",
  },
  {
    key: "hep_hemodialise",
    label: "Hemodiálise",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 41,
    sinanCode: "HEMODIAL",
    width: "quarter",
  },
  {
    key: "hep_tatuagem_piercing",
    label: "Tatuagem/Piercing",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 42,
    sinanCode: "TATUAGEM",
    width: "quarter",
  },
  {
    key: "hep_profissional_saude",
    label: "Profissional de Saúde",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 43,
    sinanCode: "PROF_SAUD",
    width: "quarter",
  },
  {
    key: "hep_classificacao_final",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
      { value: "8", label: "Inconclusivo" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
];

export const HEPATITES_TEMPLATE: SinanFormTemplate = {
  id: "sinan_hepatites",
  nome: "Hepatites Virais",
  agravoCode: "B15",
  cid10: "B15",
  cid10Range: "B15-B19",
  categoria: "hepatites",
  versaoFicha: "HEPAT_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...HEPATITES_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "hep_classificacao_etiologica",
  ],
};
