import { SinanFormTemplate, SinanField, SINAN_COMMON_FIELDS, SINAN_FORM_GROUPS } from "../template-types";

const SARAMPO_SPECIFIC_FIELDS: SinanField[] = [
  {
    key: "sar_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "sar_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "sar_exantema",
    label: "Exantema",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "EXANTEMA",
    width: "quarter",
  },
  {
    key: "sar_tosse",
    label: "Tosse",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "TOSSE",
    width: "quarter",
  },
  {
    key: "sar_coriza",
    label: "Coriza",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "CORIZA",
    width: "quarter",
  },
  {
    key: "sar_conjuntivite",
    label: "Conjuntivite",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "CONJUNTVT",
    width: "quarter",
  },
  {
    key: "sar_linfadenopatia",
    label: "Linfadenopatia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "LINFADEN",
    width: "quarter",
  },
  {
    key: "sar_manchas_koplik",
    label: "Manchas de Koplik",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 41,
    sinanCode: "KOPLIK",
    width: "quarter",
  },
  {
    key: "sar_vacinacao_previa",
    label: "Vacinação Prévia contra Sarampo",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim (1 dose)" },
      { value: "2", label: "Sim (2 doses ou mais)" },
      { value: "3", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "VAC_SARAMPO",
    width: "half",
  },
  {
    key: "sar_igm_sarampo",
    label: "Sorologia IgM para Sarampo",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "IGM_SAR",
    width: "quarter",
  },
  {
    key: "sar_isolamento_viral",
    label: "Isolamento Viral",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positivo" },
      { value: "2", label: "Negativo" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 51,
    sinanCode: "ISOL_SAR",
    width: "quarter",
  },
  {
    key: "sar_rt_pcr",
    label: "RT-PCR",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Detectável" },
      { value: "2", label: "Não detectável" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 52,
    sinanCode: "RTPCR_SAR",
    width: "quarter",
  },
];

const COQUELUCHE_SPECIFIC_FIELDS: SinanField[] = [
  {
    key: "coq_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "coq_tosse",
    label: "Tosse",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim (paroxística)" },
      { value: "2", label: "Sim (não paroxística)" },
      { value: "3", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "TOSSE",
    width: "half",
  },
  {
    key: "coq_guincho",
    label: "Guincho Inspiratório",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "GUINCHO",
    width: "quarter",
  },
  {
    key: "coq_vomito_pos_tosse",
    label: "Vômitos Pós-acessos de Tosse",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "VOMITO_PT",
    width: "quarter",
  },
  {
    key: "coq_cianose",
    label: "Cianose",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "CIANOSE",
    width: "quarter",
  },
  {
    key: "coq_apneia",
    label: "Apneia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "APNEIA",
    width: "quarter",
  },
  {
    key: "coq_vacinacao",
    label: "Vacinação contra Coqueluche (DTP/DTaP/DTPa)",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Esquema completo (3+ doses)" },
      { value: "2", label: "Esquema incompleto" },
      { value: "3", label: "Não vacinado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "VAC_COQ",
    width: "half",
  },
  {
    key: "coq_cultura",
    label: "Cultura para Bordetella pertussis",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positiva" },
      { value: "2", label: "Negativa" },
      { value: "3", label: "Não realizada" },
    ],
    order: 50,
    sinanCode: "CULTURA",
    width: "quarter",
  },
  {
    key: "coq_pcr",
    label: "PCR",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Detectável" },
      { value: "2", label: "Não detectável" },
      { value: "3", label: "Não realizado" },
    ],
    order: 51,
    sinanCode: "PCR_COQ",
    width: "quarter",
  },
];

const TETANO_ACIDENTAL_FIELDS: SinanField[] = [
  {
    key: "tet_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado" },
      { value: "2", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "tet_tipo_ferimento",
    label: "Tipo de Ferimento/Porta de Entrada",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Perfurocortante" },
      { value: "2", label: "Laceração" },
      { value: "3", label: "Escoriação" },
      { value: "4", label: "Queimadura" },
      { value: "5", label: "Lesão de mucosa" },
      { value: "6", label: "Não identificado" },
      { value: "7", label: "Outro" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "TP_FERIM",
    width: "half",
  },
  {
    key: "tet_localizacao_ferimento",
    label: "Localização do Ferimento",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Cabeça/Pescoço" },
      { value: "2", label: "Membro superior" },
      { value: "3", label: "Mão/Dedo mão" },
      { value: "4", label: "Tronco" },
      { value: "5", label: "Membro inferior" },
      { value: "6", label: "Pé/Dedo pé" },
      { value: "7", label: "Múltipla" },
      { value: "8", label: "Não identificada" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "LOCAL_FER",
    width: "half",
  },
  {
    key: "tet_trismo",
    label: "Trismo",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "TRISMO",
    width: "quarter",
  },
  {
    key: "tet_riso_sardonico",
    label: "Riso Sardônico",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "RISO_SARD",
    width: "quarter",
  },
  {
    key: "tet_rigidez_nuca",
    label: "Rigidez de Nuca",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "RIG_NUCA",
    width: "quarter",
  },
  {
    key: "tet_opistotonos",
    label: "Opistótono",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "OPISTOT",
    width: "quarter",
  },
  {
    key: "tet_convulsoes",
    label: "Espasmos/Convulsões",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "CONVULS",
    width: "quarter",
  },
  {
    key: "tet_disfagia",
    label: "Disfagia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "DISFAGIA",
    width: "quarter",
  },
  {
    key: "tet_vacinacao",
    label: "Vacinação Prévia Antitetânica",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim (3+ doses)" },
      { value: "2", label: "Sim (1-2 doses)" },
      { value: "3", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "VAC_TET",
    width: "half",
  },
  {
    key: "tet_soro_antitetanico",
    label: "Recebeu Soro Antitetânico",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 60,
    sinanCode: "SORO_TET",
    width: "quarter",
  },
];

const PFA_POLIOMIELITE_FIELDS: SinanField[] = [
  {
    key: "pfa_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Poliomielite" },
      { value: "2", label: "PFA não polio (outra etiologia)" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "pfa_febre_inicio",
    label: "Febre no Início da Deficiência Motora",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "pfa_paralisia_flacida",
    label: "Paralisia Flácida Aguda",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 36,
    sinanCode: "PARAL_FL",
    width: "quarter",
  },
  {
    key: "pfa_assimetrica",
    label: "Paralisia Assimétrica",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "ASSIM",
    width: "quarter",
  },
  {
    key: "pfa_sensibilidade",
    label: "Alteração de Sensibilidade",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "SENSIBIL",
    width: "quarter",
  },
  {
    key: "pfa_instalacao_paralisia",
    label: "Instalação da Paralisia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Súbita (até 4 dias)" },
      { value: "2", label: "Gradual (mais de 4 dias)" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "INST_PARA",
    width: "half",
  },
  {
    key: "pfa_vacinacao_polio",
    label: "Vacinação contra Poliomielite",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Esquema completo (3+ doses)" },
      { value: "2", label: "Esquema incompleto" },
      { value: "3", label: "Não vacinado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "VAC_POLIO",
    width: "half",
  },
  {
    key: "pfa_coleta_fezes",
    label: "Coleta de Fezes (até 14 dias do início da deficiência)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Sim (oportuna)" },
      { value: "2", label: "Sim (inoportuna)" },
      { value: "3", label: "Não" },
    ],
    order: 50,
    sinanCode: "COL_FEZES",
    width: "half",
  },
  {
    key: "pfa_resultado_fezes",
    label: "Resultado da Cultura de Fezes",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Poliovírus selvagem" },
      { value: "2", label: "Poliovírus vacinal" },
      { value: "3", label: "Outro enterovírus" },
      { value: "4", label: "Negativo" },
      { value: "5", label: "Não realizado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 51,
    sinanCode: "RES_FEZES",
    dependsOn: { field: "pfa_coleta_fezes", value: ["1", "2"] },
    width: "half",
  },
  {
    key: "pfa_exame_revisao_60dias",
    label: "Exame de Revisão aos 60 dias",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Déficit motor presente" },
      { value: "2", label: "Sem sequela motora" },
      { value: "3", label: "Evolução para óbito" },
      { value: "4", label: "Não realizado" },
    ],
    order: 101,
    sinanCode: "REV_60D",
    width: "half",
  },
];

export const SARAMPO_TEMPLATE: SinanFormTemplate = {
  id: "sinan_sarampo",
  nome: "Sarampo",
  agravoCode: "B05",
  cid10: "B05",
  categoria: "imunoprevenivel",
  versaoFicha: "SARAMPO_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...SARAMPO_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const COQUELUCHE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_coqueluche",
  nome: "Coqueluche",
  agravoCode: "A37",
  cid10: "A37",
  categoria: "respiratorias",
  versaoFicha: "COQUEL_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...COQUELUCHE_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const TETANO_ACIDENTAL_TEMPLATE: SinanFormTemplate = {
  id: "sinan_tetano_acidental",
  nome: "Tétano Acidental",
  agravoCode: "A35",
  cid10: "A35",
  categoria: "imunoprevenivel",
  versaoFicha: "TETANO_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...TETANO_ACIDENTAL_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const PFA_POLIOMIELITE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_pfa_polio",
  nome: "Paralisia Flácida Aguda/Poliomielite",
  agravoCode: "A80",
  cid10: "A80",
  categoria: "imunoprevenivel",
  versaoFicha: "PFA_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...PFA_POLIOMIELITE_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};
