import { SinanFormTemplate, SinanField, SINAN_COMMON_FIELDS, SINAN_FORM_GROUPS } from "../template-types";

const INTOXICACAO_SPECIFIC_FIELDS: SinanField[] = [
  {
    key: "intox_tipo",
    label: "Tipo de Exposição/Intoxicação",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Aguda - única" },
      { value: "2", label: "Aguda - repetida" },
      { value: "3", label: "Crônica" },
      { value: "4", label: "Aguda sobre crônica" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "TIPO_EXPO",
    width: "half",
  },
  {
    key: "intox_agente_toxico",
    label: "Agente Tóxico",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Medicamento" },
      { value: "2", label: "Agrotóxico agrícola" },
      { value: "3", label: "Agrotóxico doméstico" },
      { value: "4", label: "Agrotóxico saúde pública" },
      { value: "5", label: "Raticida" },
      { value: "6", label: "Produto veterinário" },
      { value: "7", label: "Produto uso domiciliar" },
      { value: "8", label: "Cosmético" },
      { value: "9", label: "Produto químico industrial" },
      { value: "10", label: "Metal" },
      { value: "11", label: "Drogas de abuso" },
      { value: "12", label: "Planta tóxica" },
      { value: "13", label: "Alimento e bebida" },
      { value: "14", label: "Outro" },
      { value: "99", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "AG_TOXICO",
    width: "half",
  },
  {
    key: "intox_nome_agente",
    label: "Nome do Agente Tóxico",
    type: "text",
    required: false,
    group: "clinicos",
    order: 37,
    sinanCode: "NM_AGENTE",
    width: "full",
  },
  {
    key: "intox_circunstancia",
    label: "Circunstância",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Uso habitual" },
      { value: "2", label: "Acidental" },
      { value: "3", label: "Ambiental" },
      { value: "4", label: "Uso terapêutico" },
      { value: "5", label: "Prescrição médica inadequada" },
      { value: "6", label: "Erro de administração" },
      { value: "7", label: "Automedicação" },
      { value: "8", label: "Abuso" },
      { value: "9", label: "Ingestão de alimento" },
      { value: "10", label: "Tentativa de suicídio" },
      { value: "11", label: "Tentativa de aborto" },
      { value: "12", label: "Violência/homicídio" },
      { value: "13", label: "Outra" },
      { value: "99", label: "Ignorada" },
    ],
    order: 38,
    sinanCode: "CIRCUNST",
    width: "half",
  },
  {
    key: "intox_local_exposicao",
    label: "Local de Exposição",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Residência" },
      { value: "2", label: "Ambiente de trabalho" },
      { value: "3", label: "Trajeto do trabalho" },
      { value: "4", label: "Serviço de saúde" },
      { value: "5", label: "Escola/creche" },
      { value: "6", label: "Ambiente externo" },
      { value: "7", label: "Outro" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "LOCAL_EXP",
    width: "half",
  },
  {
    key: "intox_via_exposicao_digestiva",
    label: "Via - Digestiva",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 39,
    sinanCode: "VIA_DIGES",
    width: "quarter",
  },
  {
    key: "intox_via_exposicao_cutanea",
    label: "Via - Cutânea",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 40,
    sinanCode: "VIA_CUTAN",
    width: "quarter",
  },
  {
    key: "intox_via_exposicao_respiratoria",
    label: "Via - Respiratória",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 41,
    sinanCode: "VIA_RESP",
    width: "quarter",
  },
  {
    key: "intox_via_exposicao_ocular",
    label: "Via - Ocular",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 42,
    sinanCode: "VIA_OCUL",
    width: "quarter",
  },
  {
    key: "intox_via_exposicao_parenteral",
    label: "Via - Parenteral",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 43,
    sinanCode: "VIA_PAREN",
    width: "quarter",
  },
  {
    key: "intox_relacionada_trabalho",
    label: "Relacionada ao Trabalho",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "REL_TRAB",
    width: "quarter",
  },
  {
    key: "intox_cat",
    label: "Emitida CAT",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "3", label: "Não se aplica" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "CAT",
    dependsOn: { field: "intox_relacionada_trabalho", value: "1" },
    width: "quarter",
  },
  {
    key: "intox_tempo_exposicao",
    label: "Tempo Decorrido entre Exposição e Atendimento",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Até 1 hora" },
      { value: "2", label: "1 a 3 horas" },
      { value: "3", label: "3 a 6 horas" },
      { value: "4", label: "6 a 12 horas" },
      { value: "5", label: "12 a 24 horas" },
      { value: "6", label: "Mais de 24 horas" },
      { value: "9", label: "Ignorado" },
    ],
    order: 44,
    sinanCode: "TEMPO_EXP",
    width: "half",
  },
  {
    key: "intox_hospitalizacao",
    label: "Houve Hospitalização",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 45,
    sinanCode: "HOSPITAL",
    width: "quarter",
  },
  {
    key: "intox_classificacao_gravidade",
    label: "Classificação de Gravidade",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Leve" },
      { value: "2", label: "Moderado" },
      { value: "3", label: "Grave" },
      { value: "9", label: "Ignorado" },
    ],
    order: 100,
    sinanCode: "GRAVIDADE",
    width: "half",
  },
  {
    key: "intox_classificacao_final",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Intoxicação confirmada" },
      { value: "2", label: "Só exposição" },
      { value: "3", label: "Reação adversa" },
      { value: "4", label: "Outro diagnóstico" },
    ],
    order: 101,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "intox_evolucao",
    label: "Evolução do Caso",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Cura sem sequela" },
      { value: "2", label: "Cura com sequela" },
      { value: "3", label: "Óbito por intoxicação" },
      { value: "4", label: "Óbito por outra causa" },
      { value: "5", label: "Perda de seguimento" },
      { value: "9", label: "Ignorado" },
    ],
    order: 102,
    sinanCode: "EVOLUCAO",
    width: "half",
  },
];

export const INTOXICACAO_TEMPLATE: SinanFormTemplate = {
  id: "sinan_intoxicacao",
  nome: "Intoxicação Exógena",
  agravoCode: "T65.9",
  cid10: "T65.9",
  categoria: "intoxicacoes",
  versaoFicha: "INTEXOG_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...INTOXICACAO_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};
