import { SinanFormTemplate, SinanField, SINAN_COMMON_FIELDS, SINAN_FORM_GROUPS } from "../template-types";

const HIV_AIDS_FIELDS: SinanField[] = [
  {
    key: "hiv_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado HIV" },
      { value: "2", label: "Confirmado AIDS" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "hiv_criterio_definidor",
    label: "Critério Definidor de AIDS",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "CDC adaptado" },
      { value: "2", label: "Rio de Janeiro/Caracas" },
      { value: "3", label: "Óbito" },
      { value: "4", label: "Excepcional" },
      { value: "5", label: "Não se aplica (HIV)" },
    ],
    order: 35,
    sinanCode: "CRIT_DEF",
    width: "half",
  },
  {
    key: "hiv_cd4",
    label: "Contagem de CD4",
    type: "number",
    required: false,
    group: "laboratoriais",
    order: 50,
    sinanCode: "CD4",
    width: "quarter",
  },
  {
    key: "hiv_carga_viral",
    label: "Carga Viral (cópias/mL)",
    type: "number",
    required: false,
    group: "laboratoriais",
    order: 51,
    sinanCode: "CARGA_VIR",
    width: "quarter",
  },
  {
    key: "hiv_teste_rapido",
    label: "Teste Rápido HIV",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 52,
    sinanCode: "TR_HIV",
    width: "quarter",
  },
  {
    key: "hiv_elisa",
    label: "ELISA HIV",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 53,
    sinanCode: "ELISA_HIV",
    width: "quarter",
  },
  {
    key: "hiv_western_blot",
    label: "Western Blot",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Indeterminado" },
      { value: "4", label: "Não realizado" },
    ],
    order: 54,
    sinanCode: "WB",
    width: "quarter",
  },
  {
    key: "hiv_categoria_exposicao",
    label: "Categoria de Exposição",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sexual - HSH" },
      { value: "2", label: "Sexual - Heterossexual" },
      { value: "3", label: "UDI" },
      { value: "4", label: "Transfusão" },
      { value: "5", label: "Acidente biológico ocupacional" },
      { value: "6", label: "Transmissão vertical" },
      { value: "7", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "CAT_EXP",
    width: "half",
  },
  {
    key: "hiv_gestante",
    label: "Gestante",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "3", label: "Não se aplica" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "GESTANTE",
    width: "quarter",
  },
  {
    key: "hiv_tarv",
    label: "Em Uso de TARV",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 60,
    sinanCode: "TARV",
    width: "quarter",
  },
];

const SIFILIS_ADQUIRIDA_FIELDS: SinanField[] = [
  {
    key: "sfa_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado" },
      { value: "2", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "sfa_estagio",
    label: "Estágio Clínico",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sífilis primária" },
      { value: "2", label: "Sífilis secundária" },
      { value: "3", label: "Sífilis latente recente (< 1 ano)" },
      { value: "4", label: "Sífilis latente tardia (> 1 ano)" },
      { value: "5", label: "Sífilis terciária" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "ESTAGIO",
    width: "half",
  },
  {
    key: "sfa_cancro_duro",
    label: "Cancro Duro",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "CANCRO",
    width: "quarter",
  },
  {
    key: "sfa_roseola",
    label: "Roséola Sifilítica",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "ROSEOLA",
    width: "quarter",
  },
  {
    key: "sfa_condiloma_plano",
    label: "Condiloma Plano",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "CONDILOMA",
    width: "quarter",
  },
  {
    key: "sfa_alopecia",
    label: "Alopecia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "ALOPECIA",
    width: "quarter",
  },
  {
    key: "sfa_vdrl",
    label: "VDRL",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "VDRL",
    width: "quarter",
  },
  {
    key: "sfa_titulacao_vdrl",
    label: "Titulação VDRL",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "1:1" },
      { value: "2", label: "1:2" },
      { value: "3", label: "1:4" },
      { value: "4", label: "1:8" },
      { value: "5", label: "1:16" },
      { value: "6", label: "1:32" },
      { value: "7", label: "1:64" },
      { value: "8", label: "1:128 ou mais" },
    ],
    order: 51,
    sinanCode: "TIT_VDRL",
    dependsOn: { field: "sfa_vdrl", value: "1" },
    width: "quarter",
  },
  {
    key: "sfa_teste_treponemico",
    label: "Teste Treponêmico",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Não realizado" },
    ],
    order: 52,
    sinanCode: "TREP",
    width: "quarter",
  },
  {
    key: "sfa_tratamento",
    label: "Tratamento Realizado",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Penicilina G Benzatina" },
      { value: "2", label: "Outro esquema" },
      { value: "3", label: "Não tratado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 60,
    sinanCode: "TRATAM",
    width: "half",
  },
  {
    key: "sfa_parceiro_tratado",
    label: "Parceiro(s) Tratado(s)",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 61,
    sinanCode: "PARC_TRAT",
    width: "quarter",
  },
];

const GONORREIA_FIELDS: SinanField[] = [
  {
    key: "gon_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado" },
      { value: "2", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "gon_localizacao",
    label: "Localização da Infecção",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Uretral" },
      { value: "2", label: "Cervical" },
      { value: "3", label: "Retal" },
      { value: "4", label: "Faríngea" },
      { value: "5", label: "Conjuntival" },
      { value: "6", label: "Disseminada" },
      { value: "7", label: "Múltiplas" },
    ],
    order: 35,
    sinanCode: "LOCALIZ",
    width: "half",
  },
  {
    key: "gon_corrimento",
    label: "Corrimento",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "CORRIM",
    width: "quarter",
  },
  {
    key: "gon_disuria",
    label: "Disúria",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "DISURIA",
    width: "quarter",
  },
  {
    key: "gon_cultura",
    label: "Cultura",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positiva N. gonorrhoeae" },
      { value: "2", label: "Negativa" },
      { value: "3", label: "Não realizada" },
    ],
    order: 50,
    sinanCode: "CULTURA",
    width: "half",
  },
  {
    key: "gon_pcr",
    label: "PCR/NAAT",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Detectável" },
      { value: "2", label: "Não detectável" },
      { value: "3", label: "Não realizado" },
    ],
    order: 51,
    sinanCode: "PCR",
    width: "quarter",
  },
];

const HERPES_GENITAL_FIELDS: SinanField[] = [
  {
    key: "hrp_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado" },
      { value: "2", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "hrp_tipo",
    label: "Tipo de Episódio",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Primeiro episódio (primário)" },
      { value: "2", label: "Recorrência" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "TP_EPISOD",
    width: "half",
  },
  {
    key: "hrp_vesiculas",
    label: "Vesículas/Úlceras Genitais",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 36,
    sinanCode: "VESICULAS",
    width: "quarter",
  },
  {
    key: "hrp_dor_local",
    label: "Dor Local",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "DOR_LOC",
    width: "quarter",
  },
  {
    key: "hrp_adenopatia",
    label: "Adenopatia Inguinal",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "ADENOPAT",
    width: "quarter",
  },
  {
    key: "hrp_pcr",
    label: "PCR HSV",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "HSV-1 detectado" },
      { value: "2", label: "HSV-2 detectado" },
      { value: "3", label: "Não detectado" },
      { value: "4", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "PCR_HSV",
    width: "half",
  },
];

export const HIV_AIDS_TEMPLATE: SinanFormTemplate = {
  id: "sinan_hiv_aids",
  nome: "HIV/AIDS em Adulto",
  agravoCode: "B20",
  cid10: "B20",
  cid10Range: "B20-B24",
  categoria: "ist",
  versaoFicha: "HIV_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...HIV_AIDS_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const GESTANTE_HIV_TEMPLATE: SinanFormTemplate = {
  id: "sinan_gestante_hiv",
  nome: "Gestante HIV+",
  agravoCode: "Z21",
  cid10: "Z21",
  categoria: "ist",
  versaoFicha: "GESTHIV_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...HIV_AIDS_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const CRIANCA_EXPOSTA_HIV_TEMPLATE: SinanFormTemplate = {
  id: "sinan_crianca_exposta_hiv",
  nome: "Criança Exposta ao HIV",
  agravoCode: "Z20.6",
  cid10: "Z20.6",
  categoria: "ist",
  versaoFicha: "CRIAHIV_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const SIFILIS_ADQUIRIDA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_sifilis_adquirida",
  nome: "Sífilis Adquirida",
  agravoCode: "A51",
  cid10: "A51",
  cid10Range: "A51-A53",
  categoria: "ist",
  versaoFicha: "SIFADQ_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...SIFILIS_ADQUIRIDA_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const GONORREIA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_gonorreia",
  nome: "Gonorreia",
  agravoCode: "A54",
  cid10: "A54",
  categoria: "ist",
  versaoFicha: "GON_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: false,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...GONORREIA_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const HERPES_GENITAL_TEMPLATE: SinanFormTemplate = {
  id: "sinan_herpes_genital",
  nome: "Herpes Genital",
  agravoCode: "A60",
  cid10: "A60",
  categoria: "ist",
  versaoFicha: "HERP_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: false,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...HERPES_GENITAL_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "hrp_vesiculas",
  ],
};

export const HIV_CRIANCA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_hiv_crianca",
  nome: "HIV/AIDS em Criança",
  agravoCode: "B20.CR",
  cid10: "B20",
  categoria: "ist",
  versaoFicha: "HIVCR_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...HIV_AIDS_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const HIV_GESTANTE_PARTURIENTE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_hiv_gestante_parturiente",
  nome: "HIV em Gestante/Parturiente/Puérpera",
  agravoCode: "B20.GE",
  cid10: "B20",
  categoria: "ist",
  versaoFicha: "HIVGE_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...GESTANTE_HIV_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};
