import { SinanFormTemplate, SinanField, SINAN_COMMON_FIELDS, SINAN_FORM_GROUPS } from "../template-types";

const MENINGITE_SPECIFIC_FIELDS: SinanField[] = [
  {
    key: "meni_etiologia",
    label: "Etiologia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Meningocócica" },
      { value: "2", label: "Pneumocócica" },
      { value: "3", label: "Haemophilus" },
      { value: "4", label: "Tuberculosa" },
      { value: "5", label: "Viral" },
      { value: "6", label: "Outras bactérias" },
      { value: "7", label: "Não especificada" },
      { value: "8", label: "Outra etiologia" },
      { value: "9", label: "Ignorada" },
    ],
    order: 35,
    sinanCode: "ETIOLOGIA",
    width: "half",
  },
  {
    key: "meni_sorogrupo",
    label: "Sorogrupo (se meningocócica)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "A", label: "A" },
      { value: "B", label: "B" },
      { value: "C", label: "C" },
      { value: "W", label: "W" },
      { value: "Y", label: "Y" },
      { value: "X", label: "X" },
      { value: "Z", label: "Z" },
      { value: "29E", label: "29E" },
      { value: "NC", label: "Não capsulada" },
      { value: "NG", label: "Não grupável" },
      { value: "NR", label: "Não realizado" },
      { value: "IG", label: "Ignorado" },
    ],
    order: 50,
    sinanCode: "SOROGRUPO",
    dependsOn: { field: "meni_etiologia", value: "1" },
    width: "quarter",
  },
  {
    key: "meni_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "meni_cefaleia",
    label: "Cefaleia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "CEFALEIA",
    width: "quarter",
  },
  {
    key: "meni_vomito",
    label: "Vômitos",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "VOMITO",
    width: "quarter",
  },
  {
    key: "meni_rigidez_nuca",
    label: "Rigidez de Nuca",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "RIG_NUCA",
    width: "quarter",
  },
  {
    key: "meni_kernig_brudzinski",
    label: "Sinal de Kernig/Brudzinski",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "KERNIG",
    width: "quarter",
  },
  {
    key: "meni_abaulamento_fontanela",
    label: "Abaulamento de Fontanela",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "3", label: "Não se aplica" },
      { value: "9", label: "Ignorado" },
    ],
    order: 41,
    sinanCode: "FONTANELA",
    width: "quarter",
  },
  {
    key: "meni_convulsoes",
    label: "Convulsões",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 42,
    sinanCode: "CONVULS",
    width: "quarter",
  },
  {
    key: "meni_coma",
    label: "Coma",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 43,
    sinanCode: "COMA",
    width: "quarter",
  },
  {
    key: "meni_petequias",
    label: "Petéquias",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 44,
    sinanCode: "PETEQUIA",
    width: "quarter",
  },
  {
    key: "meni_sufusoes",
    label: "Sufusões Hemorrágicas",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 45,
    sinanCode: "SUFUSOES",
    width: "quarter",
  },
  {
    key: "meni_puncao_liquor",
    label: "Punção do Líquor",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Realizada" },
      { value: "2", label: "Não realizada" },
    ],
    order: 51,
    sinanCode: "PUNCAO_LQ",
    width: "quarter",
  },
  {
    key: "meni_aspecto_liquor",
    label: "Aspecto do Líquor",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Límpido" },
      { value: "2", label: "Turvo" },
      { value: "3", label: "Purulento" },
      { value: "4", label: "Xantocrômico" },
      { value: "5", label: "Hemorrágico" },
      { value: "9", label: "Ignorado" },
    ],
    order: 52,
    sinanCode: "ASP_LIQ",
    dependsOn: { field: "meni_puncao_liquor", value: "1" },
    width: "quarter",
  },
  {
    key: "meni_cultura_liquor",
    label: "Cultura de Líquor",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positiva" },
      { value: "2", label: "Negativa" },
      { value: "3", label: "Não realizada" },
      { value: "9", label: "Ignorado" },
    ],
    order: 53,
    sinanCode: "CULT_LIQ",
    width: "quarter",
  },
  {
    key: "meni_contraimunoeletroforese",
    label: "Contraimunoeletroforese (CIE)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positiva" },
      { value: "2", label: "Negativa" },
      { value: "3", label: "Não realizada" },
      { value: "9", label: "Ignorado" },
    ],
    order: 54,
    sinanCode: "CIE",
    width: "quarter",
  },
  {
    key: "meni_latex",
    label: "Aglutinação em Látex",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positiva" },
      { value: "2", label: "Negativa" },
      { value: "3", label: "Não realizada" },
      { value: "9", label: "Ignorado" },
    ],
    order: 55,
    sinanCode: "LATEX",
    width: "quarter",
  },
  {
    key: "meni_pcr",
    label: "PCR",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positiva" },
      { value: "2", label: "Negativa" },
      { value: "3", label: "Não realizada" },
      { value: "9", label: "Ignorado" },
    ],
    order: 56,
    sinanCode: "PCR",
    width: "quarter",
  },
  {
    key: "meni_quimioprofilaxia",
    label: "Quimioprofilaxia dos Contatos",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 60,
    sinanCode: "QUIMIO",
    width: "quarter",
  },
  {
    key: "meni_classificacao_final",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado" },
      { value: "2", label: "Descartado" },
      { value: "8", label: "Inconclusivo" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "meni_criterio_confirmacao",
    label: "Critério de Confirmação",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Cultura" },
      { value: "2", label: "CIE" },
      { value: "3", label: "Látex" },
      { value: "4", label: "Clínico" },
      { value: "5", label: "Quimiocitológico" },
      { value: "6", label: "Bacterioscopia" },
      { value: "7", label: "PCR" },
      { value: "8", label: "Outro" },
      { value: "9", label: "Ignorado" },
    ],
    order: 101,
    sinanCode: "CRIT_CONF",
    dependsOn: { field: "meni_classificacao_final", value: "1" },
    width: "half",
  },
  {
    key: "meni_evolucao",
    label: "Evolução",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Cura" },
      { value: "2", label: "Óbito pelo agravo notificado" },
      { value: "3", label: "Óbito por outra causa" },
      { value: "9", label: "Ignorado" },
    ],
    order: 102,
    sinanCode: "EVOLUCAO",
    width: "half",
  },
];

export const MENINGITE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_meningite",
  nome: "Meningite",
  agravoCode: "G00",
  cid10: "G00",
  cid10Range: "G00-G03, A17.0, A39",
  categoria: "meningites",
  versaoFicha: "MENING_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...MENINGITE_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const MENINGITE_TUBERCULOSA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_meningite_tuberculosa",
  nome: "Meningite Tuberculosa",
  agravoCode: "A17.0",
  cid10: "A17.0",
  categoria: "meningites",
  versaoFicha: "MENING_TB_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...MENINGITE_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const DOENCA_MENINGOCOCICA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_doenca_meningococica",
  nome: "Doença Meningocócica",
  agravoCode: "A39",
  cid10: "A39",
  categoria: "meningites",
  versaoFicha: "MENING_DMG_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...MENINGITE_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const MENINGITE_VIRAL_TEMPLATE: SinanFormTemplate = {
  id: "sinan_meningite_viral",
  nome: "Meningite Viral",
  agravoCode: "G02",
  cid10: "G02",
  cid10Range: "A87, G02",
  categoria: "meningites",
  versaoFicha: "MENING_VIR_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...MENINGITE_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const MENINGITE_OUTRAS_TEMPLATE: SinanFormTemplate = {
  id: "sinan_meningite_outras",
  nome: "Meningite de Outras Etiologias",
  agravoCode: "G03",
  cid10: "G03",
  categoria: "meningites",
  versaoFicha: "MENING_OUT_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...MENINGITE_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};
