import { SinanFormTemplate, SinanField, SINAN_COMMON_FIELDS, SINAN_FORM_GROUPS } from "../template-types";

const PESTE_FIELDS: SinanField[] = [
  {
    key: "pest_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "pest_forma_clinica",
    label: "Forma Clínica",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Bubônica" },
      { value: "2", label: "Septicêmica primária" },
      { value: "3", label: "Pneumônica primária" },
      { value: "4", label: "Pneumônica secundária" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "FORMA_CLI",
    width: "half",
  },
  {
    key: "pest_febre",
    label: "Febre",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "pest_bubao",
    label: "Bubão",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "BUBAO",
    width: "quarter",
  },
  {
    key: "pest_cultura",
    label: "Cultura (Yersinia pestis)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positiva" },
      { value: "2", label: "Negativa" },
      { value: "3", label: "Não realizada" },
    ],
    order: 50,
    sinanCode: "CULTURA",
    width: "quarter",
  },
];

const ANTRAZ_FIELDS: SinanField[] = [
  {
    key: "ant_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "ant_forma_clinica",
    label: "Forma Clínica",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Cutânea" },
      { value: "2", label: "Respiratória/Inalatória" },
      { value: "3", label: "Gastrointestinal" },
      { value: "4", label: "Meníngea" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "FORMA_CLI",
    width: "half",
  },
  {
    key: "ant_lesao_cutanea",
    label: "Lesão Cutânea (Escara Negra)",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "LES_CUT",
    width: "quarter",
  },
  {
    key: "ant_contato_animal",
    label: "Contato com Animais/Produtos de Origem Animal",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "CONT_ANIM",
    width: "half",
  },
  {
    key: "ant_cultura",
    label: "Cultura (Bacillus anthracis)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positiva" },
      { value: "2", label: "Negativa" },
      { value: "3", label: "Não realizada" },
    ],
    order: 50,
    sinanCode: "CULTURA",
    width: "quarter",
  },
];

const TETANO_NEONATAL_FIELDS: SinanField[] = [
  {
    key: "tnn_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado" },
      { value: "2", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "tnn_trismo",
    label: "Trismo",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 35,
    sinanCode: "TRISMO",
    width: "quarter",
  },
  {
    key: "tnn_contraturas",
    label: "Contraturas Musculares",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "CONTRATUR",
    width: "quarter",
  },
  {
    key: "tnn_dificuldade_mamar",
    label: "Dificuldade para Mamar",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "DIF_MAMAR",
    width: "quarter",
  },
  {
    key: "tnn_espasmos",
    label: "Espasmos/Crises",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "ESPASMOS",
    width: "quarter",
  },
  {
    key: "tnn_local_parto",
    label: "Local do Parto",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Domicílio" },
      { value: "2", label: "Hospital" },
      { value: "3", label: "Outro" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "LOC_PARTO",
    width: "half",
  },
  {
    key: "tnn_quem_fez_parto",
    label: "Quem Realizou o Parto",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Médico" },
      { value: "2", label: "Enfermeiro" },
      { value: "3", label: "Parteira" },
      { value: "4", label: "Outro" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "QUEM_PARTO",
    width: "half",
  },
  {
    key: "tnn_vacinacao_mae",
    label: "Vacinação Antitetânica da Mãe (Gestação)",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Vacinada (esquema completo)" },
      { value: "2", label: "Vacinação incompleta" },
      { value: "3", label: "Não vacinada" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "VAC_MAE",
    width: "half",
  },
];

const ROTAVIRUS_FIELDS: SinanField[] = [
  {
    key: "rot_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado" },
      { value: "2", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "rot_diarreia",
    label: "Diarreia",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 35,
    sinanCode: "DIARREIA",
    width: "quarter",
  },
  {
    key: "rot_vomito",
    label: "Vômito",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "VOMITO",
    width: "quarter",
  },
  {
    key: "rot_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "rot_desidratacao",
    label: "Desidratação",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sem desidratação" },
      { value: "2", label: "Leve" },
      { value: "3", label: "Moderada" },
      { value: "4", label: "Grave" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "DESIDRAT",
    width: "half",
  },
  {
    key: "rot_vacinacao",
    label: "Vacinação contra Rotavírus",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "1 dose" },
      { value: "2", label: "2 doses (completo)" },
      { value: "3", label: "Não vacinado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "VAC_ROTA",
    width: "half",
  },
  {
    key: "rot_teste_rapido",
    label: "Teste Rápido para Rotavírus",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positivo" },
      { value: "2", label: "Negativo" },
      { value: "3", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "TR_ROTA",
    width: "quarter",
  },
];

const FEBRE_MACULOSA_FIELDS: SinanField[] = [
  {
    key: "fmb_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "fmb_febre",
    label: "Febre",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 35,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "fmb_exantema",
    label: "Exantema",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "EXANTEMA",
    width: "quarter",
  },
  {
    key: "fmb_cefaleia",
    label: "Cefaleia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "CEFALEIA",
    width: "quarter",
  },
  {
    key: "fmb_mialgia",
    label: "Mialgia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "MIALGIA",
    width: "quarter",
  },
  {
    key: "fmb_escara",
    label: "Escara de Inoculação",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "ESCARA",
    width: "quarter",
  },
  {
    key: "fmb_contato_carrapato",
    label: "Contato com Carrapato/Capivara",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "CONT_CARR",
    width: "half",
  },
  {
    key: "fmb_sorologia",
    label: "Sorologia (IFI/ELISA)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "SOROL",
    width: "quarter",
  },
  {
    key: "fmb_pcr",
    label: "PCR",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Detectável" },
      { value: "2", label: "Não detectável" },
      { value: "3", label: "Não realizado" },
    ],
    order: 51,
    sinanCode: "PCR",
    width: "quarter",
  },
];

const TIFO_ENDEMICO_FIELDS: SinanField[] = [
  {
    key: "tif_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado" },
      { value: "2", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "tif_febre",
    label: "Febre",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 35,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "tif_cefaleia",
    label: "Cefaleia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "CEFALEIA",
    width: "quarter",
  },
  {
    key: "tif_exantema",
    label: "Exantema",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "EXANTEMA",
    width: "quarter",
  },
  {
    key: "tif_infestacao_pulga",
    label: "Infestação por Pulgas",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "INF_PULGA",
    width: "half",
  },
  {
    key: "tif_sorologia",
    label: "Sorologia (Weil-Felix/IFI)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "SOROL",
    width: "quarter",
  },
];

export const PESTE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_peste",
  nome: "Peste",
  agravoCode: "A20",
  cid10: "A20",
  categoria: "bacterianas",
  versaoFicha: "PESTE_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...PESTE_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "pest_febre",
  ],
};

export const ANTRAZ_TEMPLATE: SinanFormTemplate = {
  id: "sinan_antraz",
  nome: "Antraz/Carbúnculo",
  agravoCode: "A22",
  cid10: "A22",
  categoria: "bacterianas",
  versaoFicha: "ANTRAZ_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...ANTRAZ_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const BRUCELOSE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_brucelose",
  nome: "Brucelose",
  agravoCode: "A23",
  cid10: "A23",
  categoria: "zoonoses",
  versaoFicha: "BRUCE_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const TETANO_NEONATAL_TEMPLATE: SinanFormTemplate = {
  id: "sinan_tetano_neonatal",
  nome: "Tétano Neonatal",
  agravoCode: "A33",
  cid10: "A33",
  categoria: "imunoprevenivel",
  versaoFicha: "TETNEO_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...TETANO_NEONATAL_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "tnn_trismo",
  ],
};

export const ROTAVIRUS_TEMPLATE: SinanFormTemplate = {
  id: "sinan_rotavirus",
  nome: "Doença Diarreica por Rotavírus",
  agravoCode: "A08.0",
  cid10: "A08.0",
  categoria: "alimentares",
  versaoFicha: "ROTAV_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...ROTAVIRUS_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "rot_diarreia",
  ],
};

export const FEBRE_MACULOSA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_febre_maculosa",
  nome: "Febre Maculosa Brasileira e outras Rickettsioses",
  agravoCode: "A77",
  cid10: "A77",
  categoria: "rickettsias",
  versaoFicha: "FMB_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...FEBRE_MACULOSA_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "fmb_febre",
  ],
};

export const TIFO_ENDEMICO_TEMPLATE: SinanFormTemplate = {
  id: "sinan_tifo_endemico",
  nome: "Tifo Endêmico (Murino)",
  agravoCode: "A75.2",
  cid10: "A75.2",
  categoria: "rickettsias",
  versaoFicha: "TIFO_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...TIFO_ENDEMICO_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "tif_febre",
  ],
};

export const TRACOMA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_tracoma",
  nome: "Tracoma",
  agravoCode: "TRACOMA",
  cid10: "A71",
  categoria: "bacterianas",
  versaoFicha: "TRACOMA_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const FILARIOSE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_filariose",
  nome: "Filariose Linfática",
  agravoCode: "B74",
  cid10: "B74",
  categoria: "parasitarias",
  versaoFicha: "FILAR_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const ONCOCERCOSE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_oncocercose",
  nome: "Oncocercose",
  agravoCode: "B73",
  cid10: "B73",
  categoria: "parasitarias",
  versaoFicha: "ONCOCE_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const DEFICIENCIA_VIT_A_TEMPLATE: SinanFormTemplate = {
  id: "sinan_deficiencia_vit_a",
  nome: "Deficiência de Vitamina A",
  agravoCode: "E50",
  cid10: "E50",
  categoria: "nutricional",
  versaoFicha: "VITA_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: false,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const BERIBERI_TEMPLATE: SinanFormTemplate = {
  id: "sinan_beriberi",
  nome: "Beribéri",
  agravoCode: "E51.1",
  cid10: "E51.1",
  categoria: "nutricional",
  versaoFicha: "BERIB_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const ANOMALIA_CONGENITA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_anomalia_congenita",
  nome: "Anomalia Congênita/Defeitos Congênitos",
  agravoCode: "Q89.9",
  cid10: "Q89.9",
  cid10Range: "Q00-Q99",
  categoria: "congenitas",
  versaoFicha: "ANOMCONG_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const OBITO_MATERNO_TEMPLATE: SinanFormTemplate = {
  id: "sinan_obito_materno",
  nome: "Óbito Materno",
  agravoCode: "O95",
  cid10: "O95",
  cid10Range: "O00-O99",
  categoria: "materna",
  versaoFicha: "OBMAT_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const OBITO_INFANTIL_TEMPLATE: SinanFormTemplate = {
  id: "sinan_obito_infantil",
  nome: "Óbito Infantil e Fetal",
  agravoCode: "P96.9",
  cid10: "P96.9",
  cid10Range: "P00-P96",
  categoria: "infantil",
  versaoFicha: "OBINF_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

const TIFO_EPIDEMICO_FIELDS: SinanField[] = [
  {
    key: "tife_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "tife_febre",
    label: "Febre Alta",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "tife_exantema",
    label: "Exantema",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "EXANTEMA",
    width: "quarter",
  },
  {
    key: "tife_contato_piolho",
    label: "Contato com Piolho Corporal",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "PIOLHO",
    width: "half",
  },
  {
    key: "tife_sorologia",
    label: "Sorologia (Weil-Felix/ELISA)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "SOROL",
    width: "quarter",
  },
];

const GEOHELMINTÍASES_FIELDS: SinanField[] = [
  {
    key: "geo_tipo_parasita",
    label: "Tipo de Parasita",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Ascaris lumbricoides" },
      { value: "2", label: "Trichuris trichiura" },
      { value: "3", label: "Ancilostomídeos" },
      { value: "4", label: "Strongyloides stercoralis" },
      { value: "5", label: "Múltiplos" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "TP_PARAS",
    width: "half",
  },
  {
    key: "geo_epp",
    label: "Exame Parasitológico de Fezes",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positivo" },
      { value: "2", label: "Negativo" },
      { value: "3", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "EPF",
    width: "quarter",
  },
  {
    key: "geo_tratamento",
    label: "Tratamento Realizado",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 60,
    sinanCode: "TRATAM",
    width: "quarter",
  },
];

const INTERVENCAO_LEGAL_FIELDS: SinanField[] = [
  {
    key: "il_tipo",
    label: "Tipo de Intervenção",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Arma de fogo" },
      { value: "2", label: "Explosivos" },
      { value: "3", label: "Gás" },
      { value: "4", label: "Objeto contundente" },
      { value: "5", label: "Objetos cortantes" },
      { value: "9", label: "Não especificado" },
    ],
    order: 35,
    sinanCode: "TP_INTERV",
    width: "half",
  },
  {
    key: "il_lesao",
    label: "Tipo de Lesão",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Ferimento por arma de fogo" },
      { value: "2", label: "Traumatismo contuso" },
      { value: "3", label: "Lesão por explosão" },
      { value: "4", label: "Asfixia" },
      { value: "5", label: "Queimadura" },
      { value: "9", label: "Outra" },
    ],
    order: 36,
    sinanCode: "TP_LESAO",
    width: "half",
  },
  {
    key: "il_agente",
    label: "Agente da Intervenção",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Polícia Militar" },
      { value: "2", label: "Polícia Civil" },
      { value: "3", label: "Polícia Federal" },
      { value: "4", label: "Guarda Municipal" },
      { value: "5", label: "Forças Armadas" },
      { value: "9", label: "Não especificado" },
    ],
    order: 34,
    sinanCode: "AGENTE",
    width: "half",
  },
];

const PORTADOR_DOENCA_FIELDS: SinanField[] = [
  {
    key: "port_agravo",
    label: "Agravo do Portador",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Hepatite B" },
      { value: "2", label: "Hepatite C" },
      { value: "3", label: "HIV" },
      { value: "4", label: "HTLV" },
      { value: "5", label: "Doença de Chagas" },
      { value: "9", label: "Outro" },
    ],
    order: 35,
    sinanCode: "AGRAVO",
    width: "half",
  },
  {
    key: "port_sintomatico",
    label: "Sintomático",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 36,
    sinanCode: "SINTOM",
    width: "quarter",
  },
  {
    key: "port_acompanhamento",
    label: "Em Acompanhamento",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 37,
    sinanCode: "ACOMPAN",
    width: "quarter",
  },
];

const SURTO_DTA_FIELDS: SinanField[] = [
  {
    key: "surto_agente",
    label: "Agente Etiológico Identificado",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Salmonella" },
      { value: "2", label: "E. coli" },
      { value: "3", label: "Staphylococcus aureus" },
      { value: "4", label: "Rotavírus" },
      { value: "5", label: "Norovírus" },
      { value: "6", label: "Hepatite A" },
      { value: "7", label: "Clostridium" },
      { value: "8", label: "Não identificado" },
      { value: "9", label: "Outro" },
    ],
    order: 35,
    sinanCode: "AGENTE",
    width: "half",
  },
  {
    key: "surto_fonte",
    label: "Fonte Provável",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Restaurante" },
      { value: "2", label: "Residência" },
      { value: "3", label: "Escola/Creche" },
      { value: "4", label: "Festa/Evento" },
      { value: "5", label: "Água" },
      { value: "9", label: "Não identificada" },
    ],
    order: 34,
    sinanCode: "FONTE",
    width: "half",
  },
  {
    key: "surto_num_expostos",
    label: "Número de Expostos",
    type: "number",
    required: false,
    group: "antecedentes",
    order: 35,
    sinanCode: "NUM_EXP",
    width: "quarter",
  },
  {
    key: "surto_num_doentes",
    label: "Número de Doentes",
    type: "number",
    required: false,
    group: "antecedentes",
    order: 36,
    sinanCode: "NUM_DOEN",
    width: "quarter",
  },
];

const ONCOBIOLOGICO_FIELDS: SinanField[] = [
  {
    key: "onco_tipo",
    label: "Tipo de Evento Adverso",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Reação local" },
      { value: "2", label: "Reação sistêmica leve" },
      { value: "3", label: "Reação sistêmica grave" },
      { value: "4", label: "Anafilaxia" },
      { value: "9", label: "Outro" },
    ],
    order: 35,
    sinanCode: "TP_EVENTO",
    width: "half",
  },
  {
    key: "onco_medicamento",
    label: "Medicamento Oncobiológico",
    type: "text",
    required: false,
    group: "antecedentes",
    order: 34,
    sinanCode: "MEDICAM",
    width: "full",
  },
  {
    key: "onco_gravidade",
    label: "Gravidade",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Leve" },
      { value: "2", label: "Moderada" },
      { value: "3", label: "Grave" },
      { value: "4", label: "Fatal" },
    ],
    order: 36,
    sinanCode: "GRAVIDADE",
    width: "quarter",
  },
];

export const TIFO_EPIDEMICO_TEMPLATE: SinanFormTemplate = {
  id: "sinan_tifo_epidemico",
  nome: "Tifo Epidêmico (Tifo Exantemático)",
  agravoCode: "A75",
  cid10: "A75",
  categoria: "zoonoses",
  versaoFicha: "TIFOEPI_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...TIFO_EPIDEMICO_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const GEOHELMINTÍASES_TEMPLATE: SinanFormTemplate = {
  id: "sinan_geohelmintíases",
  nome: "Geo-helmintíases",
  agravoCode: "B83.2",
  cid10: "B83.2",
  categoria: "parasitarias",
  versaoFicha: "GEOHELM_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...GEOHELMINTÍASES_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const INTERVENCAO_LEGAL_TEMPLATE: SinanFormTemplate = {
  id: "sinan_intervencao_legal",
  nome: "Intervenção Legal",
  agravoCode: "Y35",
  cid10: "Y35",
  categoria: "violencia",
  versaoFicha: "INTLEG_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...INTERVENCAO_LEGAL_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const PORTADOR_DOENCA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_portador_doenca",
  nome: "Portador de Doença Infecciosa",
  agravoCode: "Z22",
  cid10: "Z22",
  categoria: "infecciosas",
  versaoFicha: "PORTAD_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...PORTADOR_DOENCA_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "port_agravo",
  ],
};

export const SURTO_DTA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_surto_dta",
  nome: "Surto de Doença Transmitida por Alimentos",
  agravoCode: "SURTO",
  cid10: "A05.9",
  categoria: "alimentares",
  versaoFicha: "SURTO_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...SURTO_DTA_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const ONCOBIOLOGICO_TEMPLATE: SinanFormTemplate = {
  id: "sinan_oncobiologico",
  nome: "Evento Adverso a Oncobiológico",
  agravoCode: "ONCO",
  cid10: "Y43.4",
  categoria: "farmacovigilancia",
  versaoFicha: "ONCO_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...ONCOBIOLOGICO_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const CONTATO_DOENCA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_contato_doenca",
  nome: "Contato com Doença Transmissível",
  agravoCode: "Z20.9",
  cid10: "Z20.9",
  categoria: "vigilancia",
  versaoFicha: "CONTATO_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: false,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};
