import { SinanFormTemplate, SinanField, SINAN_COMMON_FIELDS, SINAN_FORM_GROUPS } from "../template-types";

const ESQUISTOSSOMOSE_FIELDS: SinanField[] = [
  {
    key: "esq_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "esq_forma_clinica",
    label: "Forma Clínica",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Intestinal" },
      { value: "2", label: "Hepatointestinal" },
      { value: "3", label: "Hepatoesplênica compensada" },
      { value: "4", label: "Hepatoesplênica descompensada" },
      { value: "5", label: "Outras formas" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "FORMA_CLI",
    width: "half",
  },
  {
    key: "esq_diarreia",
    label: "Diarreia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "DIARREIA",
    width: "quarter",
  },
  {
    key: "esq_hepatomegalia",
    label: "Hepatomegalia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "HEPATOMEG",
    width: "quarter",
  },
  {
    key: "esq_esplenomegalia",
    label: "Esplenomegalia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "ESPLENOM",
    width: "quarter",
  },
  {
    key: "esq_ascite",
    label: "Ascite",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "ASCITE",
    width: "quarter",
  },
  {
    key: "esq_contato_colecao",
    label: "Contato com Coleção Hídrica",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "CONT_AGUA",
    width: "half",
  },
  {
    key: "esq_pef",
    label: "Parasitológico de Fezes (Kato-Katz)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positivo" },
      { value: "2", label: "Negativo" },
      { value: "3", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "PEF",
    width: "quarter",
  },
  {
    key: "esq_carga_parasitaria",
    label: "Carga Parasitária (ovos/g fezes)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Leve (< 100)" },
      { value: "2", label: "Moderada (100-399)" },
      { value: "3", label: "Alta (>= 400)" },
    ],
    order: 51,
    sinanCode: "CARGA_PAR",
    dependsOn: { field: "esq_pef", value: "1" },
    width: "quarter",
  },
  {
    key: "esq_tratamento",
    label: "Tratamento",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Praziquantel" },
      { value: "2", label: "Oxamniquina" },
      { value: "3", label: "Não tratado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 60,
    sinanCode: "TRATAM",
    width: "half",
  },
];

const CISTICERCOSE_FIELDS: SinanField[] = [
  {
    key: "cis_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado" },
      { value: "2", label: "Provável" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "cis_localizacao",
    label: "Localização",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Neurocisticercose" },
      { value: "2", label: "Ocular" },
      { value: "3", label: "Muscular/Subcutânea" },
      { value: "4", label: "Cardíaca" },
      { value: "5", label: "Múltipla" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "LOCALIZ",
    width: "half",
  },
  {
    key: "cis_convulsao",
    label: "Convulsão/Epilepsia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "CONVULS",
    width: "quarter",
  },
  {
    key: "cis_cefaleia",
    label: "Cefaleia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "CEFALEIA",
    width: "quarter",
  },
  {
    key: "cis_hipertensao_ic",
    label: "Hipertensão Intracraniana",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "HIC",
    width: "quarter",
  },
  {
    key: "cis_imagem",
    label: "Exame de Imagem (TC/RNM)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Lesões compatíveis" },
      { value: "2", label: "Normal" },
      { value: "3", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "IMAGEM",
    width: "half",
  },
  {
    key: "cis_sorologia",
    label: "Sorologia (ELISA/Western Blot)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 51,
    sinanCode: "SOROL",
    width: "quarter",
  },
];

const TENIASE_FIELDS: SinanField[] = [
  {
    key: "ten_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado" },
      { value: "2", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "ten_especie",
    label: "Espécie",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Taenia solium" },
      { value: "2", label: "Taenia saginata" },
      { value: "3", label: "Não identificada" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "ESPECIE",
    width: "half",
  },
  {
    key: "ten_dor_abdominal",
    label: "Dor Abdominal",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "DOR_ABD",
    width: "quarter",
  },
  {
    key: "ten_proglotes",
    label: "Eliminação de Proglotes",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "PROGLOTES",
    width: "quarter",
  },
  {
    key: "ten_pef",
    label: "Parasitológico de Fezes",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Ovos de Taenia" },
      { value: "2", label: "Proglotes identificados" },
      { value: "3", label: "Negativo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "PEF",
    width: "half",
  },
];

const TOXOPLASMOSE_FIELDS: SinanField[] = [
  {
    key: "txp_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado" },
      { value: "2", label: "Provável" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "txp_forma",
    label: "Forma Clínica",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Adquirida (aguda)" },
      { value: "2", label: "Congênita" },
      { value: "3", label: "Ocular" },
      { value: "4", label: "Cerebral" },
      { value: "5", label: "Outra" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "FORMA",
    width: "half",
  },
  {
    key: "txp_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "txp_linfadenopatia",
    label: "Linfadenopatia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "LINFADEN",
    width: "quarter",
  },
  {
    key: "txp_coriorretinite",
    label: "Coriorretinite",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "CORIORETN",
    width: "quarter",
  },
  {
    key: "txp_gestante",
    label: "Gestante",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "3", label: "Não se aplica" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "GESTANTE",
    width: "quarter",
  },
  {
    key: "txp_igm",
    label: "IgM anti-Toxoplasma",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "IGM",
    width: "quarter",
  },
  {
    key: "txp_igg",
    label: "IgG anti-Toxoplasma",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 51,
    sinanCode: "IGG",
    width: "quarter",
  },
  {
    key: "txp_avidez_igg",
    label: "Avidez de IgG",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Baixa (< 30%)" },
      { value: "2", label: "Intermediária (30-60%)" },
      { value: "3", label: "Alta (> 60%)" },
      { value: "4", label: "Não realizado" },
    ],
    order: 52,
    sinanCode: "AVIDEZ",
    width: "quarter",
  },
];

export const ESQUISTOSSOMOSE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_esquistossomose",
  nome: "Esquistossomose",
  agravoCode: "B65",
  cid10: "B65",
  categoria: "parasitarias",
  versaoFicha: "ESQUIS_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...ESQUISTOSSOMOSE_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const CISTICERCOSE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_cisticercose",
  nome: "Cisticercose",
  agravoCode: "B69",
  cid10: "B69",
  categoria: "parasitarias",
  versaoFicha: "CISTIC_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...CISTICERCOSE_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const TENIASE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_teniase",
  nome: "Teníase",
  agravoCode: "B68",
  cid10: "B68",
  categoria: "parasitarias",
  versaoFicha: "TENIAS_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...TENIASE_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const TOXOPLASMOSE_GESTANTE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_toxoplasmose_gestante",
  nome: "Toxoplasmose Gestacional",
  agravoCode: "O98.6",
  cid10: "O98.6",
  categoria: "parasitarias",
  versaoFicha: "TOXOGEST_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...TOXOPLASMOSE_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const TOXOPLASMOSE_CONGENITA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_toxoplasmose_congenita",
  nome: "Toxoplasmose Congênita",
  agravoCode: "P37.1",
  cid10: "P37.1",
  categoria: "parasitarias",
  versaoFicha: "TOXOCONG_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...TOXOPLASMOSE_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};
