import { SinanFormTemplate, SinanField, SINAN_COMMON_FIELDS, SINAN_FORM_GROUPS } from "../template-types";

const DIFTERIA_SPECIFIC_FIELDS: SinanField[] = [
  {
    key: "dif_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "dif_pseudomembrana",
    label: "Pseudomembrana",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "PSEUDO",
    width: "quarter",
  },
  {
    key: "dif_localizacao_pseudo",
    label: "Localização da Pseudomembrana",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Amígdalas" },
      { value: "2", label: "Faringe" },
      { value: "3", label: "Laringe" },
      { value: "4", label: "Nasal" },
      { value: "5", label: "Cutânea" },
      { value: "6", label: "Outra" },
    ],
    order: 36,
    sinanCode: "LOC_PSEUDO",
    dependsOn: { field: "dif_pseudomembrana", value: "1" },
    width: "half",
  },
  {
    key: "dif_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "dif_dor_garganta",
    label: "Dor de Garganta",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "DOR_GARG",
    width: "quarter",
  },
  {
    key: "dif_rouquidao",
    label: "Rouquidão",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "ROUQUID",
    width: "quarter",
  },
  {
    key: "dif_estridor",
    label: "Estridor",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "ESTRIDOR",
    width: "quarter",
  },
  {
    key: "dif_vacinacao",
    label: "Vacinação contra Difteria (DTP/DTPa)",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Esquema completo (3+ doses)" },
      { value: "2", label: "Esquema incompleto" },
      { value: "3", label: "Não vacinado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "VAC_DIF",
    width: "half",
  },
  {
    key: "dif_cultura",
    label: "Cultura para Corynebacterium diphtheriae",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positiva" },
      { value: "2", label: "Negativa" },
      { value: "3", label: "Não realizada" },
    ],
    order: 50,
    sinanCode: "CULTURA",
    width: "quarter",
  },
  {
    key: "dif_soro_antidifterico",
    label: "Recebeu Soro Antidiftérico (SAD)",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 60,
    sinanCode: "SAD",
    width: "quarter",
  },
];

const INFLUENZA_SPECIFIC_FIELDS: SinanField[] = [
  {
    key: "inf_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Influenza A" },
      { value: "2", label: "Influenza B" },
      { value: "3", label: "Outro vírus respiratório" },
      { value: "4", label: "Etiologia não identificada" },
      { value: "5", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "inf_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "inf_tosse",
    label: "Tosse",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "TOSSE",
    width: "quarter",
  },
  {
    key: "inf_dor_garganta",
    label: "Dor de Garganta",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "DOR_GARG",
    width: "quarter",
  },
  {
    key: "inf_mialgia",
    label: "Mialgia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "MIALGIA",
    width: "quarter",
  },
  {
    key: "inf_dispneia",
    label: "Dispneia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "DISPNEIA",
    width: "quarter",
  },
  {
    key: "inf_saturacao",
    label: "Saturação O2 < 95%",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "SATURACAO",
    width: "quarter",
  },
  {
    key: "inf_internacao",
    label: "Internação",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 41,
    sinanCode: "INTERN",
    width: "quarter",
  },
  {
    key: "inf_uti",
    label: "UTI",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 42,
    sinanCode: "UTI",
    dependsOn: { field: "inf_internacao", value: "1" },
    width: "quarter",
  },
  {
    key: "inf_vacinacao",
    label: "Vacinação contra Influenza (ano corrente)",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "VAC_INF",
    width: "half",
  },
  {
    key: "inf_rt_pcr",
    label: "RT-PCR para Influenza",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positivo Influenza A" },
      { value: "2", label: "Positivo Influenza B" },
      { value: "3", label: "Negativo" },
      { value: "4", label: "Inconclusivo" },
      { value: "5", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "PCR_INF",
    width: "half",
  },
  {
    key: "inf_antiviral",
    label: "Uso de Antiviral (Oseltamivir)",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 60,
    sinanCode: "ANTIVIRAL",
    width: "quarter",
  },
];

const SRAG_SPECIFIC_FIELDS: SinanField[] = [
  {
    key: "srag_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "SRAG por Influenza" },
      { value: "2", label: "SRAG por outro vírus respiratório" },
      { value: "3", label: "SRAG por outro agente etiológico" },
      { value: "4", label: "SRAG não especificado" },
      { value: "5", label: "COVID-19" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "srag_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "srag_tosse",
    label: "Tosse",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "TOSSE",
    width: "quarter",
  },
  {
    key: "srag_dispneia",
    label: "Dispneia",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "DISPNEIA",
    width: "quarter",
  },
  {
    key: "srag_saturacao",
    label: "Saturação O2 < 95%",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "SATURACAO",
    width: "quarter",
  },
  {
    key: "srag_desconforto",
    label: "Desconforto Respiratório",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "DESC_RESP",
    width: "quarter",
  },
  {
    key: "srag_internacao",
    label: "Internação",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 40,
    sinanCode: "INTERN",
    width: "quarter",
  },
  {
    key: "srag_uti",
    label: "UTI",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 41,
    sinanCode: "UTI",
    width: "quarter",
  },
  {
    key: "srag_suporte_ventilatorio",
    label: "Suporte Ventilatório",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim, invasivo" },
      { value: "2", label: "Sim, não invasivo" },
      { value: "3", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 42,
    sinanCode: "SUPORTE",
    width: "quarter",
  },
  {
    key: "srag_raio_x",
    label: "Raio-X de Tórax",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Normal" },
      { value: "2", label: "Infiltrado intersticial" },
      { value: "3", label: "Consolidação" },
      { value: "4", label: "Misto" },
      { value: "5", label: "Outro" },
      { value: "6", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "RX_TORAX",
    width: "half",
  },
  {
    key: "srag_coleta_amostra",
    label: "Coleta de Amostra",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 51,
    sinanCode: "COL_AMOST",
    width: "quarter",
  },
  {
    key: "srag_resultado_pcr",
    label: "Resultado RT-PCR",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Influenza A" },
      { value: "2", label: "Influenza B" },
      { value: "3", label: "SARS-CoV-2" },
      { value: "4", label: "VSR" },
      { value: "5", label: "Outro vírus" },
      { value: "6", label: "Negativo" },
      { value: "7", label: "Inconclusivo" },
      { value: "8", label: "Aguardando" },
    ],
    order: 52,
    sinanCode: "RES_PCR",
    dependsOn: { field: "srag_coleta_amostra", value: "1" },
    width: "half",
  },
  {
    key: "srag_antiviral",
    label: "Uso de Antiviral",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 60,
    sinanCode: "ANTIVIRAL",
    width: "quarter",
  },
];

const COVID19_SPECIFIC_FIELDS: SinanField[] = [
  {
    key: "cov_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Confirmado clínico-imagem" },
      { value: "4", label: "Síndrome Gripal não especificada" },
      { value: "5", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "cov_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "cov_tosse",
    label: "Tosse",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "TOSSE",
    width: "quarter",
  },
  {
    key: "cov_dor_garganta",
    label: "Dor de Garganta",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "DOR_GARG",
    width: "quarter",
  },
  {
    key: "cov_dispneia",
    label: "Dispneia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "DISPNEIA",
    width: "quarter",
  },
  {
    key: "cov_anosmia",
    label: "Anosmia/Hiposmia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "ANOSMIA",
    width: "quarter",
  },
  {
    key: "cov_ageusia",
    label: "Ageusia/Disgeusia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "AGEUSIA",
    width: "quarter",
  },
  {
    key: "cov_saturacao",
    label: "Saturação O2 < 95%",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 41,
    sinanCode: "SATURACAO",
    width: "quarter",
  },
  {
    key: "cov_comorbidades",
    label: "Possui Comorbidades",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "COMORB",
    width: "quarter",
  },
  {
    key: "cov_vacinacao",
    label: "Vacinação COVID-19",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Não vacinado" },
      { value: "2", label: "1 dose" },
      { value: "3", label: "2 doses" },
      { value: "4", label: "3 doses (reforço)" },
      { value: "5", label: "4+ doses" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "VAC_COV",
    width: "half",
  },
  {
    key: "cov_rt_pcr",
    label: "RT-PCR SARS-CoV-2",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Detectável" },
      { value: "2", label: "Não detectável" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "PCR_COV",
    width: "quarter",
  },
  {
    key: "cov_teste_rapido",
    label: "Teste Rápido Antígeno",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 51,
    sinanCode: "TR_AG",
    width: "quarter",
  },
  {
    key: "cov_internacao",
    label: "Internação",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 42,
    sinanCode: "INTERN",
    width: "quarter",
  },
  {
    key: "cov_uti",
    label: "UTI",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 43,
    sinanCode: "UTI",
    width: "quarter",
  },
];

export const DIFTERIA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_difteria",
  nome: "Difteria",
  agravoCode: "A36",
  cid10: "A36",
  categoria: "respiratorias",
  versaoFicha: "DIFT_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...DIFTERIA_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const INFLUENZA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_influenza",
  nome: "Influenza por Vírus Identificado",
  agravoCode: "J10",
  cid10: "J10",
  categoria: "respiratorias",
  versaoFicha: "INFLZ_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...INFLUENZA_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const SRAG_TEMPLATE: SinanFormTemplate = {
  id: "sinan_srag",
  nome: "SRAG - Síndrome Respiratória Aguda Grave",
  agravoCode: "J80",
  cid10: "J80",
  categoria: "respiratorias",
  versaoFicha: "SRAG_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...SRAG_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "srag_dispneia",
    "srag_internacao",
  ],
};

export const COVID19_TEMPLATE: SinanFormTemplate = {
  id: "sinan_covid19",
  nome: "COVID-19",
  agravoCode: "U07.1",
  cid10: "U07.1",
  categoria: "respiratorias",
  versaoFicha: "COVID_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...COVID19_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const INFLUENZA_PANDEMICA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_influenza_pandemica",
  nome: "Influenza Pandêmica",
  agravoCode: "J09",
  cid10: "J09",
  categoria: "respiratorias",
  versaoFicha: "INFLZP_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...INFLUENZA_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};
