import { SinanFormTemplate, SinanField, SINAN_COMMON_FIELDS, SINAN_FORM_GROUPS } from "../template-types";

const SIFILIS_CONGENITA_FIELDS: SinanField[] = [
  {
    key: "sif_diag_final",
    label: "Diagnóstico Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Sífilis congênita recente" },
      { value: "2", label: "Sífilis congênita tardia" },
      { value: "3", label: "Aborto por sífilis" },
      { value: "4", label: "Natimorto por sífilis" },
      { value: "5", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "DIAG_FINAL",
    width: "half",
  },
  {
    key: "sif_idade_gestacional",
    label: "Idade Gestacional (semanas)",
    type: "number",
    required: false,
    group: "clinicos",
    order: 35,
    sinanCode: "IG",
    validation: { min: 1, max: 45 },
    width: "quarter",
  },
  {
    key: "sif_peso_nascer",
    label: "Peso ao Nascer (gramas)",
    type: "number",
    required: false,
    group: "clinicos",
    order: 36,
    sinanCode: "PESO_NASC",
    validation: { min: 100, max: 9999 },
    width: "quarter",
  },
  {
    key: "sif_sintomatico",
    label: "Criança Sintomática",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "SINTOMTIC",
    width: "quarter",
  },
  {
    key: "sif_ictericia",
    label: "Icterícia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "ICTERICIA",
    dependsOn: { field: "sif_sintomatico", value: "1" },
    width: "quarter",
  },
  {
    key: "sif_hepatoesplenomegalia",
    label: "Hepato/Esplenomegalia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "HEPATESPL",
    dependsOn: { field: "sif_sintomatico", value: "1" },
    width: "quarter",
  },
  {
    key: "sif_lesao_pele",
    label: "Lesão de Pele",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "LES_PELE",
    dependsOn: { field: "sif_sintomatico", value: "1" },
    width: "quarter",
  },
  {
    key: "sif_rinite_coriza",
    label: "Rinite/Coriza Serossanguinolenta",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 41,
    sinanCode: "RINITE",
    dependsOn: { field: "sif_sintomatico", value: "1" },
    width: "quarter",
  },
  {
    key: "sif_osteocondrite",
    label: "Osteocondrite",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 42,
    sinanCode: "OSTEOCOND",
    dependsOn: { field: "sif_sintomatico", value: "1" },
    width: "quarter",
  },
  {
    key: "sif_trat_mae_gestacao",
    label: "Tratamento da Mãe Durante Gestação",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Adequado" },
      { value: "2", label: "Inadequado" },
      { value: "3", label: "Não realizado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "TRAT_MAE",
    width: "half",
  },
  {
    key: "sif_trat_parceiro",
    label: "Tratamento do Parceiro",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "TRAT_PARC",
    width: "quarter",
  },
  {
    key: "sif_vdrl_sangue_periferico",
    label: "VDRL Sangue Periférico",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Não realizado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 50,
    sinanCode: "VDRL_SP",
    width: "quarter",
  },
  {
    key: "sif_titulacao_vdrl",
    label: "Titulação",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "1:1" },
      { value: "2", label: "1:2" },
      { value: "4", label: "1:4" },
      { value: "8", label: "1:8" },
      { value: "16", label: "1:16" },
      { value: "32", label: "1:32" },
      { value: "64", label: "1:64" },
      { value: "128", label: "1:128 ou mais" },
    ],
    order: 51,
    sinanCode: "TIT_VDRL",
    dependsOn: { field: "sif_vdrl_sangue_periferico", value: "1" },
    width: "quarter",
  },
  {
    key: "sif_teste_treponemico",
    label: "Teste Treponêmico (após 18 meses)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Não realizado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 52,
    sinanCode: "TR_TREPON",
    width: "quarter",
  },
  {
    key: "sif_vdrl_lcr",
    label: "VDRL Líquor",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Não realizado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 53,
    sinanCode: "VDRL_LCR",
    width: "quarter",
  },
  {
    key: "sif_rx_ossos_longos",
    label: "RX Ossos Longos",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Alterações compatíveis com sífilis congênita" },
      { value: "2", label: "Sem alterações" },
      { value: "3", label: "Não realizado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 54,
    sinanCode: "RX_OSSOS",
    width: "half",
  },
  {
    key: "sif_tratamento_crianca",
    label: "Esquema de Tratamento da Criança",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Penicilina G cristalina 100.000 a 150.000 UI/kg/dia por 10 dias" },
      { value: "2", label: "Penicilina G procaína 50.000 UI/kg/dia por 10 dias" },
      { value: "3", label: "Penicilina G benzatina 50.000 UI/kg dose única" },
      { value: "4", label: "Outro esquema" },
      { value: "5", label: "Não realizado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 60,
    sinanCode: "TRAT_CRIA",
    width: "full",
  },
];

const SIFILIS_GESTANTE_FIELDS: SinanField[] = [
  {
    key: "sif_g_class_clinica",
    label: "Classificação Clínica",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sífilis primária" },
      { value: "2", label: "Sífilis secundária" },
      { value: "3", label: "Sífilis terciária" },
      { value: "4", label: "Sífilis latente" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "CLAS_CLIN",
    width: "half",
  },
  {
    key: "sif_g_idade_gestacional_diag",
    label: "Idade Gestacional no Diagnóstico (semanas)",
    type: "number",
    required: false,
    group: "clinicos",
    order: 36,
    sinanCode: "IG_DIAG",
    validation: { min: 1, max: 45 },
    width: "quarter",
  },
  {
    key: "sif_g_momento_diagnostico",
    label: "Diagnóstico Realizado Durante",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Pré-natal" },
      { value: "2", label: "Parto/Curetagem" },
      { value: "3", label: "Pós-parto" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "DIAG_MOM",
    width: "half",
  },
  {
    key: "sif_g_teste_nao_treponemico",
    label: "Teste Não Treponêmico (VDRL/RPR)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Não realizado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 50,
    sinanCode: "T_N_TREPO",
    width: "quarter",
  },
  {
    key: "sif_g_titulacao",
    label: "Titulação",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "1:1" },
      { value: "2", label: "1:2" },
      { value: "4", label: "1:4" },
      { value: "8", label: "1:8" },
      { value: "16", label: "1:16" },
      { value: "32", label: "1:32" },
      { value: "64", label: "1:64" },
      { value: "128", label: "1:128 ou mais" },
    ],
    order: 51,
    sinanCode: "TIT_NT",
    dependsOn: { field: "sif_g_teste_nao_treponemico", value: "1" },
    width: "quarter",
  },
  {
    key: "sif_g_teste_treponemico",
    label: "Teste Treponêmico",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Não realizado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 52,
    sinanCode: "T_TREPO",
    width: "quarter",
  },
  {
    key: "sif_g_esquema_tratamento",
    label: "Esquema de Tratamento",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Penicilina G benzatina 2.400.000 UI" },
      { value: "2", label: "Penicilina G benzatina 4.800.000 UI" },
      { value: "3", label: "Penicilina G benzatina 7.200.000 UI" },
      { value: "4", label: "Outro esquema" },
      { value: "5", label: "Não realizado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 60,
    sinanCode: "ESQ_TRAT",
    width: "half",
  },
  {
    key: "sif_g_tratamento_parceiro",
    label: "Tratamento do Parceiro",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 61,
    sinanCode: "TRAT_PARC",
    width: "quarter",
  },
  {
    key: "sif_g_motivo_nao_trat_parceiro",
    label: "Motivo do Não Tratamento do Parceiro",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Parceiro não foi comunicado" },
      { value: "2", label: "Parceiro não compareceu" },
      { value: "3", label: "Parceiro com exames negativos" },
      { value: "4", label: "Outro motivo" },
      { value: "9", label: "Ignorado" },
    ],
    order: 62,
    sinanCode: "MOT_N_TRT",
    dependsOn: { field: "sif_g_tratamento_parceiro", value: "2" },
    width: "half",
  },
];

export const SIFILIS_CONGENITA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_sifilis_congenita",
  nome: "Sífilis Congênita",
  agravoCode: "A50",
  cid10: "A50",
  categoria: "ist",
  versaoFicha: "SIFCONG_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...SIFILIS_CONGENITA_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const SIFILIS_GESTANTE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_sifilis_gestante",
  nome: "Sífilis em Gestante",
  agravoCode: "A52",
  cid10: "O98.1",
  categoria: "ist",
  versaoFicha: "SIFGEST_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...SIFILIS_GESTANTE_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};
