import { SinanFormTemplate, SinanField, SINAN_COMMON_FIELDS, SINAN_FORM_GROUPS } from "../template-types";

const ACIDENTE_TRABALHO_GRAVE_FIELDS: SinanField[] = [
  {
    key: "atg_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado" },
      { value: "2", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "atg_tipo_acidente",
    label: "Tipo de Acidente",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Típico" },
      { value: "2", label: "De trajeto" },
      { value: "3", label: "Doença do trabalho" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "TP_ACID",
    width: "half",
  },
  {
    key: "atg_causa_acidente",
    label: "Causa do Acidente",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Queda" },
      { value: "2", label: "Máquina/equipamento" },
      { value: "3", label: "Veículo de transporte" },
      { value: "4", label: "Queda de objeto" },
      { value: "5", label: "Choque elétrico" },
      { value: "6", label: "Incêndio/explosão" },
      { value: "7", label: "Substância química" },
      { value: "8", label: "Agressão/violência" },
      { value: "9", label: "Outra" },
    ],
    order: 36,
    sinanCode: "CAUSA_ACID",
    width: "half",
  },
  {
    key: "atg_natureza_lesao",
    label: "Natureza da Lesão Principal",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Fratura" },
      { value: "2", label: "Luxação" },
      { value: "3", label: "Amputação" },
      { value: "4", label: "Ferimento corto-contuso" },
      { value: "5", label: "Queimadura" },
      { value: "6", label: "Contusão/esmagamento" },
      { value: "7", label: "Intoxicação" },
      { value: "8", label: "Politraumatismo" },
      { value: "9", label: "Outra" },
    ],
    order: 37,
    sinanCode: "NAT_LESAO",
    width: "half",
  },
  {
    key: "atg_parte_corpo",
    label: "Parte do Corpo Atingida",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Cabeça/face" },
      { value: "2", label: "Pescoço" },
      { value: "3", label: "Tórax" },
      { value: "4", label: "Abdome" },
      { value: "5", label: "Membro superior" },
      { value: "6", label: "Mão/dedos" },
      { value: "7", label: "Membro inferior" },
      { value: "8", label: "Pé/dedos" },
      { value: "9", label: "Múltiplas partes" },
    ],
    order: 38,
    sinanCode: "PARTE_CORP",
    width: "half",
  },
  {
    key: "atg_obito",
    label: "Evolução para Óbito",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 39,
    sinanCode: "OBITO",
    width: "quarter",
  },
  {
    key: "atg_ocupacao",
    label: "Ocupação (CBO)",
    type: "text",
    required: false,
    group: "antecedentes",
    order: 34,
    sinanCode: "OCUPACAO",
    width: "half",
  },
  {
    key: "atg_cnae",
    label: "Atividade Econômica (CNAE)",
    type: "text",
    required: false,
    group: "antecedentes",
    order: 35,
    sinanCode: "CNAE",
    width: "half",
  },
  {
    key: "atg_situacao_trabalhador",
    label: "Situação no Mercado de Trabalho",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Empregado registrado com CTPS" },
      { value: "2", label: "Empregado não registrado" },
      { value: "3", label: "Autônomo/conta própria" },
      { value: "4", label: "Servidor público estatutário" },
      { value: "5", label: "Servidor público celetista" },
      { value: "6", label: "Aposentado" },
      { value: "7", label: "Desempregado" },
      { value: "8", label: "Trabalho temporário" },
      { value: "9", label: "Cooperativado" },
      { value: "10", label: "Trabalhador avulso" },
      { value: "11", label: "Empregador" },
      { value: "12", label: "Outros" },
      { value: "99", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "SIT_MERC",
    width: "half",
  },
  {
    key: "atg_cat_emitida",
    label: "CAT Emitida",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "3", label: "Não se aplica" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "CAT",
    width: "quarter",
  },
];

const ACIDENTE_BIOLOGICO_FIELDS: SinanField[] = [
  {
    key: "abio_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado" },
      { value: "2", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "abio_tipo_exposicao",
    label: "Tipo de Exposição",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Percutânea" },
      { value: "2", label: "Mucosa ocular" },
      { value: "3", label: "Mucosa oral" },
      { value: "4", label: "Pele íntegra" },
      { value: "5", label: "Pele não íntegra" },
      { value: "6", label: "Mordedura humana" },
    ],
    order: 35,
    sinanCode: "TP_EXP",
    width: "half",
  },
  {
    key: "abio_material_organico",
    label: "Material Orgânico",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sangue" },
      { value: "2", label: "Líquor" },
      { value: "3", label: "Líquido pleural" },
      { value: "4", label: "Líquido amniótico" },
      { value: "5", label: "Sêmen" },
      { value: "6", label: "Secreção vaginal" },
      { value: "7", label: "Outro fluido com sangue" },
      { value: "8", label: "Outro fluido sem sangue" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "MAT_ORG",
    width: "half",
  },
  {
    key: "abio_agente",
    label: "Agente Causador",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Agulha com lúmen" },
      { value: "2", label: "Agulha sem lúmen" },
      { value: "3", label: "Lâmina/lanceta" },
      { value: "4", label: "Vidro" },
      { value: "5", label: "Outro perfurocortante" },
      { value: "6", label: "Não se aplica (mucosa)" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "AGENTE",
    width: "half",
  },
  {
    key: "abio_circunstancia",
    label: "Circunstância do Acidente",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Administração de medicação EV/IM/SC/ID" },
      { value: "2", label: "Punção venosa/arterial para coleta" },
      { value: "3", label: "Procedimento cirúrgico" },
      { value: "4", label: "Procedimento odontológico" },
      { value: "5", label: "Procedimento laboratorial" },
      { value: "6", label: "Descarte de material" },
      { value: "7", label: "Reencape de agulha" },
      { value: "8", label: "Lavagem de material" },
      { value: "9", label: "Manipulação de caixa com perfurocortante" },
      { value: "10", label: "Outro" },
      { value: "99", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "CIRCUNST",
    width: "half",
  },
  {
    key: "abio_uso_epi",
    label: "Uso de EPI no Momento",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "EPI",
    width: "quarter",
  },
  {
    key: "abio_situacao_vacinal_hepb",
    label: "Situação Vacinal Hepatite B",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Vacinado (3 doses)" },
      { value: "2", label: "Vacinação incompleta" },
      { value: "3", label: "Não vacinado" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "VAC_HEPB",
    width: "half",
  },
  {
    key: "abio_fonte_hiv",
    label: "Paciente Fonte - HIV",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Desconhecido" },
      { value: "4", label: "Não se aplica" },
    ],
    order: 50,
    sinanCode: "FONTE_HIV",
    width: "quarter",
  },
  {
    key: "abio_fonte_hepb",
    label: "Paciente Fonte - Hepatite B",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "HBsAg reagente" },
      { value: "2", label: "HBsAg não reagente" },
      { value: "3", label: "Desconhecido" },
      { value: "4", label: "Não se aplica" },
    ],
    order: 51,
    sinanCode: "FONTE_HEPB",
    width: "quarter",
  },
  {
    key: "abio_fonte_hepc",
    label: "Paciente Fonte - Hepatite C",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Anti-HCV reagente" },
      { value: "2", label: "Anti-HCV não reagente" },
      { value: "3", label: "Desconhecido" },
      { value: "4", label: "Não se aplica" },
    ],
    order: 52,
    sinanCode: "FONTE_HEPC",
    width: "quarter",
  },
  {
    key: "abio_pep",
    label: "Indicada PEP (Profilaxia Pós-Exposição)",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 60,
    sinanCode: "PEP",
    width: "quarter",
  },
];

const LER_DORT_FIELDS: SinanField[] = [
  {
    key: "ler_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado" },
      { value: "2", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "ler_diagnostico",
    label: "Diagnóstico Específico",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Síndrome do túnel do carpo" },
      { value: "2", label: "Epicondilite lateral/medial" },
      { value: "3", label: "Tendinite de ombro" },
      { value: "4", label: "Tenossinovite" },
      { value: "5", label: "Bursite" },
      { value: "6", label: "Cervicobraquialgia" },
      { value: "7", label: "Lombalgia ocupacional" },
      { value: "8", label: "Outra" },
    ],
    order: 35,
    sinanCode: "DIAGNOST",
    width: "half",
  },
  {
    key: "ler_localizacao",
    label: "Localização da Lesão",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Mão/punho/dedos" },
      { value: "2", label: "Antebraço" },
      { value: "3", label: "Cotovelo" },
      { value: "4", label: "Braço" },
      { value: "5", label: "Ombro" },
      { value: "6", label: "Pescoço/cervical" },
      { value: "7", label: "Coluna lombar" },
      { value: "8", label: "Múltiplas localizações" },
    ],
    order: 36,
    sinanCode: "LOCALIZ",
    width: "half",
  },
  {
    key: "ler_lateralidade",
    label: "Lateralidade",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Direito" },
      { value: "2", label: "Esquerdo" },
      { value: "3", label: "Bilateral" },
      { value: "4", label: "Não se aplica" },
    ],
    order: 37,
    sinanCode: "LATERAL",
    width: "quarter",
  },
  {
    key: "ler_tempo_exposicao",
    label: "Tempo de Exposição (anos)",
    type: "number",
    required: false,
    group: "antecedentes",
    order: 34,
    sinanCode: "TEMPO_EXP",
    width: "quarter",
  },
  {
    key: "ler_fator_risco",
    label: "Principal Fator de Risco",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Movimentos repetitivos" },
      { value: "2", label: "Esforço físico intenso" },
      { value: "3", label: "Postura inadequada" },
      { value: "4", label: "Compressão mecânica" },
      { value: "5", label: "Vibração" },
      { value: "6", label: "Frio" },
      { value: "7", label: "Múltiplos fatores" },
    ],
    order: 35,
    sinanCode: "FAT_RISCO",
    width: "half",
  },
  {
    key: "ler_nexo_causal",
    label: "Nexo Causal Estabelecido",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Inconclusivo" },
    ],
    order: 101,
    sinanCode: "NEXO",
    width: "quarter",
  },
];

const PAIR_FIELDS: SinanField[] = [
  {
    key: "pair_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado" },
      { value: "2", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "pair_grau_perda",
    label: "Grau da Perda Auditiva",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Leve (26-40 dB)" },
      { value: "2", label: "Moderada (41-55 dB)" },
      { value: "3", label: "Moderadamente severa (56-70 dB)" },
      { value: "4", label: "Severa (71-90 dB)" },
      { value: "5", label: "Profunda (> 90 dB)" },
    ],
    order: 35,
    sinanCode: "GRAU_PERD",
    width: "half",
  },
  {
    key: "pair_lateralidade",
    label: "Lateralidade",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Ouvido direito" },
      { value: "2", label: "Ouvido esquerdo" },
      { value: "3", label: "Bilateral" },
    ],
    order: 36,
    sinanCode: "LATERAL",
    width: "quarter",
  },
  {
    key: "pair_zumbido",
    label: "Zumbido",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "ZUMBIDO",
    width: "quarter",
  },
  {
    key: "pair_tempo_exposicao",
    label: "Tempo de Exposição ao Ruído (anos)",
    type: "number",
    required: false,
    group: "antecedentes",
    order: 34,
    sinanCode: "TEMPO_EXP",
    width: "quarter",
  },
  {
    key: "pair_nivel_ruido",
    label: "Nível de Ruído (dB)",
    type: "number",
    required: false,
    group: "antecedentes",
    order: 35,
    sinanCode: "NIV_RUIDO",
    width: "quarter",
  },
  {
    key: "pair_uso_epi",
    label: "Uso de EPI (Protetor Auricular)",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim, regularmente" },
      { value: "2", label: "Sim, irregularmente" },
      { value: "3", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "EPI",
    width: "half",
  },
  {
    key: "pair_audiometria",
    label: "Audiometria Ocupacional",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Alterada" },
      { value: "2", label: "Normal" },
      { value: "3", label: "Não realizada" },
    ],
    order: 50,
    sinanCode: "AUDIOM",
    width: "quarter",
  },
];

const PNEUMOCONIOSE_FIELDS: SinanField[] = [
  {
    key: "pnm_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado" },
      { value: "2", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "pnm_tipo",
    label: "Tipo de Pneumoconiose",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Silicose" },
      { value: "2", label: "Asbestose" },
      { value: "3", label: "Pneumoconiose do carvoeiro" },
      { value: "4", label: "Siderose" },
      { value: "5", label: "Talcose" },
      { value: "6", label: "Outra" },
    ],
    order: 35,
    sinanCode: "TIPO",
    width: "half",
  },
  {
    key: "pnm_dispneia",
    label: "Dispneia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "DISPNEIA",
    width: "quarter",
  },
  {
    key: "pnm_tosse",
    label: "Tosse Crônica",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "TOSSE",
    width: "quarter",
  },
  {
    key: "pnm_tempo_exposicao",
    label: "Tempo de Exposição (anos)",
    type: "number",
    required: false,
    group: "antecedentes",
    order: 34,
    sinanCode: "TEMPO_EXP",
    width: "quarter",
  },
  {
    key: "pnm_raio_x",
    label: "Radiografia de Tórax (OIT)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Alterações compatíveis" },
      { value: "2", label: "Normal" },
      { value: "3", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "RX_TORAX",
    width: "half",
  },
  {
    key: "pnm_espirometria",
    label: "Espirometria",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Padrão restritivo" },
      { value: "2", label: "Padrão obstrutivo" },
      { value: "3", label: "Padrão misto" },
      { value: "4", label: "Normal" },
      { value: "5", label: "Não realizada" },
    ],
    order: 51,
    sinanCode: "ESPIROM",
    width: "half",
  },
];

export const ACIDENTE_TRABALHO_GRAVE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_acidente_trabalho_grave",
  nome: "Acidente de Trabalho Grave",
  agravoCode: "W64",
  cid10: "W64",
  categoria: "trabalho",
  versaoFicha: "ATG_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...ACIDENTE_TRABALHO_GRAVE_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const ACIDENTE_TRABALHO_CRIANCA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_acidente_trabalho_crianca",
  nome: "Trabalho Infantil / Acidente de Trabalho em < 18 anos",
  agravoCode: "Y97",
  cid10: "Y97",
  categoria: "trabalho",
  versaoFicha: "ATCRI_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...ACIDENTE_TRABALHO_GRAVE_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const ACIDENTE_BIOLOGICO_TEMPLATE: SinanFormTemplate = {
  id: "sinan_acidente_biologico",
  nome: "Acidente de Trabalho com Exposição a Material Biológico",
  agravoCode: "W65",
  cid10: "W65",
  categoria: "trabalho",
  versaoFicha: "ATBIO_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...ACIDENTE_BIOLOGICO_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const LER_DORT_TEMPLATE: SinanFormTemplate = {
  id: "sinan_ler_dort",
  nome: "LER/DORT",
  agravoCode: "M65",
  cid10: "M65",
  cid10Range: "M60-M79",
  categoria: "trabalho",
  versaoFicha: "LERDORT_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...LER_DORT_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const PAIR_TEMPLATE: SinanFormTemplate = {
  id: "sinan_pair",
  nome: "PAIR - Perda Auditiva Induzida por Ruído",
  agravoCode: "H83.3",
  cid10: "H83.3",
  categoria: "trabalho",
  versaoFicha: "PAIR_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...PAIR_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const PNEUMOCONIOSE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_pneumoconiose",
  nome: "Pneumoconioses",
  agravoCode: "J60",
  cid10: "J60",
  cid10Range: "J60-J70",
  categoria: "trabalho",
  versaoFicha: "PNEUMO_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...PNEUMOCONIOSE_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const DERMATOSE_OCUPACIONAL_TEMPLATE: SinanFormTemplate = {
  id: "sinan_dermatose_ocupacional",
  nome: "Dermatose Ocupacional",
  agravoCode: "L23",
  cid10: "L23",
  cid10Range: "L20-L30",
  categoria: "trabalho",
  versaoFicha: "DERMOC_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const CANCER_RELACIONADO_TRABALHO_TEMPLATE: SinanFormTemplate = {
  id: "sinan_cancer_trabalho",
  nome: "Câncer Relacionado ao Trabalho",
  agravoCode: "C80",
  cid10: "C80",
  cid10Range: "C00-D48",
  categoria: "trabalho",
  versaoFicha: "CANCTRAB_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const TRANSTORNO_MENTAL_TRABALHO_TEMPLATE: SinanFormTemplate = {
  id: "sinan_transtorno_mental_trabalho",
  nome: "Transtorno Mental Relacionado ao Trabalho",
  agravoCode: "F43",
  cid10: "F43",
  cid10Range: "F00-F99",
  categoria: "trabalho",
  versaoFicha: "TMTRAB_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

const INTOXICACAO_OCUPACIONAL_FIELDS: SinanField[] = [
  {
    key: "intox_oc_agente",
    label: "Agente Tóxico",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Agrotóxico/Pesticida" },
      { value: "2", label: "Metal pesado" },
      { value: "3", label: "Solvente orgânico" },
      { value: "4", label: "Gás/Vapor" },
      { value: "5", label: "Poeira mineral" },
      { value: "6", label: "Produto químico industrial" },
      { value: "9", label: "Outro" },
    ],
    order: 35,
    sinanCode: "AGENTE_TOX",
    width: "half",
  },
  {
    key: "intox_oc_via",
    label: "Via de Exposição",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Inalatória" },
      { value: "2", label: "Cutânea" },
      { value: "3", label: "Oral" },
      { value: "4", label: "Ocular" },
      { value: "5", label: "Múltiplas" },
    ],
    order: 36,
    sinanCode: "VIA_EXPOS",
    width: "quarter",
  },
  {
    key: "intox_oc_epi",
    label: "Uso de EPI",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim, completo" },
      { value: "2", label: "Sim, incompleto" },
      { value: "3", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "USO_EPI",
    width: "quarter",
  },
  {
    key: "intox_oc_cat",
    label: "CAT Emitida",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "3", label: "Não se aplica" },
    ],
    order: 35,
    sinanCode: "CAT",
    width: "quarter",
  },
  {
    key: "intox_oc_cnae",
    label: "CNAE da Empresa",
    type: "text",
    required: false,
    group: "antecedentes",
    order: 36,
    sinanCode: "CNAE",
    width: "quarter",
  },
];

export const INTOXICACAO_OCUPACIONAL_TEMPLATE: SinanFormTemplate = {
  id: "sinan_intoxicacao_ocupacional",
  nome: "Intoxicação Exógena Ocupacional",
  agravoCode: "X49",
  cid10: "X49",
  categoria: "trabalho",
  versaoFicha: "INTOXOC_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...INTOXICACAO_OCUPACIONAL_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};
