import { SinanFormTemplate, SinanField, SINAN_COMMON_FIELDS, SINAN_FORM_GROUPS } from "../template-types";

const TUBERCULOSE_SPECIFIC_FIELDS: SinanField[] = [
  {
    key: "tb_forma",
    label: "Forma",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Pulmonar" },
      { value: "2", label: "Extrapulmonar" },
      { value: "3", label: "Pulmonar + Extrapulmonar" },
    ],
    order: 35,
    sinanCode: "FORMA",
    width: "half",
  },
  {
    key: "tb_extrapulmonar",
    label: "Se Extrapulmonar, qual localização",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Pleural" },
      { value: "2", label: "Ganglionar periférica" },
      { value: "3", label: "Geniturinária" },
      { value: "4", label: "Óssea" },
      { value: "5", label: "Ocular" },
      { value: "6", label: "Miliar" },
      { value: "7", label: "Meningoencefálica" },
      { value: "8", label: "Cutânea" },
      { value: "9", label: "Laríngea" },
      { value: "10", label: "Outra" },
    ],
    order: 36,
    sinanCode: "EXTRAPULM",
    dependsOn: { field: "tb_forma", value: ["2", "3"] },
    width: "half",
  },
  {
    key: "tb_tipo_entrada",
    label: "Tipo de Entrada",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Caso novo" },
      { value: "2", label: "Recidiva" },
      { value: "3", label: "Reingresso após abandono" },
      { value: "4", label: "Não sabe" },
      { value: "5", label: "Transferência" },
      { value: "6", label: "Pós-óbito" },
    ],
    order: 37,
    sinanCode: "TRATAM_ANT",
    width: "half",
  },
  {
    key: "tb_institucionalizado",
    label: "Institucionalizado",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Não" },
      { value: "2", label: "Presídio" },
      { value: "3", label: "Asilo" },
      { value: "4", label: "Orfanato" },
      { value: "5", label: "Hospital psiquiátrico" },
      { value: "6", label: "Outro" },
    ],
    order: 34,
    sinanCode: "INSTITUCI",
    width: "half",
  },
  {
    key: "tb_populacao_rua",
    label: "Situação de Rua",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "POP_RUA",
    width: "quarter",
  },
  {
    key: "tb_profissional_saude",
    label: "Profissional de Saúde",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "PROF_SAUD",
    width: "quarter",
  },
  {
    key: "tb_privado_liberdade",
    label: "Privado de Liberdade",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "PRIV_LIB",
    width: "quarter",
  },
  {
    key: "tb_imigrante",
    label: "Imigrante",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "IMIGRANTE",
    width: "quarter",
  },
  {
    key: "tb_baciloscopia_escarro",
    label: "Baciloscopia de Escarro",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positiva" },
      { value: "2", label: "Negativa" },
      { value: "3", label: "Não realizada" },
      { value: "4", label: "Não se aplica" },
    ],
    order: 50,
    sinanCode: "BACILOS_E",
    width: "quarter",
  },
  {
    key: "tb_cultura_escarro",
    label: "Cultura de Escarro",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positiva" },
      { value: "2", label: "Negativa" },
      { value: "3", label: "Em andamento" },
      { value: "4", label: "Não realizada" },
    ],
    order: 51,
    sinanCode: "CULTURA_E",
    width: "quarter",
  },
  {
    key: "tb_teste_molecular",
    label: "Teste Rápido Molecular TB",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Detectável sensível Rif" },
      { value: "2", label: "Detectável resistente Rif" },
      { value: "3", label: "Não detectável" },
      { value: "4", label: "Inconclusivo" },
      { value: "5", label: "Não realizado" },
    ],
    order: 52,
    sinanCode: "TRM",
    width: "half",
  },
  {
    key: "tb_teste_sensibilidade",
    label: "Teste de Sensibilidade",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Sensível" },
      { value: "2", label: "Resistente Isoniazida" },
      { value: "3", label: "Resistente Rifampicina" },
      { value: "4", label: "Resistente outras" },
      { value: "5", label: "Resistência múltipla (MDR)" },
      { value: "6", label: "Resistência extensiva (XDR)" },
      { value: "7", label: "Em andamento" },
      { value: "8", label: "Não realizado" },
    ],
    order: 53,
    sinanCode: "TS",
    width: "half",
  },
  {
    key: "tb_hiv",
    label: "HIV",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positivo" },
      { value: "2", label: "Negativo" },
      { value: "3", label: "Em andamento" },
      { value: "4", label: "Não realizado" },
    ],
    order: 54,
    sinanCode: "HIV",
    width: "quarter",
  },
  {
    key: "tb_aids",
    label: "AIDS",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "AIDS",
    dependsOn: { field: "tb_hiv", value: "1" },
    width: "quarter",
  },
  {
    key: "tb_uso_alcool",
    label: "Uso de Álcool",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "ALCOOLISM",
    width: "quarter",
  },
  {
    key: "tb_tabagismo",
    label: "Tabagismo",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 41,
    sinanCode: "TABAGISMO",
    width: "quarter",
  },
  {
    key: "tb_diabetes",
    label: "Diabetes",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 42,
    sinanCode: "DIABETES",
    width: "quarter",
  },
  {
    key: "tb_doenca_mental",
    label: "Doença Mental",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 43,
    sinanCode: "DOENC_MEN",
    width: "quarter",
  },
  {
    key: "tb_drogas_ilicitas",
    label: "Drogas Ilícitas",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 44,
    sinanCode: "DROGAS",
    width: "quarter",
  },
  {
    key: "tb_tratamento_dot",
    label: "Tratamento Diretamente Observado (TDO)",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 60,
    sinanCode: "TDO",
    width: "half",
  },
  {
    key: "tb_esquema",
    label: "Esquema de Tratamento",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Básico" },
      { value: "2", label: "Básico + Etambutol" },
      { value: "3", label: "Para TB Meningoencefálica" },
      { value: "4", label: "Para TB Multidroga-resistente" },
      { value: "5", label: "Outros" },
    ],
    order: 61,
    sinanCode: "ESQUEMA",
    width: "half",
  },
  {
    key: "tb_dt_inicio_tratamento",
    label: "Data de Início do Tratamento",
    type: "date",
    required: false,
    group: "tratamento",
    order: 62,
    sinanCode: "DT_INIC_TR",
    width: "third",
  },
  {
    key: "tb_situacao_encerramento",
    label: "Situação de Encerramento",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Cura" },
      { value: "2", label: "Abandono" },
      { value: "3", label: "Óbito por tuberculose" },
      { value: "4", label: "Óbito por outras causas" },
      { value: "5", label: "Transferência" },
      { value: "6", label: "TB-DR (mudança de esquema)" },
      { value: "7", label: "Mudança de diagnóstico" },
      { value: "8", label: "Falência" },
      { value: "9", label: "Abandono primário" },
    ],
    order: 100,
    sinanCode: "SIT_ENCER",
    width: "half",
  },
  {
    key: "tb_dt_encerramento",
    label: "Data de Encerramento",
    type: "date",
    required: false,
    group: "conclusao",
    order: 101,
    sinanCode: "DT_ENCERRA",
    width: "third",
  },
  {
    key: "tb_beneficiario_gov",
    label: "Beneficiário de Programa de Transferência de Renda do Governo",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 45,
    sinanCode: "BENEF_GOV",
    width: "half",
  },
  {
    key: "tb_raio_x_torax",
    label: "Raio-X de Tórax",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Suspeito" },
      { value: "2", label: "Normal" },
      { value: "3", label: "Outra patologia" },
      { value: "4", label: "Não realizado" },
    ],
    order: 55,
    sinanCode: "RX_TORAX",
    width: "quarter",
  },
];

export const TUBERCULOSE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_tuberculose",
  nome: "Tuberculose",
  agravoCode: "A15",
  cid10: "A15",
  cid10Range: "A15-A19",
  categoria: "respiratorias",
  versaoFicha: "TB_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...TUBERCULOSE_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "tb_forma",
    "tb_tipo_entrada",
  ],
};
