import { SinanFormTemplate, SinanField, SINAN_COMMON_FIELDS, SINAN_FORM_GROUPS } from "../template-types";

const VIOLENCIA_SPECIFIC_FIELDS: SinanField[] = [
  {
    key: "viol_local_ocorrencia",
    label: "Local de Ocorrência",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Residência" },
      { value: "2", label: "Habitação coletiva" },
      { value: "3", label: "Escola" },
      { value: "4", label: "Local de prática esportiva" },
      { value: "5", label: "Bar ou similar" },
      { value: "6", label: "Via pública" },
      { value: "7", label: "Comércio/Serviços" },
      { value: "8", label: "Indústrias/Construção" },
      { value: "9", label: "Outro" },
      { value: "99", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "LOCAL_OCOR",
    width: "half",
  },
  {
    key: "viol_ocorreu_outras_vezes",
    label: "Ocorreu Outras Vezes",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "OUT_VEZES",
    width: "quarter",
  },
  {
    key: "viol_autoprovocada",
    label: "Lesão Autoprovocada",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "LES_AUTOP",
    width: "quarter",
  },
  {
    key: "viol_tipo_violencia_fisica",
    label: "Violência Física",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "VIOL_FIS",
    width: "quarter",
  },
  {
    key: "viol_tipo_violencia_psicologica",
    label: "Violência Psicológica/Moral",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "VIOL_PSI",
    width: "quarter",
  },
  {
    key: "viol_tipo_violencia_tortura",
    label: "Tortura",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "TORTURA",
    width: "quarter",
  },
  {
    key: "viol_tipo_violencia_sexual",
    label: "Violência Sexual",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "VIOL_SEX",
    width: "quarter",
  },
  {
    key: "viol_tipo_violencia_trafico",
    label: "Tráfico de Seres Humanos",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "TRAFICO",
    width: "quarter",
  },
  {
    key: "viol_tipo_violencia_financeira",
    label: "Violência Financeira/Econômica",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 41,
    sinanCode: "FINANC",
    width: "quarter",
  },
  {
    key: "viol_tipo_violencia_negligencia",
    label: "Negligência/Abandono",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 42,
    sinanCode: "NEGLIG",
    width: "quarter",
  },
  {
    key: "viol_tipo_violencia_trabalho_infantil",
    label: "Trabalho Infantil",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 43,
    sinanCode: "TRAB_INF",
    width: "quarter",
  },
  {
    key: "viol_tipo_violencia_intervencao_legal",
    label: "Intervenção Legal",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 44,
    sinanCode: "INTER_LEG",
    width: "quarter",
  },
  {
    key: "viol_meio_agressao_forca",
    label: "Meio - Força Corporal/Espancamento",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 50,
    sinanCode: "FORCA",
    width: "quarter",
  },
  {
    key: "viol_meio_agressao_enforcamento",
    label: "Meio - Enforcamento",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 51,
    sinanCode: "ENFORC",
    width: "quarter",
  },
  {
    key: "viol_meio_agressao_objeto_contundente",
    label: "Meio - Objeto Contundente",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 52,
    sinanCode: "OBJ_CONT",
    width: "quarter",
  },
  {
    key: "viol_meio_agressao_objeto_perfuro",
    label: "Meio - Objeto Perfurocortante",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 53,
    sinanCode: "OBJ_PERF",
    width: "quarter",
  },
  {
    key: "viol_meio_agressao_substancia_quente",
    label: "Meio - Substância/Objeto Quente",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 54,
    sinanCode: "SUB_QUENT",
    width: "quarter",
  },
  {
    key: "viol_meio_agressao_envenenamento",
    label: "Meio - Envenenamento/Intoxicação",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 55,
    sinanCode: "ENVENEN",
    width: "quarter",
  },
  {
    key: "viol_meio_agressao_arma_fogo",
    label: "Meio - Arma de Fogo",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 56,
    sinanCode: "ARMA_FOGO",
    width: "quarter",
  },
  {
    key: "viol_meio_agressao_ameaca",
    label: "Meio - Ameaça",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 57,
    sinanCode: "AMEACA",
    width: "quarter",
  },
  {
    key: "viol_autor_pai",
    label: "Autor - Pai",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 36,
    sinanCode: "AUT_PAI",
    width: "quarter",
  },
  {
    key: "viol_autor_mae",
    label: "Autor - Mãe",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 37,
    sinanCode: "AUT_MAE",
    width: "quarter",
  },
  {
    key: "viol_autor_padrasto",
    label: "Autor - Padrasto",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 38,
    sinanCode: "AUT_PADR",
    width: "quarter",
  },
  {
    key: "viol_autor_madrasta",
    label: "Autor - Madrasta",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 39,
    sinanCode: "AUT_MADR",
    width: "quarter",
  },
  {
    key: "viol_autor_conjuge",
    label: "Autor - Cônjuge",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 40,
    sinanCode: "AUT_CONJ",
    width: "quarter",
  },
  {
    key: "viol_autor_ex_conjuge",
    label: "Autor - Ex-Cônjuge",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 41,
    sinanCode: "AUT_EXCON",
    width: "quarter",
  },
  {
    key: "viol_autor_namorado",
    label: "Autor - Namorado(a)",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 42,
    sinanCode: "AUT_NAM",
    width: "quarter",
  },
  {
    key: "viol_autor_ex_namorado",
    label: "Autor - Ex-Namorado(a)",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 43,
    sinanCode: "AUT_EXNAM",
    width: "quarter",
  },
  {
    key: "viol_autor_desconhecido",
    label: "Autor - Desconhecido",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 44,
    sinanCode: "AUT_DESC",
    width: "quarter",
  },
  {
    key: "viol_autor_sexo",
    label: "Sexo do Provável Autor",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Masculino" },
      { value: "2", label: "Feminino" },
      { value: "3", label: "Ambos os sexos" },
      { value: "9", label: "Ignorado" },
    ],
    order: 45,
    sinanCode: "SEXO_AUT",
    width: "quarter",
  },
  {
    key: "viol_autor_uso_alcool",
    label: "Suspeita de Uso de Álcool",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 46,
    sinanCode: "ALCOOL",
    width: "quarter",
  },
  {
    key: "viol_encaminhamento_rede_saude",
    label: "Encaminhamento - Rede de Saúde",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 60,
    sinanCode: "ENC_SAUDE",
    width: "quarter",
  },
  {
    key: "viol_encaminhamento_rede_assistencia",
    label: "Encaminhamento - Assistência Social",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 61,
    sinanCode: "ENC_ASSIS",
    width: "quarter",
  },
  {
    key: "viol_encaminhamento_delegacia",
    label: "Encaminhamento - Delegacia",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 62,
    sinanCode: "ENC_DELEG",
    width: "quarter",
  },
  {
    key: "viol_encaminhamento_conselho_tutelar",
    label: "Encaminhamento - Conselho Tutelar",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 63,
    sinanCode: "ENC_CONS",
    width: "quarter",
  },
  {
    key: "viol_encaminhamento_iml",
    label: "Encaminhamento - IML",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 64,
    sinanCode: "ENC_IML",
    width: "quarter",
  },
];

export const VIOLENCIA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_violencia",
  nome: "Violência Interpessoal/Autoprovocada",
  agravoCode: "Y09",
  cid10: "Y09",
  categoria: "violencias",
  versaoFicha: "VIOLDOM_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...VIOLENCIA_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};
