import { SinanFormTemplate, SinanField, SINAN_COMMON_FIELDS, SINAN_FORM_GROUPS } from "../template-types";

const EBOLA_MARBURG_FIELDS: SinanField[] = [
  {
    key: "ebm_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Provável" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "ebm_febre",
    label: "Febre",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "ebm_cefaleia",
    label: "Cefaleia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "CEFALEIA",
    width: "quarter",
  },
  {
    key: "ebm_mialgia",
    label: "Mialgia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "MIALGIA",
    width: "quarter",
  },
  {
    key: "ebm_diarreia",
    label: "Diarreia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "DIARREIA",
    width: "quarter",
  },
  {
    key: "ebm_vomito",
    label: "Vômito",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "VOMITO",
    width: "quarter",
  },
  {
    key: "ebm_sangramento",
    label: "Sangramento",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "SANGRAM",
    width: "quarter",
  },
  {
    key: "ebm_local_sangramento",
    label: "Local do Sangramento",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Gengiva" },
      { value: "2", label: "Nasal" },
      { value: "3", label: "Gastrointestinal" },
      { value: "4", label: "Pele" },
      { value: "5", label: "Múltiplo" },
      { value: "6", label: "Outro" },
    ],
    order: 41,
    sinanCode: "LOC_SANG",
    dependsOn: { field: "ebm_sangramento", value: "1" },
    width: "half",
  },
  {
    key: "ebm_viagem",
    label: "Viagem para Área Endêmica (21 dias)",
    type: "select",
    required: true,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "VIAGEM",
    width: "half",
  },
  {
    key: "ebm_contato_caso",
    label: "Contato com Caso Confirmado/Provável",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "CONT_CASO",
    width: "half",
  },
  {
    key: "ebm_rt_pcr",
    label: "RT-PCR",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Detectável" },
      { value: "2", label: "Não detectável" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "RTPCR",
    width: "quarter",
  },
];

const HANTAVIROSE_FIELDS: SinanField[] = [
  {
    key: "han_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "han_forma_clinica",
    label: "Forma Clínica",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Síndrome Cardiopulmonar (SCPH)" },
      { value: "2", label: "Febre Hemorrágica com Síndrome Renal (FHSR)" },
      { value: "3", label: "Mista" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "FORMA_CLI",
    width: "half",
  },
  {
    key: "han_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "han_mialgia",
    label: "Mialgia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "MIALGIA",
    width: "quarter",
  },
  {
    key: "han_dispneia",
    label: "Dispneia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "DISPNEIA",
    width: "quarter",
  },
  {
    key: "han_edema_pulmonar",
    label: "Edema Pulmonar",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "EDEMA_PUL",
    width: "quarter",
  },
  {
    key: "han_insuf_renal",
    label: "Insuficiência Renal",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "INS_RENAL",
    width: "quarter",
  },
  {
    key: "han_exposicao_roedores",
    label: "Exposição a Roedores/Excretas",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "EXP_ROED",
    width: "half",
  },
  {
    key: "han_local_exposicao",
    label: "Local Provável de Exposição",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Peridomicílio" },
      { value: "2", label: "Ambiente de trabalho" },
      { value: "3", label: "Área rural" },
      { value: "4", label: "Lazer/turismo" },
      { value: "5", label: "Outro" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "LOC_EXP",
    width: "half",
  },
  {
    key: "han_elisa_igm",
    label: "ELISA IgM",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "ELISA_IGM",
    width: "quarter",
  },
  {
    key: "han_imunohistoquimica",
    label: "Imunohistoquímica",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positivo" },
      { value: "2", label: "Negativo" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 51,
    sinanCode: "IMUNOHIST",
    width: "quarter",
  },
];

const MPOX_FIELDS: SinanField[] = [
  {
    key: "mpx_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Provável" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "mpx_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "mpx_lesoes_cutaneas",
    label: "Lesões Cutâneas",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 36,
    sinanCode: "LES_CUT",
    width: "quarter",
  },
  {
    key: "mpx_fase_lesoes",
    label: "Fase das Lesões",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Máculas" },
      { value: "2", label: "Pápulas" },
      { value: "3", label: "Vesículas" },
      { value: "4", label: "Pústulas" },
      { value: "5", label: "Crostas" },
      { value: "6", label: "Múltiplas fases" },
    ],
    order: 37,
    sinanCode: "FASE_LES",
    dependsOn: { field: "mpx_lesoes_cutaneas", value: "1" },
    width: "half",
  },
  {
    key: "mpx_local_lesoes",
    label: "Localização das Lesões",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Face" },
      { value: "2", label: "Tronco" },
      { value: "3", label: "Membros" },
      { value: "4", label: "Genitália/perianal" },
      { value: "5", label: "Palmas/plantas" },
      { value: "6", label: "Disseminada" },
    ],
    order: 38,
    sinanCode: "LOC_LES",
    dependsOn: { field: "mpx_lesoes_cutaneas", value: "1" },
    width: "half",
  },
  {
    key: "mpx_linfadenopatia",
    label: "Linfadenopatia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "LINFADEN",
    width: "quarter",
  },
  {
    key: "mpx_proctite",
    label: "Proctite",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "PROCTITE",
    width: "quarter",
  },
  {
    key: "mpx_contato_caso",
    label: "Contato com Caso Confirmado/Provável",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "CONT_CASO",
    width: "half",
  },
  {
    key: "mpx_viagem",
    label: "Viagem para Área com Surto (21 dias)",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "VIAGEM",
    width: "half",
  },
  {
    key: "mpx_pcr",
    label: "PCR",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Detectável" },
      { value: "2", label: "Não detectável" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "PCR",
    width: "quarter",
  },
];

const VARICELA_FIELDS: SinanField[] = [
  {
    key: "var_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "var_tipo",
    label: "Tipo de Manifestação",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Varicela (Catapora)" },
      { value: "2", label: "Herpes Zoster" },
    ],
    order: 35,
    sinanCode: "TIPO",
    width: "half",
  },
  {
    key: "var_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "var_exantema_vesicular",
    label: "Exantema Vesicular",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 37,
    sinanCode: "EXANT_VES",
    width: "quarter",
  },
  {
    key: "var_prurido",
    label: "Prurido",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "PRURIDO",
    width: "quarter",
  },
  {
    key: "var_complicacoes",
    label: "Complicações",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "COMPLIC",
    width: "quarter",
  },
  {
    key: "var_tipo_complicacao",
    label: "Tipo de Complicação",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Infecção bacteriana secundária" },
      { value: "2", label: "Pneumonia" },
      { value: "3", label: "Encefalite" },
      { value: "4", label: "Ataxia cerebelar" },
      { value: "5", label: "Outra" },
    ],
    order: 40,
    sinanCode: "TP_COMPL",
    dependsOn: { field: "var_complicacoes", value: "1" },
    width: "half",
  },
  {
    key: "var_vacinacao",
    label: "Vacinação contra Varicela",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim (1 dose)" },
      { value: "2", label: "Sim (2 doses)" },
      { value: "3", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "VAC_VAR",
    width: "half",
  },
  {
    key: "var_contato_caso",
    label: "Contato com Caso de Varicela",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "CONT_CASO",
    width: "half",
  },
];

const RUBEOLA_FIELDS: SinanField[] = [
  {
    key: "rub_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "rub_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "rub_exantema",
    label: "Exantema",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 36,
    sinanCode: "EXANTEMA",
    width: "quarter",
  },
  {
    key: "rub_linfadenopatia",
    label: "Linfadenopatia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "LINFADEN",
    width: "quarter",
  },
  {
    key: "rub_artralgia",
    label: "Artralgia/Artrite",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "ARTRALGIA",
    width: "quarter",
  },
  {
    key: "rub_conjuntivite",
    label: "Conjuntivite",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "CONJUNTV",
    width: "quarter",
  },
  {
    key: "rub_vacinacao",
    label: "Vacinação contra Rubéola (Tríplice/Tetra Viral)",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim (1 dose)" },
      { value: "2", label: "Sim (2 doses)" },
      { value: "3", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "VAC_RUB",
    width: "half",
  },
  {
    key: "rub_igm",
    label: "Sorologia IgM para Rubéola",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "IGM_RUB",
    width: "quarter",
  },
];

const SRC_FIELDS: SinanField[] = [
  {
    key: "src_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "src_catarata",
    label: "Catarata Congênita",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "CATARATA",
    width: "quarter",
  },
  {
    key: "src_cardiopatia",
    label: "Cardiopatia Congênita",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "CARDIOPAT",
    width: "quarter",
  },
  {
    key: "src_surdez",
    label: "Surdez",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "SURDEZ",
    width: "quarter",
  },
  {
    key: "src_microcefalia",
    label: "Microcefalia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "MICROCEF",
    width: "quarter",
  },
  {
    key: "src_purpura",
    label: "Púrpura",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "PURPURA",
    width: "quarter",
  },
  {
    key: "src_hepatoesplenomegalia",
    label: "Hepatoesplenomegalia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "HEPATOESPL",
    width: "quarter",
  },
  {
    key: "src_rubeola_mae",
    label: "Mãe com Rubéola na Gestação",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim, confirmado" },
      { value: "2", label: "Sim, suspeito" },
      { value: "3", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "RUB_MAE",
    width: "half",
  },
  {
    key: "src_trimestre_infeccao",
    label: "Trimestre da Infecção Materna",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "1º trimestre" },
      { value: "2", label: "2º trimestre" },
      { value: "3", label: "3º trimestre" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "TRIM_INF",
    dependsOn: { field: "src_rubeola_mae", value: ["1", "2"] },
    width: "half",
  },
  {
    key: "src_igm_rn",
    label: "IgM do RN",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "IGM_RN",
    width: "quarter",
  },
];

export const EBOLA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_ebola",
  nome: "Doença por Vírus Ebola",
  agravoCode: "A98.4",
  cid10: "A98.4",
  categoria: "virais",
  versaoFicha: "EBOLA_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...EBOLA_MARBURG_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "ebm_febre",
    "ebm_viagem",
  ],
};

export const MARBURG_TEMPLATE: SinanFormTemplate = {
  id: "sinan_marburg",
  nome: "Febre Hemorrágica de Marburg",
  agravoCode: "A98.3",
  cid10: "A98.3",
  categoria: "virais",
  versaoFicha: "MARBURG_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...EBOLA_MARBURG_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "ebm_febre",
    "ebm_viagem",
  ],
};

export const LASSA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_lassa",
  nome: "Febre de Lassa",
  agravoCode: "A96.2",
  cid10: "A96.2",
  categoria: "virais",
  versaoFicha: "LASSA_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...EBOLA_MARBURG_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const HANTAVIROSE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_hantavirose",
  nome: "Hantavirose",
  agravoCode: "A98.5",
  cid10: "A98.5",
  categoria: "zoonoses",
  versaoFicha: "HANTA_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...HANTAVIROSE_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const MPOX_TEMPLATE: SinanFormTemplate = {
  id: "sinan_mpox",
  nome: "Mpox (Varíola dos Macacos)",
  agravoCode: "B04",
  cid10: "B04",
  categoria: "virais",
  versaoFicha: "MPOX_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...MPOX_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "mpx_lesoes_cutaneas",
  ],
};

export const VARICELA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_varicela",
  nome: "Varicela/Herpes Zoster",
  agravoCode: "B01",
  cid10: "B01",
  categoria: "imunoprevenivel",
  versaoFicha: "VARIC_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...VARICELA_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "var_exantema_vesicular",
  ],
};

export const RUBEOLA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_rubeola",
  nome: "Rubéola",
  agravoCode: "B06",
  cid10: "B06",
  categoria: "imunoprevenivel",
  versaoFicha: "RUB_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...RUBEOLA_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "rub_exantema",
  ],
};

export const SRC_TEMPLATE: SinanFormTemplate = {
  id: "sinan_src",
  nome: "Síndrome da Rubéola Congênita",
  agravoCode: "P35.0",
  cid10: "P35.0",
  categoria: "imunoprevenivel",
  versaoFicha: "SRC_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...SRC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const CAXUMBA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_caxumba",
  nome: "Caxumba (Parotidite Epidêmica)",
  agravoCode: "B26",
  cid10: "B26",
  categoria: "imunoprevenivel",
  versaoFicha: "CAXUMBA_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};
