import { SinanFormTemplate, SinanField, SINAN_COMMON_FIELDS, SINAN_FORM_GROUPS } from "../template-types";

const LEPTOSPIROSE_SPECIFIC_FIELDS: SinanField[] = [
  {
    key: "lepto_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado" },
      { value: "2", label: "Descartado" },
      { value: "8", label: "Inconclusivo" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "lepto_febre",
    label: "Febre",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "FEBRE",
    width: "quarter",
  },
  {
    key: "lepto_mialgia",
    label: "Mialgia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "MIALGIA",
    width: "quarter",
  },
  {
    key: "lepto_cefaleia",
    label: "Cefaleia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "CEFALEIA",
    width: "quarter",
  },
  {
    key: "lepto_ictericia",
    label: "Icterícia",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "ICTERICIA",
    width: "quarter",
  },
  {
    key: "lepto_sufusao_conjuntival",
    label: "Sufusão Conjuntival",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "SUFUSAO",
    width: "quarter",
  },
  {
    key: "lepto_hemorragia",
    label: "Manifestações Hemorrágicas",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "HEMORRG",
    width: "quarter",
  },
  {
    key: "lepto_insuficiencia_renal",
    label: "Insuficiência Renal",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 41,
    sinanCode: "INSUF_REN",
    width: "quarter",
  },
  {
    key: "lepto_contato_agua",
    label: "Contato com Água ou Lama de Enchente",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "AGUA_ENCHE",
    width: "half",
  },
  {
    key: "lepto_contato_animais",
    label: "Contato com Animais (roedores, cães, gado)",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "CONT_ANIM",
    width: "half",
  },
  {
    key: "lepto_presenca_roedores",
    label: "Presença de Roedores no Local",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "ROEDORES",
    width: "quarter",
  },
  {
    key: "lepto_elisa_igm",
    label: "ELISA-IgM",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 50,
    sinanCode: "ELISA_IgM",
    width: "quarter",
  },
  {
    key: "lepto_microaglutinacao",
    label: "Microaglutinação (MAT)",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Reagente" },
      { value: "2", label: "Não reagente" },
      { value: "3", label: "Inconclusivo" },
      { value: "4", label: "Não realizado" },
    ],
    order: 51,
    sinanCode: "MAT",
    width: "quarter",
  },
];

const RAIVA_HUMANA_SPECIFIC_FIELDS: SinanField[] = [
  {
    key: "raiva_classificacao",
    label: "Classificação Final",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Confirmado laboratorial" },
      { value: "2", label: "Confirmado clínico-epidemiológico" },
      { value: "3", label: "Descartado" },
    ],
    order: 100,
    sinanCode: "CLASSI_FIN",
    width: "half",
  },
  {
    key: "raiva_tipo_exposicao",
    label: "Tipo de Exposição",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Mordedura" },
      { value: "2", label: "Arranhadura" },
      { value: "3", label: "Lambedura de mucosa" },
      { value: "4", label: "Lambedura de pele lesada" },
      { value: "5", label: "Contato indireto" },
      { value: "9", label: "Ignorado" },
    ],
    order: 34,
    sinanCode: "TP_EXPOSIC",
    width: "half",
  },
  {
    key: "raiva_especie_animal",
    label: "Espécie do Animal Agressor",
    type: "select",
    required: false,
    group: "antecedentes",
    options: [
      { value: "1", label: "Canina" },
      { value: "2", label: "Felina" },
      { value: "3", label: "Quiróptera (morcego)" },
      { value: "4", label: "Primata" },
      { value: "5", label: "Raposa" },
      { value: "6", label: "Herbívoros" },
      { value: "7", label: "Outra" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "ESP_ANIM",
    width: "half",
  },
  {
    key: "raiva_localizacao_lesao_cabeca",
    label: "Lesão em Cabeça/Pescoço",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 35,
    sinanCode: "LES_CAB",
    width: "quarter",
  },
  {
    key: "raiva_localizacao_lesao_maos",
    label: "Lesão em Mãos/Pés",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 36,
    sinanCode: "LES_MAOS",
    width: "quarter",
  },
  {
    key: "raiva_localizacao_lesao_tronco",
    label: "Lesão em Tronco",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 37,
    sinanCode: "LES_TRONC",
    width: "quarter",
  },
  {
    key: "raiva_localizacao_lesao_membros",
    label: "Lesão em Membros",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
    ],
    order: 38,
    sinanCode: "LES_MEMB",
    width: "quarter",
  },
  {
    key: "raiva_lesao_profunda",
    label: "Lesão Profunda",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "LES_PROF",
    width: "quarter",
  },
  {
    key: "raiva_lesao_multipla",
    label: "Lesão Múltipla",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "LES_MULT",
    width: "quarter",
  },
  {
    key: "raiva_imunofluorescencia",
    label: "Imunofluorescência Direta",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positiva" },
      { value: "2", label: "Negativa" },
      { value: "3", label: "Não realizada" },
    ],
    order: 50,
    sinanCode: "IFD",
    width: "quarter",
  },
  {
    key: "raiva_inoculacao",
    label: "Inoculação em Camundongo",
    type: "select",
    required: false,
    group: "laboratoriais",
    options: [
      { value: "1", label: "Positiva" },
      { value: "2", label: "Negativa" },
      { value: "3", label: "Não realizada" },
    ],
    order: 51,
    sinanCode: "INOCUL",
    width: "quarter",
  },
];

const ACIDENTE_ANIMAL_PECONHENTO_FIELDS: SinanField[] = [
  {
    key: "aap_tipo_animal",
    label: "Tipo de Animal",
    type: "select",
    required: true,
    group: "clinicos",
    options: [
      { value: "1", label: "Serpente" },
      { value: "2", label: "Aranha" },
      { value: "3", label: "Escorpião" },
      { value: "4", label: "Lagarta" },
      { value: "5", label: "Abelha" },
      { value: "6", label: "Outros" },
      { value: "9", label: "Ignorado" },
    ],
    order: 35,
    sinanCode: "TP_ANIM",
    width: "half",
  },
  {
    key: "aap_tipo_serpente",
    label: "Tipo de Serpente",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Jararaca (Bothrops)" },
      { value: "2", label: "Cascavel (Crotalus)" },
      { value: "3", label: "Surucucu (Lachesis)" },
      { value: "4", label: "Coral verdadeira (Micrurus)" },
      { value: "5", label: "Não peçonhenta" },
      { value: "9", label: "Ignorado" },
    ],
    order: 36,
    sinanCode: "TP_SERP",
    dependsOn: { field: "aap_tipo_animal", value: "1" },
    width: "half",
  },
  {
    key: "aap_tipo_aranha",
    label: "Tipo de Aranha",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Phoneutria (armadeira)" },
      { value: "2", label: "Loxosceles (aranha-marrom)" },
      { value: "3", label: "Latrodectus (viúva-negra)" },
      { value: "4", label: "Outra" },
      { value: "9", label: "Ignorado" },
    ],
    order: 37,
    sinanCode: "TP_ARAN",
    dependsOn: { field: "aap_tipo_animal", value: "2" },
    width: "half",
  },
  {
    key: "aap_localizacao_picada",
    label: "Localização da Picada",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Cabeça" },
      { value: "2", label: "Braço" },
      { value: "3", label: "Antebraço" },
      { value: "4", label: "Mão" },
      { value: "5", label: "Dedo da mão" },
      { value: "6", label: "Tronco" },
      { value: "7", label: "Coxa" },
      { value: "8", label: "Perna" },
      { value: "9", label: "Pé" },
      { value: "10", label: "Dedo do pé" },
      { value: "99", label: "Ignorado" },
    ],
    order: 38,
    sinanCode: "LOCAL_PIC",
    width: "half",
  },
  {
    key: "aap_tempo_picada_atendimento",
    label: "Tempo entre Picada e Atendimento",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "0 a 1 hora" },
      { value: "2", label: "1 a 3 horas" },
      { value: "3", label: "3 a 6 horas" },
      { value: "4", label: "6 a 12 horas" },
      { value: "5", label: "12 a 24 horas" },
      { value: "6", label: "Acima de 24 horas" },
      { value: "9", label: "Ignorado" },
    ],
    order: 39,
    sinanCode: "TEMPO_PIC",
    width: "half",
  },
  {
    key: "aap_dor_local",
    label: "Dor Local",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 40,
    sinanCode: "DOR_LOCAL",
    width: "quarter",
  },
  {
    key: "aap_edema_local",
    label: "Edema Local",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 41,
    sinanCode: "EDEMA_LOC",
    width: "quarter",
  },
  {
    key: "aap_equimose",
    label: "Equimose",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 42,
    sinanCode: "EQUIMOSE",
    width: "quarter",
  },
  {
    key: "aap_necrose",
    label: "Necrose",
    type: "select",
    required: false,
    group: "clinicos",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 43,
    sinanCode: "NECROSE",
    width: "quarter",
  },
  {
    key: "aap_classificacao_gravidade",
    label: "Classificação de Gravidade",
    type: "select",
    required: false,
    group: "conclusao",
    options: [
      { value: "1", label: "Leve" },
      { value: "2", label: "Moderado" },
      { value: "3", label: "Grave" },
      { value: "9", label: "Ignorado" },
    ],
    order: 100,
    sinanCode: "GRAVIDADE",
    width: "half",
  },
  {
    key: "aap_soroterapia",
    label: "Soroterapia",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "Sim" },
      { value: "2", label: "Não" },
      { value: "9", label: "Ignorado" },
    ],
    order: 60,
    sinanCode: "SOROTERA",
    width: "quarter",
  },
  {
    key: "aap_tipo_soro",
    label: "Tipo de Soro",
    type: "select",
    required: false,
    group: "tratamento",
    options: [
      { value: "1", label: "SAB (antibotrópico)" },
      { value: "2", label: "SAC (anticrotálico)" },
      { value: "3", label: "SABC (antibotrópico-crotálico)" },
      { value: "4", label: "SAEL (antielapídico)" },
      { value: "5", label: "SAL (antilaquético)" },
      { value: "6", label: "SALOX (antiloxoscélico)" },
      { value: "7", label: "SAA (antiaracnídico)" },
      { value: "8", label: "SAE (antiescorpiônico)" },
      { value: "9", label: "SAEEL (antiescorpiônico-elapídico)" },
    ],
    order: 61,
    sinanCode: "TP_SORO",
    dependsOn: { field: "aap_soroterapia", value: "1" },
    width: "half",
  },
];

export const LEPTOSPIROSE_TEMPLATE: SinanFormTemplate = {
  id: "sinan_leptospirose",
  nome: "Leptospirose",
  agravoCode: "A27",
  cid10: "A27",
  categoria: "zoonoses",
  versaoFicha: "LEPTO_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...LEPTOSPIROSE_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const RAIVA_HUMANA_TEMPLATE: SinanFormTemplate = {
  id: "sinan_raiva_humana",
  nome: "Raiva Humana",
  agravoCode: "A82",
  cid10: "A82",
  categoria: "zoonoses",
  versaoFicha: "RAIVA_v5.0",
  prazoNotificacao: "imediata",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.ANTECEDENTES_EPIDEMIO,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.DADOS_LABORATORIAIS,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...RAIVA_HUMANA_SPECIFIC_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
  ],
};

export const ACIDENTE_ANIMAL_PECONHENTO_TEMPLATE: SinanFormTemplate = {
  id: "sinan_acidente_animal_peconhento",
  nome: "Acidente por Animais Peçonhentos",
  agravoCode: "T63.4",
  cid10: "T63.4",
  categoria: "zoonoses",
  versaoFicha: "ANIMAIS_v5.0",
  prazoNotificacao: "semanal",
  fichaInvestigacao: true,
  groups: [
    SINAN_FORM_GROUPS.DADOS_GERAIS,
    SINAN_FORM_GROUPS.NOTIFICACAO_INDIVIDUAL,
    SINAN_FORM_GROUPS.DADOS_RESIDENCIA,
    SINAN_FORM_GROUPS.DADOS_CLINICOS,
    SINAN_FORM_GROUPS.TRATAMENTO,
    SINAN_FORM_GROUPS.CONCLUSAO,
    SINAN_FORM_GROUPS.INVESTIGADOR,
  ],
  fields: [...SINAN_COMMON_FIELDS, ...ACIDENTE_ANIMAL_PECONHENTO_FIELDS],
  requiredFields: [
    "tipo_notificacao",
    "agravo_doenca",
    "dt_notificacao",
    "uf_notificacao",
    "municipio_notificacao",
    "unidade_saude",
    "paciente_nome",
    "paciente_idade",
    "paciente_idade_tipo",
    "paciente_sexo",
    "res_uf",
    "res_municipio",
    "aap_tipo_animal",
  ],
};
