import { db } from "./db";
import { renameCatalog } from "@shared/schema";

/**
 * Seed do Catálogo RENAME - Relação Nacional de Medicamentos Essenciais
 * Baseado na RENAME 2024 do Ministério da Saúde
 * Inclui classificação Portaria 344/98 ANVISA
 */
export async function seedRENAMECatalog() {
  console.log("[SEED] Iniciando seed catálogo RENAME...");
  
  const medications = [
    // ANALGÉSICOS E ANTIPIRÉTICOS
    {
      code: "RENAME001",
      commercialName: "Dipirona",
      activeIngredient: "Dipirona sódica",
      therapeuticClass: "Analgésico/Antipirético",
      presentation: "500mg comprimido",
      concentration: "500mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: false,
      pediatricDosePerKg: "10-15mg/kg a cada 6h",
      contraindications: ["Alergia a pirazolônicos", "Agranulocitose", "Porfiria"],
      interactions: ["Anticoagulantes", "Metotrexato", "Ciclosporina"],
    },
    {
      code: "RENAME002",
      commercialName: "Paracetamol",
      activeIngredient: "Paracetamol",
      therapeuticClass: "Analgésico/Antipirético",
      presentation: "500mg comprimido",
      concentration: "500mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: false,
      pediatricDosePerKg: "10-15mg/kg a cada 4-6h (máx 60mg/kg/dia)",
      contraindications: ["Insuficiência hepática grave", "Hipersensibilidade"],
      interactions: ["Álcool", "Varfarina", "Isoniazida"],
    },
    {
      code: "RENAME003",
      commercialName: "Ibuprofeno",
      activeIngredient: "Ibuprofeno",
      therapeuticClass: "Anti-inflamatório/Analgésico",
      presentation: "600mg comprimido",
      concentration: "600mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: false,
      pediatricDosePerKg: "5-10mg/kg a cada 6-8h",
      contraindications: ["Úlcera péptica ativa", "Insuficiência renal grave", "Gestação 3º trimestre"],
      interactions: ["AAS", "Anticoagulantes", "Lítio", "Metotrexato"],
    },
    
    // ANTI-HIPERTENSIVOS
    {
      code: "RENAME010",
      commercialName: "Losartana",
      activeIngredient: "Losartana potássica",
      therapeuticClass: "Anti-hipertensivo (BRA)",
      presentation: "50mg comprimido",
      concentration: "50mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: false,
      contraindications: ["Gestação", "Estenose bilateral artéria renal", "Hipercalemia"],
      interactions: ["IECA", "Espironolactona", "Suplementos de potássio", "AINEs"],
    },
    {
      code: "RENAME011",
      commercialName: "Enalapril",
      activeIngredient: "Maleato de enalapril",
      therapeuticClass: "Anti-hipertensivo (IECA)",
      presentation: "10mg comprimido",
      concentration: "10mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: false,
      contraindications: ["Gestação", "Angioedema prévio", "Estenose bilateral"],
      interactions: ["BRA", "Espironolactona", "AINEs", "Lítio"],
    },
    {
      code: "RENAME012",
      commercialName: "Anlodipino",
      activeIngredient: "Besilato de anlodipino",
      therapeuticClass: "Anti-hipertensivo (BCC)",
      presentation: "5mg comprimido",
      concentration: "5mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: false,
      contraindications: ["Choque cardiogênico", "Estenose aórtica grave"],
      interactions: ["Sinvastatina (dose alta)", "Ciclosporina"],
    },
    {
      code: "RENAME013",
      commercialName: "Hidroclorotiazida",
      activeIngredient: "Hidroclorotiazida",
      therapeuticClass: "Diurético tiazídico",
      presentation: "25mg comprimido",
      concentration: "25mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: false,
      contraindications: ["Anúria", "Hipocalemia refratária", "Gota"],
      interactions: ["Lítio", "AINEs", "Digitálicos"],
    },
    
    // ANTIDIABÉTICOS
    {
      code: "RENAME020",
      commercialName: "Metformina",
      activeIngredient: "Cloridrato de metformina",
      therapeuticClass: "Antidiabético oral (Biguanida)",
      presentation: "850mg comprimido",
      concentration: "850mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: false,
      contraindications: ["Insuficiência renal (TFG<30)", "Acidose metabólica", "Alcoolismo"],
      interactions: ["Contraste iodado", "Álcool"],
    },
    {
      code: "RENAME021",
      commercialName: "Glibenclamida",
      activeIngredient: "Glibenclamida",
      therapeuticClass: "Antidiabético oral (Sulfonilureia)",
      presentation: "5mg comprimido",
      concentration: "5mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: false,
      contraindications: ["DM tipo 1", "Cetoacidose", "Insuficiência hepática grave"],
      interactions: ["Álcool", "Betabloqueadores", "AINEs"],
    },
    {
      code: "RENAME022",
      commercialName: "Insulina NPH",
      activeIngredient: "Insulina humana NPH",
      therapeuticClass: "Insulina de ação intermediária",
      presentation: "100UI/ml frasco 10ml",
      concentration: "100UI/ml",
      unit: "UI",
      administrationRoute: "injectable" as const,
      isControlled: false,
      contraindications: ["Hipoglicemia"],
      interactions: ["Betabloqueadores", "Corticoides", "Tiazídicos"],
    },
    
    // ANTIBIÓTICOS
    {
      code: "RENAME030",
      commercialName: "Amoxicilina",
      activeIngredient: "Amoxicilina tri-hidratada",
      therapeuticClass: "Antibiótico (Penicilina)",
      presentation: "500mg cápsula",
      concentration: "500mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: false,
      pediatricDosePerKg: "25-50mg/kg/dia dividido em 8/8h",
      contraindications: ["Alergia a penicilinas"],
      interactions: ["Alopurinol", "Metotrexato", "Anticoagulantes"],
    },
    {
      code: "RENAME031",
      commercialName: "Azitromicina",
      activeIngredient: "Azitromicina di-hidratada",
      therapeuticClass: "Antibiótico (Macrolídeo)",
      presentation: "500mg comprimido",
      concentration: "500mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: false,
      pediatricDosePerKg: "10mg/kg no 1º dia, depois 5mg/kg por 4 dias",
      contraindications: ["Alergia a macrolídeos", "Insuficiência hepática grave"],
      interactions: ["Ergotamina", "Digoxina", "Varfarina"],
    },
    {
      code: "RENAME032",
      commercialName: "Cefalexina",
      activeIngredient: "Cefalexina mono-hidratada",
      therapeuticClass: "Antibiótico (Cefalosporina 1ª geração)",
      presentation: "500mg cápsula",
      concentration: "500mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: false,
      pediatricDosePerKg: "25-50mg/kg/dia dividido em 6/6h",
      contraindications: ["Alergia a cefalosporinas (reação cruzada penicilinas)"],
      interactions: ["Probenecida", "Aminoglicosídeos"],
    },
    
    // MEDICAMENTOS CONTROLADOS (Portaria 344/98)
    {
      code: "RENAME100",
      commercialName: "Diazepam",
      activeIngredient: "Diazepam",
      therapeuticClass: "Benzodiazepínico",
      presentation: "10mg comprimido",
      concentration: "10mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: true,
      controlType: "B1" as const,
      maxPrescriptionDays: 60,
      requiresSpecialForm: true,
      contraindications: ["Miastenia gravis", "Insuficiência respiratória grave", "Glaucoma de ângulo fechado"],
      interactions: ["Álcool", "Opioides", "Antipsicóticos", "Barbitúricos"],
    },
    {
      code: "RENAME101",
      commercialName: "Clonazepam",
      activeIngredient: "Clonazepam",
      therapeuticClass: "Benzodiazepínico",
      presentation: "2mg comprimido",
      concentration: "2mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: true,
      controlType: "B1" as const,
      maxPrescriptionDays: 60,
      requiresSpecialForm: true,
      contraindications: ["Miastenia gravis", "Insuficiência respiratória grave"],
      interactions: ["Álcool", "Opioides", "Carbamazepina"],
    },
    {
      code: "RENAME102",
      commercialName: "Fluoxetina",
      activeIngredient: "Cloridrato de fluoxetina",
      therapeuticClass: "Antidepressivo (ISRS)",
      presentation: "20mg cápsula",
      concentration: "20mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: true,
      controlType: "C1" as const,
      maxPrescriptionDays: 60,
      requiresSpecialForm: false,
      contraindications: ["Uso de IMAO nos últimos 14 dias", "Pimozida"],
      interactions: ["IMAO", "Tramadol", "Varfarina", "Carbamazepina"],
    },
    {
      code: "RENAME103",
      commercialName: "Sertralina",
      activeIngredient: "Cloridrato de sertralina",
      therapeuticClass: "Antidepressivo (ISRS)",
      presentation: "50mg comprimido",
      concentration: "50mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: true,
      controlType: "C1" as const,
      maxPrescriptionDays: 60,
      requiresSpecialForm: false,
      contraindications: ["Uso de IMAO nos últimos 14 dias", "Pimozida"],
      interactions: ["IMAO", "Tramadol", "Varfarina"],
    },
    {
      code: "RENAME104",
      commercialName: "Amitriptilina",
      activeIngredient: "Cloridrato de amitriptilina",
      therapeuticClass: "Antidepressivo tricíclico",
      presentation: "25mg comprimido",
      concentration: "25mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: true,
      controlType: "C1" as const,
      maxPrescriptionDays: 60,
      requiresSpecialForm: false,
      contraindications: ["IAM recente", "Arritmias", "Glaucoma de ângulo fechado"],
      interactions: ["IMAO", "Álcool", "Anticolinérgicos"],
    },
    {
      code: "RENAME105",
      commercialName: "Codeína + Paracetamol",
      activeIngredient: "Fosfato de codeína + Paracetamol",
      therapeuticClass: "Analgésico opioide",
      presentation: "30mg + 500mg comprimido",
      concentration: "30mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: true,
      controlType: "A2" as const,
      maxPrescriptionDays: 30,
      requiresSpecialForm: true,
      contraindications: ["Depressão respiratória", "Asma aguda", "Íleo paralítico"],
      interactions: ["Álcool", "Benzodiazepínicos", "IMAO"],
    },
    {
      code: "RENAME106",
      commercialName: "Tramadol",
      activeIngredient: "Cloridrato de tramadol",
      therapeuticClass: "Analgésico opioide atípico",
      presentation: "50mg cápsula",
      concentration: "50mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: true,
      controlType: "A2" as const,
      maxPrescriptionDays: 30,
      requiresSpecialForm: true,
      contraindications: ["Epilepsia não controlada", "Uso de IMAO"],
      interactions: ["ISRS", "IMAO", "Carbamazepina"],
    },
    
    // ANTI-INFLAMATÓRIOS E CORTICOIDES
    {
      code: "RENAME040",
      commercialName: "Prednisona",
      activeIngredient: "Prednisona",
      therapeuticClass: "Corticosteroide",
      presentation: "20mg comprimido",
      concentration: "20mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: false,
      pediatricDosePerKg: "0.5-2mg/kg/dia",
      contraindications: ["Infecções fúngicas sistêmicas", "Herpes ocular"],
      interactions: ["AINEs", "Anticoagulantes", "Antidiabéticos"],
    },
    {
      code: "RENAME041",
      commercialName: "Dexametasona",
      activeIngredient: "Dexametasona",
      therapeuticClass: "Corticosteroide",
      presentation: "4mg comprimido",
      concentration: "4mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: false,
      pediatricDosePerKg: "0.08-0.3mg/kg/dia",
      contraindications: ["Infecções fúngicas sistêmicas"],
      interactions: ["AINEs", "Fenitoína", "Rifampicina"],
    },
    
    // ANTICONVULSIVANTES
    {
      code: "RENAME050",
      commercialName: "Carbamazepina",
      activeIngredient: "Carbamazepina",
      therapeuticClass: "Anticonvulsivante",
      presentation: "200mg comprimido",
      concentration: "200mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: true,
      controlType: "C1" as const,
      maxPrescriptionDays: 60,
      requiresSpecialForm: false,
      pediatricDosePerKg: "10-20mg/kg/dia dividido em 2-3 tomadas",
      contraindications: ["Bloqueio AV", "Porfiria", "Uso de IMAO"],
      interactions: ["Varfarina", "Contraceptivos orais", "Antidepressivos"],
    },
    {
      code: "RENAME051",
      commercialName: "Fenitoína",
      activeIngredient: "Fenitoína sódica",
      therapeuticClass: "Anticonvulsivante",
      presentation: "100mg comprimido",
      concentration: "100mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: true,
      controlType: "C1" as const,
      maxPrescriptionDays: 60,
      requiresSpecialForm: false,
      pediatricDosePerKg: "5-8mg/kg/dia dividido em 2-3 tomadas",
      contraindications: ["Bradicardia", "Bloqueio sinoatrial"],
      interactions: ["Varfarina", "Corticoides", "Contraceptivos orais"],
    },
    {
      code: "RENAME052",
      commercialName: "Ácido Valproico",
      activeIngredient: "Valproato de sódio",
      therapeuticClass: "Anticonvulsivante",
      presentation: "500mg comprimido",
      concentration: "500mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: true,
      controlType: "C1" as const,
      maxPrescriptionDays: 60,
      requiresSpecialForm: false,
      pediatricDosePerKg: "15-60mg/kg/dia dividido em 2-3 tomadas",
      contraindications: ["Hepatopatia grave", "Gestação (1º trimestre)"],
      interactions: ["Carbamazepina", "Lamotrigina", "AAS"],
    },
    
    // ANTIALÉRGICOS
    {
      code: "RENAME060",
      commercialName: "Loratadina",
      activeIngredient: "Loratadina",
      therapeuticClass: "Anti-histamínico",
      presentation: "10mg comprimido",
      concentration: "10mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: false,
      pediatricDosePerKg: "5mg/dia (2-5 anos) ou 10mg/dia (>6 anos)",
      contraindications: ["Hipersensibilidade"],
      interactions: ["Eritromicina", "Cetoconazol"],
    },
    {
      code: "RENAME061",
      commercialName: "Prometazina",
      activeIngredient: "Cloridrato de prometazina",
      therapeuticClass: "Anti-histamínico sedativo",
      presentation: "25mg comprimido",
      concentration: "25mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: false,
      pediatricDosePerKg: "0.25-0.5mg/kg a cada 6-12h",
      contraindications: ["Glaucoma de ângulo fechado", "Retenção urinária", "<2 anos"],
      interactions: ["Álcool", "Depressores do SNC", "Anticolinérgicos"],
    },
    
    // GASTROPROTETORES
    {
      code: "RENAME070",
      commercialName: "Omeprazol",
      activeIngredient: "Omeprazol",
      therapeuticClass: "Inibidor de bomba de prótons",
      presentation: "20mg cápsula",
      concentration: "20mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: false,
      pediatricDosePerKg: "0.7-3.5mg/kg/dia",
      contraindications: ["Hipersensibilidade"],
      interactions: ["Clopidogrel", "Metotrexato", "Atazanavir"],
    },
    {
      code: "RENAME071",
      commercialName: "Ranitidina",
      activeIngredient: "Cloridrato de ranitidina",
      therapeuticClass: "Antagonista H2",
      presentation: "150mg comprimido",
      concentration: "150mg",
      unit: "mg",
      administrationRoute: "oral" as const,
      isControlled: false,
      pediatricDosePerKg: "2-4mg/kg 12/12h",
      contraindications: ["Porfiria aguda"],
      interactions: ["Varfarina", "Teofilina", "Procainamida"],
    },
  ];
  
  try {
    for (const med of medications) {
      await db.insert(renameCatalog)
        .values({
          ...med,
          active: true,
        })
        .onConflictDoUpdate({
          target: renameCatalog.code,
          set: {
            commercialName: med.commercialName,
            activeIngredient: med.activeIngredient,
            therapeuticClass: med.therapeuticClass,
            presentation: med.presentation,
            concentration: med.concentration,
            unit: med.unit,
            administrationRoute: med.administrationRoute,
            isControlled: med.isControlled,
            controlType: med.controlType || null,
            maxPrescriptionDays: med.maxPrescriptionDays || 30,
            requiresSpecialForm: med.requiresSpecialForm || false,
            pediatricDosePerKg: med.pediatricDosePerKg || null,
            contraindications: med.contraindications || null,
            interactions: med.interactions || null,
            active: true,
          },
        });
    }
    
    console.log(`[SEED] ✅ ${medications.length} medicamentos RENAME inseridos/atualizados`);
    return { success: true, count: medications.length };
  } catch (error) {
    console.error("[SEED] ❌ Erro ao inserir catálogo RENAME:", error);
    throw error;
  }
}

export default seedRENAMECatalog;
