/**
 * Serviço de CIAP-2 e CID-10
 * Autocomplete e validação de códigos diagnósticos
 * Conforme e-SUS PEC v5.3
 * 
 * @module ciap2Cid10Service
 */

// CIAP-2 - Classificação Internacional de Atenção Primária 2ª edição
export const CIAP2_CODES: Array<{ code: string; description: string; chapter: string }> = [
  // A - Geral e Inespecífico
  { code: 'A01', description: 'Dor generalizada/múltiplos locais', chapter: 'A' },
  { code: 'A02', description: 'Calafrios', chapter: 'A' },
  { code: 'A03', description: 'Febre', chapter: 'A' },
  { code: 'A04', description: 'Debilidade/cansaço geral/fadiga', chapter: 'A' },
  { code: 'A05', description: 'Sensação de estar doente', chapter: 'A' },
  { code: 'A06', description: 'Desmaio/síncope', chapter: 'A' },
  { code: 'A07', description: 'Coma', chapter: 'A' },
  { code: 'A08', description: 'Edema', chapter: 'A' },
  { code: 'A09', description: 'Problemas de transpiração', chapter: 'A' },
  { code: 'A10', description: 'Hemorragia/sangramento NE', chapter: 'A' },
  { code: 'A11', description: 'Dor torácica NE', chapter: 'A' },
  { code: 'A13', description: 'Preocupação com/medo de tratamento médico', chapter: 'A' },
  { code: 'A70', description: 'Tuberculose', chapter: 'A' },
  { code: 'A71', description: 'Sarampo', chapter: 'A' },
  { code: 'A72', description: 'Varicela', chapter: 'A' },
  { code: 'A73', description: 'Malária', chapter: 'A' },
  { code: 'A74', description: 'Rubéola', chapter: 'A' },
  { code: 'A75', description: 'Mononucleose infecciosa', chapter: 'A' },
  { code: 'A76', description: 'Outras doenças virais com exantema', chapter: 'A' },
  { code: 'A77', description: 'Outras doenças virais NE', chapter: 'A' },
  { code: 'A78', description: 'Outras doenças infecciosas NE', chapter: 'A' },
  { code: 'A84', description: 'Intoxicação por medicamentos', chapter: 'A' },
  { code: 'A85', description: 'Efeito adverso de medicamento', chapter: 'A' },
  { code: 'A86', description: 'Efeitos tóxicos substâncias não medicinais', chapter: 'A' },
  { code: 'A87', description: 'Complicação de tratamento médico', chapter: 'A' },
  { code: 'A88', description: 'Efeitos adversos de fatores físicos', chapter: 'A' },
  { code: 'A89', description: 'Efeito adverso de prótese/dispositivo', chapter: 'A' },
  { code: 'A90', description: 'Anomalia congênita múltipla NE', chapter: 'A' },
  { code: 'A91', description: 'Resultado de investigação anormal NE', chapter: 'A' },
  { code: 'A92', description: 'Alergia/reação alérgica NE', chapter: 'A' },
  { code: 'A93', description: 'Recém-nascido prematuro', chapter: 'A' },
  { code: 'A94', description: 'Morbilidade perinatal outra', chapter: 'A' },
  { code: 'A95', description: 'Mortalidade perinatal', chapter: 'A' },
  { code: 'A96', description: 'Morte', chapter: 'A' },
  { code: 'A97', description: 'Sem doença', chapter: 'A' },
  { code: 'A98', description: 'Medicina preventiva/manutenção de saúde', chapter: 'A' },
  { code: 'A99', description: 'Doença/condição de natureza NE outra', chapter: 'A' },
  
  // B - Sangue, Órgãos Hematopoiéticos e Sistema Imunitário
  { code: 'B02', description: 'Adenopatia/dor de gânglio linfático', chapter: 'B' },
  { code: 'B04', description: 'Sinais/sintomas do sangue', chapter: 'B' },
  { code: 'B25', description: 'Medo de AIDS/HIV', chapter: 'B' },
  { code: 'B26', description: 'Medo de cancro de sangue', chapter: 'B' },
  { code: 'B27', description: 'Medo de outra doença de sangue/linfático', chapter: 'B' },
  { code: 'B70', description: 'Linfadenite aguda', chapter: 'B' },
  { code: 'B71', description: 'Linfadenite crônica/inespecífica', chapter: 'B' },
  { code: 'B72', description: 'Doença de Hodgkin/linfoma', chapter: 'B' },
  { code: 'B73', description: 'Leucemia', chapter: 'B' },
  { code: 'B74', description: 'Outra neoplasia maligna de sangue', chapter: 'B' },
  { code: 'B75', description: 'Neoplasia benigna/inespecífica sangue', chapter: 'B' },
  { code: 'B76', description: 'Ruptura traumática do baço', chapter: 'B' },
  { code: 'B78', description: 'Anemia hemolítica hereditária', chapter: 'B' },
  { code: 'B79', description: 'Outras anomalias congênitas de sangue', chapter: 'B' },
  { code: 'B80', description: 'Anemia por deficiência de ferro', chapter: 'B' },
  { code: 'B81', description: 'Anemia por deficiência de vitamina B12/folato', chapter: 'B' },
  { code: 'B82', description: 'Outras anemias/inespecíficas', chapter: 'B' },
  { code: 'B83', description: 'Púrpura/defeitos de coagulação', chapter: 'B' },
  { code: 'B84', description: 'Glóbulos brancos anormais', chapter: 'B' },
  { code: 'B87', description: 'Esplenomegalia', chapter: 'B' },
  { code: 'B90', description: 'Infecção por HIV/AIDS', chapter: 'B' },
  { code: 'B99', description: 'Outras doenças do sangue/linfáticos NE', chapter: 'B' },
  
  // D - Aparelho Digestivo
  { code: 'D01', description: 'Dor abdominal generalizada/cólicas', chapter: 'D' },
  { code: 'D02', description: 'Dor de estômago/epigástrica', chapter: 'D' },
  { code: 'D03', description: 'Azia', chapter: 'D' },
  { code: 'D04', description: 'Dor anal/retal', chapter: 'D' },
  { code: 'D05', description: 'Perturbação da deglutição/perianal', chapter: 'D' },
  { code: 'D06', description: 'Outras dores abdominais localizadas', chapter: 'D' },
  { code: 'D07', description: 'Dispepsia/indigestão', chapter: 'D' },
  { code: 'D08', description: 'Flatulência/gases/distensão abdominal', chapter: 'D' },
  { code: 'D09', description: 'Náusea', chapter: 'D' },
  { code: 'D10', description: 'Vômito', chapter: 'D' },
  { code: 'D11', description: 'Diarreia', chapter: 'D' },
  { code: 'D12', description: 'Constipação', chapter: 'D' },
  { code: 'D13', description: 'Icterícia', chapter: 'D' },
  { code: 'D14', description: 'Hematêmese/vômito de sangue', chapter: 'D' },
  { code: 'D15', description: 'Melena', chapter: 'D' },
  { code: 'D16', description: 'Hemorragia retal', chapter: 'D' },
  { code: 'D17', description: 'Incontinência fecal', chapter: 'D' },
  { code: 'D18', description: 'Alteração das fezes/movimentos intestinais', chapter: 'D' },
  { code: 'D19', description: 'Sinais/sintomas dentes e gengivas', chapter: 'D' },
  { code: 'D20', description: 'Sinais/sintomas boca/língua/lábios', chapter: 'D' },
  { code: 'D21', description: 'Problemas de deglutição', chapter: 'D' },
  { code: 'D70', description: 'Infecção gastrointestinal', chapter: 'D' },
  { code: 'D71', description: 'Parotidite epidêmica/caxumba', chapter: 'D' },
  { code: 'D72', description: 'Hepatite viral', chapter: 'D' },
  { code: 'D73', description: 'Gastroenterite presumível infecção', chapter: 'D' },
  { code: 'D74', description: 'Neoplasias malignas do estômago', chapter: 'D' },
  { code: 'D75', description: 'Neoplasias malignas do cólon/reto', chapter: 'D' },
  { code: 'D76', description: 'Neoplasias malignas do pâncreas', chapter: 'D' },
  { code: 'D77', description: 'Outras neoplasias malignas digestivas', chapter: 'D' },
  { code: 'D78', description: 'Neoplasias benignas digestivas', chapter: 'D' },
  { code: 'D79', description: 'Corpo estranho no aparelho digestivo', chapter: 'D' },
  { code: 'D80', description: 'Outras lesões do aparelho digestivo', chapter: 'D' },
  { code: 'D81', description: 'Anomalias congênitas digestivas', chapter: 'D' },
  { code: 'D82', description: 'Doenças dos dentes/gengivas', chapter: 'D' },
  { code: 'D83', description: 'Doenças da boca/língua/lábios', chapter: 'D' },
  { code: 'D84', description: 'Doenças do esôfago', chapter: 'D' },
  { code: 'D85', description: 'Úlcera duodenal', chapter: 'D' },
  { code: 'D86', description: 'Outra úlcera péptica', chapter: 'D' },
  { code: 'D87', description: 'Perturbação funcional do estômago', chapter: 'D' },
  { code: 'D88', description: 'Apendicite', chapter: 'D' },
  { code: 'D89', description: 'Hérnia inguinal', chapter: 'D' },
  { code: 'D90', description: 'Hérnia hiatal', chapter: 'D' },
  { code: 'D91', description: 'Outras hérnias abdominais', chapter: 'D' },
  { code: 'D92', description: 'Doença diverticular do intestino', chapter: 'D' },
  { code: 'D93', description: 'Síndrome do intestino irritável', chapter: 'D' },
  { code: 'D94', description: 'Enterite crônica/colite ulcerosa', chapter: 'D' },
  { code: 'D95', description: 'Fissura anal/fístula perianal', chapter: 'D' },
  { code: 'D96', description: 'Lombrigas/outros parasitas', chapter: 'D' },
  { code: 'D97', description: 'Doenças do fígado NE', chapter: 'D' },
  { code: 'D98', description: 'Colecistite/colelitíase', chapter: 'D' },
  { code: 'D99', description: 'Outras doenças do aparelho digestivo', chapter: 'D' },
  
  // K - Aparelho Circulatório
  { code: 'K01', description: 'Dor cardíaca atribuída ao coração', chapter: 'K' },
  { code: 'K02', description: 'Pressão/aperto cardíaco', chapter: 'K' },
  { code: 'K03', description: 'Dor cardiovascular NE', chapter: 'K' },
  { code: 'K04', description: 'Palpitações/percepção batimento cardíaco', chapter: 'K' },
  { code: 'K05', description: 'Outras irregularidades ritmo cardíaco', chapter: 'K' },
  { code: 'K06', description: 'Veias proeminentes', chapter: 'K' },
  { code: 'K07', description: 'Edema/tornozelos inchados', chapter: 'K' },
  { code: 'K22', description: 'Fator de risco doença cardiovascular', chapter: 'K' },
  { code: 'K24', description: 'Medo de doença cardíaca', chapter: 'K' },
  { code: 'K25', description: 'Medo de hipertensão', chapter: 'K' },
  { code: 'K27', description: 'Medo outra doença cardiovascular', chapter: 'K' },
  { code: 'K74', description: 'Angina de peito', chapter: 'K' },
  { code: 'K75', description: 'Infarto agudo do miocárdio', chapter: 'K' },
  { code: 'K76', description: 'Doença isquêmica crônica do coração', chapter: 'K' },
  { code: 'K77', description: 'Insuficiência cardíaca', chapter: 'K' },
  { code: 'K78', description: 'Fibrilação/flutter auricular', chapter: 'K' },
  { code: 'K79', description: 'Taquicardia paroxística', chapter: 'K' },
  { code: 'K80', description: 'Arritmia cardíaca NE', chapter: 'K' },
  { code: 'K81', description: 'Sopro cardíaco/arterial NE', chapter: 'K' },
  { code: 'K82', description: 'Doença cardíaca pulmonar', chapter: 'K' },
  { code: 'K83', description: 'Doença valvular cardíaca', chapter: 'K' },
  { code: 'K84', description: 'Outra doença cardíaca', chapter: 'K' },
  { code: 'K85', description: 'Elevação da pressão arterial', chapter: 'K' },
  { code: 'K86', description: 'Hipertensão não complicada', chapter: 'K' },
  { code: 'K87', description: 'Hipertensão com complicações', chapter: 'K' },
  { code: 'K88', description: 'Hipotensão postural', chapter: 'K' },
  { code: 'K89', description: 'Isquemia cerebral transitória', chapter: 'K' },
  { code: 'K90', description: 'Acidente vascular cerebral', chapter: 'K' },
  { code: 'K91', description: 'Doença vascular cerebral', chapter: 'K' },
  { code: 'K92', description: 'Aterosclerose/doença vascular periférica', chapter: 'K' },
  { code: 'K93', description: 'Embolia pulmonar', chapter: 'K' },
  { code: 'K94', description: 'Flebite e tromboflebite', chapter: 'K' },
  { code: 'K95', description: 'Varizes das pernas', chapter: 'K' },
  { code: 'K96', description: 'Hemorróidas', chapter: 'K' },
  { code: 'K99', description: 'Outras doenças do aparelho circulatório', chapter: 'K' },
  
  // L - Sistema Músculo-Esquelético
  { code: 'L01', description: 'Sinais/sintomas do pescoço', chapter: 'L' },
  { code: 'L02', description: 'Sinais/sintomas da região dorsal', chapter: 'L' },
  { code: 'L03', description: 'Sinais/sintomas lombar', chapter: 'L' },
  { code: 'L04', description: 'Sinais/sintomas torácico', chapter: 'L' },
  { code: 'L05', description: 'Sinais/sintomas de flancos e axilas', chapter: 'L' },
  { code: 'L07', description: 'Sinais/sintomas do tornozelo', chapter: 'L' },
  { code: 'L08', description: 'Sinais/sintomas do ombro', chapter: 'L' },
  { code: 'L09', description: 'Sinais/sintomas do braço', chapter: 'L' },
  { code: 'L10', description: 'Sinais/sintomas do cotovelo', chapter: 'L' },
  { code: 'L11', description: 'Sinais/sintomas do punho', chapter: 'L' },
  { code: 'L12', description: 'Sinais/sintomas da mão e dedos', chapter: 'L' },
  { code: 'L13', description: 'Sinais/sintomas do quadril', chapter: 'L' },
  { code: 'L14', description: 'Sinais/sintomas da coxa e perna', chapter: 'L' },
  { code: 'L15', description: 'Sinais/sintomas do joelho', chapter: 'L' },
  { code: 'L16', description: 'Sinais/sintomas do tornozelo', chapter: 'L' },
  { code: 'L17', description: 'Sinais/sintomas do pé e dedos', chapter: 'L' },
  { code: 'L18', description: 'Dor muscular', chapter: 'L' },
  { code: 'L19', description: 'Outros sinais/sintomas musculares NE', chapter: 'L' },
  { code: 'L20', description: 'Sinais/sintomas articulares NE', chapter: 'L' },
  { code: 'L70', description: 'Infecção aparelho músculo-esquelético', chapter: 'L' },
  { code: 'L71', description: 'Neoplasia maligna músculo-esquelético', chapter: 'L' },
  { code: 'L72', description: 'Fratura: rádio/cúbito', chapter: 'L' },
  { code: 'L73', description: 'Fratura: tíbia/perôneo', chapter: 'L' },
  { code: 'L74', description: 'Fratura: ossos da mão/pé', chapter: 'L' },
  { code: 'L75', description: 'Fratura: fêmur', chapter: 'L' },
  { code: 'L76', description: 'Outras fraturas', chapter: 'L' },
  { code: 'L77', description: 'Entorses e distensões do tornozelo', chapter: 'L' },
  { code: 'L78', description: 'Entorses e distensões do joelho', chapter: 'L' },
  { code: 'L79', description: 'Entorses e distensões outras articulações', chapter: 'L' },
  { code: 'L80', description: 'Luxação e subluxação', chapter: 'L' },
  { code: 'L81', description: 'Outras lesões músculo-esqueléticas NE', chapter: 'L' },
  { code: 'L82', description: 'Anomalias congênitas músculo-esqueléticas', chapter: 'L' },
  { code: 'L83', description: 'Síndrome pescoço', chapter: 'L' },
  { code: 'L84', description: 'Síndrome dorso sem irradiação', chapter: 'L' },
  { code: 'L85', description: 'Deformação adquirida da coluna', chapter: 'L' },
  { code: 'L86', description: 'Síndrome lombar com irradiação', chapter: 'L' },
  { code: 'L87', description: 'Bursite/tendinite/sinovite NE', chapter: 'L' },
  { code: 'L88', description: 'Artrite reumatóide/seropositiva', chapter: 'L' },
  { code: 'L89', description: 'Artrose do quadril', chapter: 'L' },
  { code: 'L90', description: 'Artrose do joelho', chapter: 'L' },
  { code: 'L91', description: 'Outra artrose/afecção articular', chapter: 'L' },
  { code: 'L92', description: 'Síndrome do ombro', chapter: 'L' },
  { code: 'L93', description: 'Epicondilite lateral', chapter: 'L' },
  { code: 'L94', description: 'Osteocondrose', chapter: 'L' },
  { code: 'L95', description: 'Osteoporose', chapter: 'L' },
  { code: 'L96', description: 'Lesão aguda interna do joelho', chapter: 'L' },
  { code: 'L97', description: 'Neoplasia benigna/inespecífica músculo', chapter: 'L' },
  { code: 'L98', description: 'Deformação adquirida de membro', chapter: 'L' },
  { code: 'L99', description: 'Outras doenças músculo-esqueléticas', chapter: 'L' },
  
  // P - Psicológico
  { code: 'P01', description: 'Sensação de ansiedade/nervosismo/tensão', chapter: 'P' },
  { code: 'P02', description: 'Reação aguda ao stress', chapter: 'P' },
  { code: 'P03', description: 'Sensação de depressão', chapter: 'P' },
  { code: 'P04', description: 'Sensação/comportamento irritável/zangado', chapter: 'P' },
  { code: 'P05', description: 'Senilidade', chapter: 'P' },
  { code: 'P06', description: 'Perturbação do sono', chapter: 'P' },
  { code: 'P07', description: 'Diminuição do desejo sexual', chapter: 'P' },
  { code: 'P08', description: 'Diminuição da satisfação sexual', chapter: 'P' },
  { code: 'P09', description: 'Preocupação com preferência sexual', chapter: 'P' },
  { code: 'P10', description: 'Gaguez/tiques/hipercinésia', chapter: 'P' },
  { code: 'P11', description: 'Problemas alimentares da criança', chapter: 'P' },
  { code: 'P12', description: 'Enurese', chapter: 'P' },
  { code: 'P13', description: 'Encoprese', chapter: 'P' },
  { code: 'P15', description: 'Abuso crônico do álcool', chapter: 'P' },
  { code: 'P16', description: 'Abuso agudo do álcool', chapter: 'P' },
  { code: 'P17', description: 'Abuso do tabaco', chapter: 'P' },
  { code: 'P18', description: 'Abuso de medicamentos', chapter: 'P' },
  { code: 'P19', description: 'Abuso de drogas', chapter: 'P' },
  { code: 'P20', description: 'Perturbação da memória', chapter: 'P' },
  { code: 'P22', description: 'Sinais/sintomas comportamento criança', chapter: 'P' },
  { code: 'P23', description: 'Sinais/sintomas comportamento adolescente', chapter: 'P' },
  { code: 'P24', description: 'Problemas específicos de aprendizagem', chapter: 'P' },
  { code: 'P25', description: 'Problema de fase de vida adulto', chapter: 'P' },
  { code: 'P27', description: 'Medo de perturbação mental', chapter: 'P' },
  { code: 'P28', description: 'Limitação funcional/incapacidade', chapter: 'P' },
  { code: 'P29', description: 'Sinais/sintomas psicológicos outros', chapter: 'P' },
  { code: 'P70', description: 'Demência', chapter: 'P' },
  { code: 'P71', description: 'Outras psicoses orgânicas NE', chapter: 'P' },
  { code: 'P72', description: 'Esquizofrenia', chapter: 'P' },
  { code: 'P73', description: 'Psicose afetiva', chapter: 'P' },
  { code: 'P74', description: 'Perturbação da ansiedade/estado ansiedade', chapter: 'P' },
  { code: 'P75', description: 'Perturbação somatoforme', chapter: 'P' },
  { code: 'P76', description: 'Perturbação depressiva', chapter: 'P' },
  { code: 'P77', description: 'Suicídio/tentativa de suicídio', chapter: 'P' },
  { code: 'P78', description: 'Neurastenia/surmenage', chapter: 'P' },
  { code: 'P79', description: 'Fobia/perturbação compulsiva', chapter: 'P' },
  { code: 'P80', description: 'Perturbação da personalidade', chapter: 'P' },
  { code: 'P81', description: 'Perturbação hipercinética', chapter: 'P' },
  { code: 'P82', description: 'Stress pós-traumático', chapter: 'P' },
  { code: 'P85', description: 'Atraso mental', chapter: 'P' },
  { code: 'P86', description: 'Anorexia nervosa/bulimia', chapter: 'P' },
  { code: 'P98', description: 'Outras psicoses NE', chapter: 'P' },
  { code: 'P99', description: 'Outras perturbações psicológicas', chapter: 'P' },
  
  // R - Aparelho Respiratório
  { code: 'R01', description: 'Dor atribuída ao aparelho respiratório', chapter: 'R' },
  { code: 'R02', description: 'Dificuldade respiratória/dispneia', chapter: 'R' },
  { code: 'R03', description: 'Respiração ruidosa/sibilância', chapter: 'R' },
  { code: 'R04', description: 'Outros problemas respiratórios', chapter: 'R' },
  { code: 'R05', description: 'Tosse', chapter: 'R' },
  { code: 'R06', description: 'Sangramento nasal/epistaxe', chapter: 'R' },
  { code: 'R07', description: 'Espirros/congestão nasal', chapter: 'R' },
  { code: 'R08', description: 'Outros sinais/sintomas nasais', chapter: 'R' },
  { code: 'R09', description: 'Sinais/sintomas dos seios paranasais', chapter: 'R' },
  { code: 'R21', description: 'Sinais/sintomas da garganta', chapter: 'R' },
  { code: 'R23', description: 'Sinais/sintomas da voz', chapter: 'R' },
  { code: 'R24', description: 'Medo de cancro do aparelho respiratório', chapter: 'R' },
  { code: 'R25', description: 'Expectoração/fleuma anormal', chapter: 'R' },
  { code: 'R26', description: 'Medo de outra doença respiratória', chapter: 'R' },
  { code: 'R27', description: 'Medo de doença respiratória NE', chapter: 'R' },
  { code: 'R29', description: 'Outros sinais/sintomas respiratórios', chapter: 'R' },
  { code: 'R71', description: 'Tosse convulsa', chapter: 'R' },
  { code: 'R72', description: 'Infecção estreptocócica da garganta', chapter: 'R' },
  { code: 'R73', description: 'Abcesso/furúnculo do nariz', chapter: 'R' },
  { code: 'R74', description: 'Infecção aguda das vias respiratórias', chapter: 'R' },
  { code: 'R75', description: 'Sinusite aguda/crônica', chapter: 'R' },
  { code: 'R76', description: 'Amigdalite aguda', chapter: 'R' },
  { code: 'R77', description: 'Laringite/traqueíte aguda', chapter: 'R' },
  { code: 'R78', description: 'Bronquite aguda/bronquiolite', chapter: 'R' },
  { code: 'R79', description: 'Bronquite crônica', chapter: 'R' },
  { code: 'R80', description: 'Gripe', chapter: 'R' },
  { code: 'R81', description: 'Pneumonia', chapter: 'R' },
  { code: 'R82', description: 'Pleurisia/derrame pleural', chapter: 'R' },
  { code: 'R83', description: 'Outra infecção respiratória', chapter: 'R' },
  { code: 'R84', description: 'Neoplasia maligna dos brônquios/pulmão', chapter: 'R' },
  { code: 'R85', description: 'Outra neoplasia maligna respiratória', chapter: 'R' },
  { code: 'R86', description: 'Neoplasia benigna aparelho respiratório', chapter: 'R' },
  { code: 'R87', description: 'Corpo estranho nariz/laringe/brônquio', chapter: 'R' },
  { code: 'R88', description: 'Outras lesões do aparelho respiratório', chapter: 'R' },
  { code: 'R89', description: 'Anomalia congênita do aparelho respiratório', chapter: 'R' },
  { code: 'R90', description: 'Hipertrofia amígdalas/adenóides', chapter: 'R' },
  { code: 'R92', description: 'Outra neoplasia NE aparelho respiratório', chapter: 'R' },
  { code: 'R95', description: 'Doença pulmonar obstrutiva crônica', chapter: 'R' },
  { code: 'R96', description: 'Asma', chapter: 'R' },
  { code: 'R97', description: 'Rinite alérgica', chapter: 'R' },
  { code: 'R98', description: 'Síndrome de hiperventilação', chapter: 'R' },
  { code: 'R99', description: 'Outras doenças do aparelho respiratório', chapter: 'R' },
  
  // S - Pele
  { code: 'S01', description: 'Dor/sensibilidade dolorosa da pele', chapter: 'S' },
  { code: 'S02', description: 'Prurido', chapter: 'S' },
  { code: 'S03', description: 'Verrugas', chapter: 'S' },
  { code: 'S04', description: 'Edema/tumefação localizada', chapter: 'S' },
  { code: 'S05', description: 'Nódulos/edema generalizado', chapter: 'S' },
  { code: 'S06', description: 'Erupção cutânea localizada', chapter: 'S' },
  { code: 'S07', description: 'Erupção cutânea generalizada', chapter: 'S' },
  { code: 'S08', description: 'Alterações da cor da pele', chapter: 'S' },
  { code: 'S09', description: 'Dedo inflamado/infectado', chapter: 'S' },
  { code: 'S10', description: 'Furúnculo/carbúnculo', chapter: 'S' },
  { code: 'S11', description: 'Infecção pós-traumática da pele', chapter: 'S' },
  { code: 'S12', description: 'Picada de inseto', chapter: 'S' },
  { code: 'S13', description: 'Mordedura animal/humana', chapter: 'S' },
  { code: 'S14', description: 'Queimadura/escaldão', chapter: 'S' },
  { code: 'S15', description: 'Corpo estranho na pele', chapter: 'S' },
  { code: 'S16', description: 'Contusão/escoriação', chapter: 'S' },
  { code: 'S17', description: 'Abrasão/bolha/ferida', chapter: 'S' },
  { code: 'S18', description: 'Laceração/corte', chapter: 'S' },
  { code: 'S19', description: 'Outra lesão da pele', chapter: 'S' },
  { code: 'S20', description: 'Calos/calosidades', chapter: 'S' },
  { code: 'S21', description: 'Sinais/sintomas da textura da pele', chapter: 'S' },
  { code: 'S22', description: 'Sinais/sintomas das unhas', chapter: 'S' },
  { code: 'S23', description: 'Calvície/queda de cabelo', chapter: 'S' },
  { code: 'S24', description: 'Outros sinais/sintomas pêlos/couro cabeludo', chapter: 'S' },
  { code: 'S26', description: 'Medo de cancro da pele', chapter: 'S' },
  { code: 'S27', description: 'Medo de outra doença da pele', chapter: 'S' },
  { code: 'S29', description: 'Outros sinais/sintomas da pele', chapter: 'S' },
  { code: 'S70', description: 'Herpes zoster', chapter: 'S' },
  { code: 'S71', description: 'Herpes simples', chapter: 'S' },
  { code: 'S72', description: 'Escabiose e outras acaríases', chapter: 'S' },
  { code: 'S73', description: 'Pediculose e outras infestações', chapter: 'S' },
  { code: 'S74', description: 'Dermatofitose', chapter: 'S' },
  { code: 'S75', description: 'Candidíase/monilíase da pele', chapter: 'S' },
  { code: 'S76', description: 'Outra infecção da pele', chapter: 'S' },
  { code: 'S77', description: 'Neoplasia maligna da pele', chapter: 'S' },
  { code: 'S78', description: 'Lipoma', chapter: 'S' },
  { code: 'S79', description: 'Neoplasia benigna/inespecífica da pele', chapter: 'S' },
  { code: 'S80', description: 'Queratose solar/queimadura solar', chapter: 'S' },
  { code: 'S81', description: 'Hemangioma/linfangioma', chapter: 'S' },
  { code: 'S82', description: 'Nevo/sinal', chapter: 'S' },
  { code: 'S83', description: 'Outras lesões congênitas da pele', chapter: 'S' },
  { code: 'S84', description: 'Impetigo', chapter: 'S' },
  { code: 'S85', description: 'Cisto pilonidal/fístula', chapter: 'S' },
  { code: 'S86', description: 'Dermatite seborreica', chapter: 'S' },
  { code: 'S87', description: 'Dermatite atópica/eczema', chapter: 'S' },
  { code: 'S88', description: 'Dermatite de contato/alérgica', chapter: 'S' },
  { code: 'S89', description: 'Erupção das fraldas', chapter: 'S' },
  { code: 'S90', description: 'Pitiríase rosea', chapter: 'S' },
  { code: 'S91', description: 'Psoríase', chapter: 'S' },
  { code: 'S92', description: 'Doenças das glândulas sudoríparas', chapter: 'S' },
  { code: 'S93', description: 'Cisto sebáceo', chapter: 'S' },
  { code: 'S94', description: 'Unha encravada', chapter: 'S' },
  { code: 'S95', description: 'Molusco contagioso', chapter: 'S' },
  { code: 'S96', description: 'Acne', chapter: 'S' },
  { code: 'S97', description: 'Úlcera crônica da pele', chapter: 'S' },
  { code: 'S98', description: 'Urticária', chapter: 'S' },
  { code: 'S99', description: 'Outras doenças da pele', chapter: 'S' },
  
  // T - Endócrino, Metabólico e Nutricional
  { code: 'T01', description: 'Sede excessiva', chapter: 'T' },
  { code: 'T02', description: 'Apetite excessivo', chapter: 'T' },
  { code: 'T03', description: 'Perda de apetite', chapter: 'T' },
  { code: 'T04', description: 'Problemas nutricionais NE', chapter: 'T' },
  { code: 'T05', description: 'Problemas alimentares adulto', chapter: 'T' },
  { code: 'T07', description: 'Ganho de peso', chapter: 'T' },
  { code: 'T08', description: 'Perda de peso', chapter: 'T' },
  { code: 'T10', description: 'Atraso no crescimento', chapter: 'T' },
  { code: 'T11', description: 'Desidratação', chapter: 'T' },
  { code: 'T26', description: 'Medo de cancro endócrino', chapter: 'T' },
  { code: 'T27', description: 'Medo de outra doença endócrina/metabólica', chapter: 'T' },
  { code: 'T29', description: 'Outros sinais/sintomas endócrinos/metabólicos', chapter: 'T' },
  { code: 'T70', description: 'Infecção endócrina', chapter: 'T' },
  { code: 'T71', description: 'Neoplasia maligna tireóide', chapter: 'T' },
  { code: 'T72', description: 'Neoplasia benigna tireóide', chapter: 'T' },
  { code: 'T73', description: 'Outras neoplasias NE endócrinas', chapter: 'T' },
  { code: 'T78', description: 'Cisto do canal tireoglosso', chapter: 'T' },
  { code: 'T80', description: 'Anomalia congênita endócrina/metabólica', chapter: 'T' },
  { code: 'T81', description: 'Bócio', chapter: 'T' },
  { code: 'T82', description: 'Obesidade', chapter: 'T' },
  { code: 'T83', description: 'Excesso de peso', chapter: 'T' },
  { code: 'T85', description: 'Hipertireoidismo/tireotoxicose', chapter: 'T' },
  { code: 'T86', description: 'Hipotireoidismo/mixedema', chapter: 'T' },
  { code: 'T87', description: 'Hipoglicemia', chapter: 'T' },
  { code: 'T89', description: 'Diabetes mellitus insulino-dependente', chapter: 'T' },
  { code: 'T90', description: 'Diabetes mellitus não insulino-dependente', chapter: 'T' },
  { code: 'T91', description: 'Deficiência vitamínica/nutricional', chapter: 'T' },
  { code: 'T92', description: 'Gota', chapter: 'T' },
  { code: 'T93', description: 'Alteração metabolismo lipídico', chapter: 'T' },
  { code: 'T99', description: 'Outras doenças endócrinas/metabólicas/nutricionais', chapter: 'T' },
  
  // U - Aparelho Urinário
  { code: 'U01', description: 'Disúria/micção dolorosa', chapter: 'U' },
  { code: 'U02', description: 'Micção frequente/urgência urinária', chapter: 'U' },
  { code: 'U04', description: 'Incontinência urinária', chapter: 'U' },
  { code: 'U05', description: 'Outros problemas com a micção', chapter: 'U' },
  { code: 'U06', description: 'Hematúria', chapter: 'U' },
  { code: 'U07', description: 'Outros sinais/sintomas urinários', chapter: 'U' },
  { code: 'U08', description: 'Retenção urinária', chapter: 'U' },
  { code: 'U13', description: 'Outros sinais/sintomas da bexiga', chapter: 'U' },
  { code: 'U14', description: 'Sinais/sintomas do rim', chapter: 'U' },
  { code: 'U26', description: 'Medo de cancro do aparelho urinário', chapter: 'U' },
  { code: 'U27', description: 'Medo de outra doença urinária', chapter: 'U' },
  { code: 'U29', description: 'Outros sinais/sintomas do aparelho urinário', chapter: 'U' },
  { code: 'U70', description: 'Pielonefrite/pielite', chapter: 'U' },
  { code: 'U71', description: 'Cistite/outra infecção urinária', chapter: 'U' },
  { code: 'U72', description: 'Uretrite', chapter: 'U' },
  { code: 'U75', description: 'Neoplasia maligna do rim', chapter: 'U' },
  { code: 'U76', description: 'Neoplasia maligna da bexiga', chapter: 'U' },
  { code: 'U77', description: 'Outra neoplasia maligna urinária', chapter: 'U' },
  { code: 'U78', description: 'Neoplasia benigna do aparelho urinário', chapter: 'U' },
  { code: 'U79', description: 'Neoplasia NE do aparelho urinário', chapter: 'U' },
  { code: 'U80', description: 'Lesão do aparelho urinário', chapter: 'U' },
  { code: 'U85', description: 'Anomalia congênita do aparelho urinário', chapter: 'U' },
  { code: 'U88', description: 'Glomerulonefrite/síndrome nefrótica', chapter: 'U' },
  { code: 'U90', description: 'Albuminúria/proteinúria ortostática', chapter: 'U' },
  { code: 'U95', description: 'Cálculo urinário', chapter: 'U' },
  { code: 'U98', description: 'Análise urina anormal NE', chapter: 'U' },
  { code: 'U99', description: 'Outras doenças urinárias', chapter: 'U' },
  
  // W - Gravidez, Parto, Planeamento Familiar
  { code: 'W01', description: 'Questão sobre gravidez', chapter: 'W' },
  { code: 'W02', description: 'Medo de estar grávida', chapter: 'W' },
  { code: 'W03', description: 'Hemorragia anteparto', chapter: 'W' },
  { code: 'W05', description: 'Náuseas/vômitos da gravidez', chapter: 'W' },
  { code: 'W10', description: 'Contracepção pós-coital', chapter: 'W' },
  { code: 'W11', description: 'Contracepção oral', chapter: 'W' },
  { code: 'W12', description: 'Contracepção intra-uterina', chapter: 'W' },
  { code: 'W13', description: 'Esterilização feminina', chapter: 'W' },
  { code: 'W14', description: 'Outros métodos de contracepção feminina', chapter: 'W' },
  { code: 'W15', description: 'Infertilidade/subfertilidade feminina', chapter: 'W' },
  { code: 'W17', description: 'Hemorragia pós-parto', chapter: 'W' },
  { code: 'W18', description: 'Outros sinais/sintomas pós-parto', chapter: 'W' },
  { code: 'W19', description: 'Sinais/sintomas da mama/lactação', chapter: 'W' },
  { code: 'W21', description: 'Preocupação com imagem corporal gravidez', chapter: 'W' },
  { code: 'W27', description: 'Medo de complicações da gravidez', chapter: 'W' },
  { code: 'W28', description: 'Limitação funcional/incapacidade (W)', chapter: 'W' },
  { code: 'W29', description: 'Outros sinais/sintomas gravidez', chapter: 'W' },
  { code: 'W70', description: 'Infecção puerperal/sepsis', chapter: 'W' },
  { code: 'W71', description: 'Outras infecções complicando gravidez', chapter: 'W' },
  { code: 'W72', description: 'Neoplasia maligna relacionada gravidez', chapter: 'W' },
  { code: 'W73', description: 'Neoplasia benigna/inespecífica gravidez', chapter: 'W' },
  { code: 'W75', description: 'Lesão complicando a gravidez', chapter: 'W' },
  { code: 'W76', description: 'Anomalia congênita complicando gravidez', chapter: 'W' },
  { code: 'W78', description: 'Gravidez', chapter: 'W' },
  { code: 'W79', description: 'Gravidez não desejada', chapter: 'W' },
  { code: 'W80', description: 'Gravidez ectópica', chapter: 'W' },
  { code: 'W81', description: 'Toxemia gravídica/pré-eclâmpsia', chapter: 'W' },
  { code: 'W82', description: 'Aborto espontâneo', chapter: 'W' },
  { code: 'W83', description: 'Aborto provocado', chapter: 'W' },
  { code: 'W84', description: 'Gravidez de alto risco', chapter: 'W' },
  { code: 'W85', description: 'Diabetes gestacional', chapter: 'W' },
  { code: 'W90', description: 'Parto não complicado nascido vivo', chapter: 'W' },
  { code: 'W91', description: 'Parto não complicado nado morto', chapter: 'W' },
  { code: 'W92', description: 'Parto complicado nascido vivo', chapter: 'W' },
  { code: 'W93', description: 'Parto complicado nado morto', chapter: 'W' },
  { code: 'W94', description: 'Mastite puerperal', chapter: 'W' },
  { code: 'W95', description: 'Outra doença de mama na gravidez', chapter: 'W' },
  { code: 'W96', description: 'Outras complicações do puerpério', chapter: 'W' },
  { code: 'W99', description: 'Outros problemas da gravidez/parto', chapter: 'W' },
  
  // X - Aparelho Genital Feminino
  { code: 'X01', description: 'Dor genital feminina', chapter: 'X' },
  { code: 'X02', description: 'Dor menstrual', chapter: 'X' },
  { code: 'X03', description: 'Dor intermenstrual', chapter: 'X' },
  { code: 'X04', description: 'Relação sexual dolorosa feminina', chapter: 'X' },
  { code: 'X05', description: 'Menstruação ausente/escassa', chapter: 'X' },
  { code: 'X06', description: 'Menstruação excessiva', chapter: 'X' },
  { code: 'X07', description: 'Menstruação irregular/frequente', chapter: 'X' },
  { code: 'X08', description: 'Hemorragia intermenstrual', chapter: 'X' },
  { code: 'X09', description: 'Sinais/sintomas pré-menstruais', chapter: 'X' },
  { code: 'X10', description: 'Adiamento da menstruação', chapter: 'X' },
  { code: 'X11', description: 'Sinais/sintomas da menopausa/climatério', chapter: 'X' },
  { code: 'X12', description: 'Hemorragia pós-menopausa', chapter: 'X' },
  { code: 'X13', description: 'Hemorragia pós-coital', chapter: 'X' },
  { code: 'X14', description: 'Corrimento vaginal', chapter: 'X' },
  { code: 'X15', description: 'Sinais/sintomas da vagina', chapter: 'X' },
  { code: 'X16', description: 'Sinais/sintomas da vulva', chapter: 'X' },
  { code: 'X17', description: 'Sinais/sintomas da pelve feminina', chapter: 'X' },
  { code: 'X18', description: 'Dor mamária feminina', chapter: 'X' },
  { code: 'X19', description: 'Nódulo/massa mamária feminina', chapter: 'X' },
  { code: 'X20', description: 'Sinais/sintomas do mamilo feminino', chapter: 'X' },
  { code: 'X21', description: 'Outros sinais/sintomas mama feminina', chapter: 'X' },
  { code: 'X22', description: 'Preocupação com aparência mama', chapter: 'X' },
  { code: 'X23', description: 'Medo de DST feminino', chapter: 'X' },
  { code: 'X24', description: 'Medo de disfunção sexual feminina', chapter: 'X' },
  { code: 'X25', description: 'Medo de cancro genital feminino', chapter: 'X' },
  { code: 'X26', description: 'Medo de cancro mama', chapter: 'X' },
  { code: 'X27', description: 'Medo de outra doença genital/mama', chapter: 'X' },
  { code: 'X28', description: 'Limitação funcional/incapacidade (X)', chapter: 'X' },
  { code: 'X29', description: 'Outros sinais/sintomas genital feminino', chapter: 'X' },
  { code: 'X70', description: 'Sífilis feminina', chapter: 'X' },
  { code: 'X71', description: 'Gonorreia feminina', chapter: 'X' },
  { code: 'X72', description: 'Candidíase genital feminina', chapter: 'X' },
  { code: 'X73', description: 'Tricomoníase genital feminina', chapter: 'X' },
  { code: 'X74', description: 'Doença inflamatória pélvica', chapter: 'X' },
  { code: 'X75', description: 'Outra doença inflamatória vagina/vulva', chapter: 'X' },
  { code: 'X76', description: 'Neoplasia maligna da mama feminina', chapter: 'X' },
  { code: 'X77', description: 'Neoplasia maligna do colo do útero', chapter: 'X' },
  { code: 'X78', description: 'Outras neoplasias malignas genitais femininas', chapter: 'X' },
  { code: 'X79', description: 'Neoplasia benigna da mama feminina', chapter: 'X' },
  { code: 'X80', description: 'Neoplasia benigna genital feminina', chapter: 'X' },
  { code: 'X81', description: 'Neoplasia NE genital feminina', chapter: 'X' },
  { code: 'X82', description: 'Lesão do genital feminino', chapter: 'X' },
  { code: 'X83', description: 'Anomalia congênita genital feminina', chapter: 'X' },
  { code: 'X84', description: 'Vaginite/vulvite NE', chapter: 'X' },
  { code: 'X85', description: 'Doença do colo NE', chapter: 'X' },
  { code: 'X86', description: 'Citologia do colo anormal', chapter: 'X' },
  { code: 'X87', description: 'Prolapso uterovaginal', chapter: 'X' },
  { code: 'X88', description: 'Doença fibrocística da mama', chapter: 'X' },
  { code: 'X89', description: 'Síndrome de tensão pré-menstrual', chapter: 'X' },
  { code: 'X90', description: 'Herpes genital feminino', chapter: 'X' },
  { code: 'X91', description: 'Condiloma acuminado feminino', chapter: 'X' },
  { code: 'X92', description: 'Infecção por clamídia feminina', chapter: 'X' },
  { code: 'X99', description: 'Outra doença genital feminino NE', chapter: 'X' },
  
  // Y - Aparelho Genital Masculino
  { code: 'Y01', description: 'Dor no pénis', chapter: 'Y' },
  { code: 'Y02', description: 'Dor no escroto/testículos', chapter: 'Y' },
  { code: 'Y03', description: 'Corrimento uretral masculino', chapter: 'Y' },
  { code: 'Y04', description: 'Outros sinais/sintomas do pénis', chapter: 'Y' },
  { code: 'Y05', description: 'Outros sinais/sintomas escroto/testículos', chapter: 'Y' },
  { code: 'Y06', description: 'Sinais/sintomas da próstata', chapter: 'Y' },
  { code: 'Y07', description: 'Impotência NE', chapter: 'Y' },
  { code: 'Y08', description: 'Outros sinais/sintomas da função sexual masculina', chapter: 'Y' },
  { code: 'Y10', description: 'Infertilidade/subfertilidade masculina', chapter: 'Y' },
  { code: 'Y13', description: 'Esterilização masculina', chapter: 'Y' },
  { code: 'Y14', description: 'Planeamento familiar masculino NE', chapter: 'Y' },
  { code: 'Y16', description: 'Sinais/sintomas mama masculina', chapter: 'Y' },
  { code: 'Y24', description: 'Medo disfunção sexual masculina', chapter: 'Y' },
  { code: 'Y25', description: 'Medo de DST masculino', chapter: 'Y' },
  { code: 'Y26', description: 'Medo de cancro genital masculino', chapter: 'Y' },
  { code: 'Y27', description: 'Medo outra doença genital masculina', chapter: 'Y' },
  { code: 'Y29', description: 'Outros sinais/sintomas genital masculino', chapter: 'Y' },
  { code: 'Y70', description: 'Sífilis masculina', chapter: 'Y' },
  { code: 'Y71', description: 'Gonorreia masculina', chapter: 'Y' },
  { code: 'Y72', description: 'Herpes genital masculino', chapter: 'Y' },
  { code: 'Y73', description: 'Prostatite/vesiculite seminal', chapter: 'Y' },
  { code: 'Y74', description: 'Orquite/epididimite', chapter: 'Y' },
  { code: 'Y75', description: 'Balanite', chapter: 'Y' },
  { code: 'Y76', description: 'Condiloma acuminado masculino', chapter: 'Y' },
  { code: 'Y77', description: 'Neoplasia maligna da próstata', chapter: 'Y' },
  { code: 'Y78', description: 'Outras neoplasias malignas genital masculino', chapter: 'Y' },
  { code: 'Y79', description: 'Neoplasia benigna genital masculino', chapter: 'Y' },
  { code: 'Y80', description: 'Lesão do genital masculino', chapter: 'Y' },
  { code: 'Y81', description: 'Fimose/prepúcio redundante', chapter: 'Y' },
  { code: 'Y82', description: 'Hipospadias', chapter: 'Y' },
  { code: 'Y83', description: 'Testículo não descido', chapter: 'Y' },
  { code: 'Y84', description: 'Outra anomalia congênita genital masculino', chapter: 'Y' },
  { code: 'Y85', description: 'Hipertrofia benigna da próstata', chapter: 'Y' },
  { code: 'Y86', description: 'Hidrocele', chapter: 'Y' },
  { code: 'Y99', description: 'Outra doença genital masculino NE', chapter: 'Y' },
  
  // Z - Problemas Sociais
  { code: 'Z01', description: 'Pobreza/problemas econômicos', chapter: 'Z' },
  { code: 'Z02', description: 'Problemas alimentação/água', chapter: 'Z' },
  { code: 'Z03', description: 'Problemas de habitação/vizinhança', chapter: 'Z' },
  { code: 'Z04', description: 'Problema sócio-cultural', chapter: 'Z' },
  { code: 'Z05', description: 'Problemas de trabalho', chapter: 'Z' },
  { code: 'Z06', description: 'Problema de desemprego', chapter: 'Z' },
  { code: 'Z07', description: 'Problema de educação', chapter: 'Z' },
  { code: 'Z08', description: 'Problema de segurança social', chapter: 'Z' },
  { code: 'Z09', description: 'Problema legal', chapter: 'Z' },
  { code: 'Z10', description: 'Problema de sistema de saúde', chapter: 'Z' },
  { code: 'Z11', description: 'Problema de cumprimento/adesão', chapter: 'Z' },
  { code: 'Z12', description: 'Problema de relação com parceiro', chapter: 'Z' },
  { code: 'Z13', description: 'Problema comportamento do parceiro', chapter: 'Z' },
  { code: 'Z14', description: 'Problema por doença do parceiro', chapter: 'Z' },
  { code: 'Z15', description: 'Perda/falecimento de parceiro', chapter: 'Z' },
  { code: 'Z16', description: 'Problema de relação com filho', chapter: 'Z' },
  { code: 'Z18', description: 'Problema com criança doente', chapter: 'Z' },
  { code: 'Z19', description: 'Perda/morte de criança', chapter: 'Z' },
  { code: 'Z20', description: 'Problema de relação com pais/família', chapter: 'Z' },
  { code: 'Z21', description: 'Problema comportamento pais/família', chapter: 'Z' },
  { code: 'Z22', description: 'Problema com familiar doente', chapter: 'Z' },
  { code: 'Z23', description: 'Perda/morte de familiar', chapter: 'Z' },
  { code: 'Z24', description: 'Problema de relação com amigos', chapter: 'Z' },
  { code: 'Z25', description: 'Experiência de violência/agressão', chapter: 'Z' },
  { code: 'Z27', description: 'Medo de problema social', chapter: 'Z' },
  { code: 'Z28', description: 'Limitação funcional/incapacidade (Z)', chapter: 'Z' },
  { code: 'Z29', description: 'Outros problemas sociais NE', chapter: 'Z' },
];

// CID-10 - Classificação Internacional de Doenças 10ª revisão (códigos mais usados na APS)
export const CID10_CODES: Array<{ code: string; description: string; category: string }> = [
  // Doenças infecciosas e parasitárias
  { code: 'A00', description: 'Cólera', category: 'Infecciosas' },
  { code: 'A01', description: 'Febres tifóide e paratifóide', category: 'Infecciosas' },
  { code: 'A09', description: 'Diarréia e gastroenterite', category: 'Infecciosas' },
  { code: 'A15', description: 'Tuberculose respiratória', category: 'Infecciosas' },
  { code: 'A90', description: 'Dengue', category: 'Infecciosas' },
  { code: 'B15', description: 'Hepatite aguda A', category: 'Infecciosas' },
  { code: 'B16', description: 'Hepatite aguda B', category: 'Infecciosas' },
  { code: 'B17', description: 'Outras hepatites virais agudas', category: 'Infecciosas' },
  { code: 'B18', description: 'Hepatite viral crônica', category: 'Infecciosas' },
  { code: 'B20', description: 'HIV resultando em doenças infecciosas', category: 'Infecciosas' },
  { code: 'B24', description: 'Doença pelo HIV não especificada', category: 'Infecciosas' },
  { code: 'B34', description: 'Infecção viral não especificada', category: 'Infecciosas' },
  { code: 'B35', description: 'Dermatofitose', category: 'Infecciosas' },
  { code: 'B37', description: 'Candidíase', category: 'Infecciosas' },
  
  // Neoplasias
  { code: 'C18', description: 'Neoplasia maligna do cólon', category: 'Neoplasias' },
  { code: 'C34', description: 'Neoplasia maligna dos brônquios e pulmões', category: 'Neoplasias' },
  { code: 'C50', description: 'Neoplasia maligna da mama', category: 'Neoplasias' },
  { code: 'C53', description: 'Neoplasia maligna do colo do útero', category: 'Neoplasias' },
  { code: 'C61', description: 'Neoplasia maligna da próstata', category: 'Neoplasias' },
  { code: 'D50', description: 'Anemia por deficiência de ferro', category: 'Sangue' },
  
  // Doenças endócrinas
  { code: 'E03', description: 'Hipotireoidismo', category: 'Endócrinas' },
  { code: 'E04', description: 'Bócio não-tóxico', category: 'Endócrinas' },
  { code: 'E05', description: 'Tireotoxicose/hipertireoidismo', category: 'Endócrinas' },
  { code: 'E10', description: 'Diabetes mellitus insulino-dependente', category: 'Endócrinas' },
  { code: 'E11', description: 'Diabetes mellitus não insulino-dependente', category: 'Endócrinas' },
  { code: 'E14', description: 'Diabetes mellitus não especificado', category: 'Endócrinas' },
  { code: 'E66', description: 'Obesidade', category: 'Endócrinas' },
  { code: 'E78', description: 'Distúrbios do metabolismo de lipoproteínas', category: 'Endócrinas' },
  
  // Transtornos mentais
  { code: 'F10', description: 'Transtornos mentais por uso de álcool', category: 'Mental' },
  { code: 'F17', description: 'Transtornos mentais por uso de tabaco', category: 'Mental' },
  { code: 'F19', description: 'Transtornos mentais por uso de múltiplas drogas', category: 'Mental' },
  { code: 'F20', description: 'Esquizofrenia', category: 'Mental' },
  { code: 'F31', description: 'Transtorno afetivo bipolar', category: 'Mental' },
  { code: 'F32', description: 'Episódio depressivo', category: 'Mental' },
  { code: 'F33', description: 'Transtorno depressivo recorrente', category: 'Mental' },
  { code: 'F41', description: 'Outros transtornos de ansiedade', category: 'Mental' },
  { code: 'F43', description: 'Reações ao stress e transtornos de ajustamento', category: 'Mental' },
  { code: 'F51', description: 'Distúrbios não-orgânicos do sono', category: 'Mental' },
  
  // Sistema nervoso
  { code: 'G20', description: 'Doença de Parkinson', category: 'Nervoso' },
  { code: 'G30', description: 'Doença de Alzheimer', category: 'Nervoso' },
  { code: 'G40', description: 'Epilepsia', category: 'Nervoso' },
  { code: 'G43', description: 'Enxaqueca', category: 'Nervoso' },
  { code: 'G44', description: 'Outras síndromes de cefaléia', category: 'Nervoso' },
  
  // Doenças do olho e ouvido
  { code: 'H10', description: 'Conjuntivite', category: 'Olho' },
  { code: 'H40', description: 'Glaucoma', category: 'Olho' },
  { code: 'H65', description: 'Otite média não-supurativa', category: 'Ouvido' },
  { code: 'H66', description: 'Otite média supurativa e não especificada', category: 'Ouvido' },
  
  // Sistema circulatório
  { code: 'I10', description: 'Hipertensão essencial (primária)', category: 'Circulatório' },
  { code: 'I11', description: 'Doença cardíaca hipertensiva', category: 'Circulatório' },
  { code: 'I20', description: 'Angina pectoris', category: 'Circulatório' },
  { code: 'I21', description: 'Infarto agudo do miocárdio', category: 'Circulatório' },
  { code: 'I25', description: 'Doença isquêmica crônica do coração', category: 'Circulatório' },
  { code: 'I50', description: 'Insuficiência cardíaca', category: 'Circulatório' },
  { code: 'I63', description: 'Infarto cerebral', category: 'Circulatório' },
  { code: 'I64', description: 'AVC não especificado', category: 'Circulatório' },
  { code: 'I83', description: 'Varizes dos membros inferiores', category: 'Circulatório' },
  { code: 'I84', description: 'Hemorróidas', category: 'Circulatório' },
  
  // Sistema respiratório
  { code: 'J00', description: 'Rinofaringite aguda (resfriado comum)', category: 'Respiratório' },
  { code: 'J01', description: 'Sinusite aguda', category: 'Respiratório' },
  { code: 'J02', description: 'Faringite aguda', category: 'Respiratório' },
  { code: 'J03', description: 'Amigdalite aguda', category: 'Respiratório' },
  { code: 'J06', description: 'Infecções agudas das vias aéreas superiores', category: 'Respiratório' },
  { code: 'J10', description: 'Influenza devida a vírus identificado', category: 'Respiratório' },
  { code: 'J11', description: 'Influenza devida a vírus não identificado', category: 'Respiratório' },
  { code: 'J18', description: 'Pneumonia por microorganismo não especificado', category: 'Respiratório' },
  { code: 'J20', description: 'Bronquite aguda', category: 'Respiratório' },
  { code: 'J30', description: 'Rinite alérgica e vasomotora', category: 'Respiratório' },
  { code: 'J40', description: 'Bronquite não especificada', category: 'Respiratório' },
  { code: 'J42', description: 'Bronquite crônica não especificada', category: 'Respiratório' },
  { code: 'J44', description: 'DPOC', category: 'Respiratório' },
  { code: 'J45', description: 'Asma', category: 'Respiratório' },
  
  // Sistema digestivo
  { code: 'K04', description: 'Doenças da polpa e tecidos periapicais', category: 'Digestivo' },
  { code: 'K05', description: 'Gengivite e doenças periodontais', category: 'Digestivo' },
  { code: 'K21', description: 'Doença de refluxo gastroesofágico', category: 'Digestivo' },
  { code: 'K25', description: 'Úlcera gástrica', category: 'Digestivo' },
  { code: 'K26', description: 'Úlcera duodenal', category: 'Digestivo' },
  { code: 'K29', description: 'Gastrite e duodenite', category: 'Digestivo' },
  { code: 'K30', description: 'Dispepsia funcional', category: 'Digestivo' },
  { code: 'K40', description: 'Hérnia inguinal', category: 'Digestivo' },
  { code: 'K58', description: 'Síndrome do intestino irritável', category: 'Digestivo' },
  { code: 'K59', description: 'Outros transtornos funcionais do intestino', category: 'Digestivo' },
  { code: 'K70', description: 'Doença alcoólica do fígado', category: 'Digestivo' },
  { code: 'K76', description: 'Outras doenças do fígado', category: 'Digestivo' },
  { code: 'K80', description: 'Colelitíase', category: 'Digestivo' },
  
  // Pele
  { code: 'L01', description: 'Impetigo', category: 'Pele' },
  { code: 'L02', description: 'Abscesso, furúnculo e carbúnculo', category: 'Pele' },
  { code: 'L03', description: 'Celulite', category: 'Pele' },
  { code: 'L20', description: 'Dermatite atópica', category: 'Pele' },
  { code: 'L23', description: 'Dermatite alérgica de contato', category: 'Pele' },
  { code: 'L30', description: 'Outras dermatites', category: 'Pele' },
  { code: 'L40', description: 'Psoríase', category: 'Pele' },
  { code: 'L50', description: 'Urticária', category: 'Pele' },
  { code: 'L70', description: 'Acne', category: 'Pele' },
  
  // Sistema músculo-esquelético
  { code: 'M15', description: 'Poliartrose', category: 'Músculo-esquelético' },
  { code: 'M16', description: 'Coxartrose (artrose do quadril)', category: 'Músculo-esquelético' },
  { code: 'M17', description: 'Gonartrose (artrose do joelho)', category: 'Músculo-esquelético' },
  { code: 'M19', description: 'Outras artroses', category: 'Músculo-esquelético' },
  { code: 'M25', description: 'Outros transtornos articulares', category: 'Músculo-esquelético' },
  { code: 'M41', description: 'Escoliose', category: 'Músculo-esquelético' },
  { code: 'M47', description: 'Espondilose', category: 'Músculo-esquelético' },
  { code: 'M51', description: 'Outros transtornos de discos intervertebrais', category: 'Músculo-esquelético' },
  { code: 'M54', description: 'Dorsalgia', category: 'Músculo-esquelético' },
  { code: 'M62', description: 'Outros transtornos musculares', category: 'Músculo-esquelético' },
  { code: 'M75', description: 'Lesões do ombro', category: 'Músculo-esquelético' },
  { code: 'M79', description: 'Outros transtornos dos tecidos moles', category: 'Músculo-esquelético' },
  { code: 'M80', description: 'Osteoporose com fratura patológica', category: 'Músculo-esquelético' },
  { code: 'M81', description: 'Osteoporose sem fratura patológica', category: 'Músculo-esquelético' },
  
  // Sistema geniturinário
  { code: 'N10', description: 'Nefrite túbulo-intersticial aguda', category: 'Geniturinário' },
  { code: 'N18', description: 'Doença renal crônica', category: 'Geniturinário' },
  { code: 'N20', description: 'Calculose do rim e do ureter', category: 'Geniturinário' },
  { code: 'N30', description: 'Cistite', category: 'Geniturinário' },
  { code: 'N39', description: 'Outros transtornos do aparelho urinário', category: 'Geniturinário' },
  { code: 'N40', description: 'Hiperplasia da próstata', category: 'Geniturinário' },
  { code: 'N76', description: 'Outras afecções inflamatórias da vagina e vulva', category: 'Geniturinário' },
  { code: 'N89', description: 'Outros transtornos não-inflamatórios da vagina', category: 'Geniturinário' },
  { code: 'N91', description: 'Menstruação ausente, escassa e infreqüente', category: 'Geniturinário' },
  { code: 'N92', description: 'Menstruação excessiva, freqüente e irregular', category: 'Geniturinário' },
  { code: 'N94', description: 'Dor e afecções associadas a órgãos genitais femininos', category: 'Geniturinário' },
  { code: 'N95', description: 'Transtornos da menopausa e do climatério', category: 'Geniturinário' },
  
  // Gravidez e parto
  { code: 'O00', description: 'Gravidez ectópica', category: 'Gravidez' },
  { code: 'O03', description: 'Aborto espontâneo', category: 'Gravidez' },
  { code: 'O10', description: 'Hipertensão pré-existente complicando gravidez', category: 'Gravidez' },
  { code: 'O13', description: 'Hipertensão gestacional', category: 'Gravidez' },
  { code: 'O14', description: 'Pré-eclâmpsia', category: 'Gravidez' },
  { code: 'O21', description: 'Vômitos excessivos na gravidez', category: 'Gravidez' },
  { code: 'O23', description: 'Infecções do trato geniturinário na gravidez', category: 'Gravidez' },
  { code: 'O24', description: 'Diabetes mellitus na gravidez', category: 'Gravidez' },
  { code: 'O26', description: 'Assistência materna por outras complicações', category: 'Gravidez' },
  { code: 'O80', description: 'Parto único espontâneo', category: 'Gravidez' },
  { code: 'Z32', description: 'Exame ou teste de gravidez', category: 'Gravidez' },
  { code: 'Z33', description: 'Gravidez como achado acidental', category: 'Gravidez' },
  { code: 'Z34', description: 'Supervisão de gravidez normal', category: 'Gravidez' },
  { code: 'Z35', description: 'Supervisão de gravidez de alto risco', category: 'Gravidez' },
  { code: 'Z36', description: 'Rastreamento pré-natal', category: 'Gravidez' },
  
  // Período perinatal
  { code: 'P07', description: 'Transtornos relacionados com a gestação curta e baixo peso', category: 'Perinatal' },
  { code: 'P22', description: 'Desconforto respiratório do recém-nascido', category: 'Perinatal' },
  { code: 'P36', description: 'Septicemia bacteriana do recém-nascido', category: 'Perinatal' },
  { code: 'P59', description: 'Icterícia neonatal', category: 'Perinatal' },
  
  // Sintomas e sinais
  { code: 'R05', description: 'Tosse', category: 'Sintomas' },
  { code: 'R10', description: 'Dor abdominal e pélvica', category: 'Sintomas' },
  { code: 'R11', description: 'Náusea e vômitos', category: 'Sintomas' },
  { code: 'R50', description: 'Febre de origem desconhecida', category: 'Sintomas' },
  { code: 'R51', description: 'Cefaléia', category: 'Sintomas' },
  { code: 'R52', description: 'Dor não classificada em outra parte', category: 'Sintomas' },
  { code: 'R53', description: 'Mal-estar e fadiga', category: 'Sintomas' },
  { code: 'R55', description: 'Síncope e colapso', category: 'Sintomas' },
  { code: 'R63', description: 'Sintomas e sinais relativos à alimentação', category: 'Sintomas' },
  
  // Lesões e causas externas
  { code: 'S00', description: 'Traumatismo superficial da cabeça', category: 'Lesões' },
  { code: 'S01', description: 'Ferimento da cabeça', category: 'Lesões' },
  { code: 'S06', description: 'Traumatismo intracraniano', category: 'Lesões' },
  { code: 'S42', description: 'Fratura do ombro e do braço', category: 'Lesões' },
  { code: 'S52', description: 'Fratura do antebraço', category: 'Lesões' },
  { code: 'S62', description: 'Fratura ao nível do punho e da mão', category: 'Lesões' },
  { code: 'S72', description: 'Fratura do fêmur', category: 'Lesões' },
  { code: 'S82', description: 'Fratura da perna, incluindo tornozelo', category: 'Lesões' },
  { code: 'S92', description: 'Fratura do pé', category: 'Lesões' },
  { code: 'T78', description: 'Efeitos adversos não classificados em outra parte', category: 'Lesões' },
  
  // Fatores que influenciam o estado de saúde
  { code: 'Z00', description: 'Exame geral e investigação de pessoas sem queixas', category: 'Fatores' },
  { code: 'Z01', description: 'Outros exames especiais e investigações', category: 'Fatores' },
  { code: 'Z12', description: 'Exame de rastreamento de neoplasias', category: 'Fatores' },
  { code: 'Z23', description: 'Necessidade de imunização contra doença bacteriana única', category: 'Fatores' },
  { code: 'Z24', description: 'Necessidade de imunização contra certas doenças virais', category: 'Fatores' },
  { code: 'Z25', description: 'Necessidade de imunização contra outras doenças virais', category: 'Fatores' },
  { code: 'Z30', description: 'Anticoncepção', category: 'Fatores' },
  { code: 'Z71', description: 'Pessoas em contato com serviços de saúde para aconselhamento', category: 'Fatores' },
  { code: 'Z72', description: 'Problemas relacionados com o estilo de vida', category: 'Fatores' },
  { code: 'Z76', description: 'Pessoas em contato com serviços de saúde em outras circunstâncias', category: 'Fatores' },
];

// Capítulos CIAP-2
export const CIAP2_CHAPTERS = {
  'A': 'Geral e Inespecífico',
  'B': 'Sangue, Órgãos Hematopoiéticos e Sistema Imunitário',
  'D': 'Aparelho Digestivo',
  'F': 'Olho',
  'H': 'Ouvido',
  'K': 'Aparelho Circulatório',
  'L': 'Sistema Músculo-Esquelético',
  'N': 'Sistema Nervoso',
  'P': 'Psicológico',
  'R': 'Aparelho Respiratório',
  'S': 'Pele',
  'T': 'Endócrino, Metabólico e Nutricional',
  'U': 'Aparelho Urinário',
  'W': 'Gravidez, Parto, Planeamento Familiar',
  'X': 'Aparelho Genital Feminino',
  'Y': 'Aparelho Genital Masculino',
  'Z': 'Problemas Sociais',
};

/**
 * Busca códigos CIAP-2 por texto (código ou descrição)
 */
export function searchCIAP2(query: string, limit: number = 20): Array<{ code: string; description: string; chapter: string }> {
  if (!query || query.length < 2) return [];
  
  const normalizedQuery = query.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  
  return CIAP2_CODES
    .filter(item => {
      const normalizedCode = item.code.toLowerCase();
      const normalizedDesc = item.description.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
      return normalizedCode.includes(normalizedQuery) || normalizedDesc.includes(normalizedQuery);
    })
    .slice(0, limit);
}

/**
 * Busca códigos CID-10 por texto (código ou descrição)
 */
export function searchCID10(query: string, limit: number = 20): Array<{ code: string; description: string; category: string }> {
  if (!query || query.length < 2) return [];
  
  const normalizedQuery = query.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  
  return CID10_CODES
    .filter(item => {
      const normalizedCode = item.code.toLowerCase();
      const normalizedDesc = item.description.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
      return normalizedCode.includes(normalizedQuery) || normalizedDesc.includes(normalizedQuery);
    })
    .slice(0, limit);
}

/**
 * Busca combinada CIAP-2 e CID-10
 */
export function searchDiagnosis(query: string, limit: number = 20): {
  ciap2: Array<{ code: string; description: string; chapter: string }>;
  cid10: Array<{ code: string; description: string; category: string }>;
} {
  return {
    ciap2: searchCIAP2(query, limit),
    cid10: searchCID10(query, limit),
  };
}

/**
 * Valida código CIAP-2
 */
export function isValidCIAP2(code: string): boolean {
  return CIAP2_CODES.some(item => item.code === code.toUpperCase());
}

/**
 * Valida código CID-10
 */
export function isValidCID10(code: string): boolean {
  return CID10_CODES.some(item => item.code === code.toUpperCase());
}

/**
 * Obtém descrição de código CIAP-2
 */
export function getCIAP2Description(code: string): string | null {
  const item = CIAP2_CODES.find(i => i.code === code.toUpperCase());
  return item ? item.description : null;
}

/**
 * Obtém descrição de código CID-10
 */
export function getCID10Description(code: string): string | null {
  const item = CID10_CODES.find(i => i.code === code.toUpperCase());
  return item ? item.description : null;
}

export const ciap2Cid10Service = {
  searchCIAP2,
  searchCID10,
  searchDiagnosis,
  isValidCIAP2,
  isValidCID10,
  getCIAP2Description,
  getCID10Description,
  CIAP2_CODES,
  CID10_CODES,
  CIAP2_CHAPTERS,
};
